import type { SiteCopy } from "./types";

export const ar: SiteCopy = {
  localeName: "العربية",
  seo: {
    home: { title: "مدير هندسة · Web وMobile وAI", description: "خبرة دينيس نادي لأكثر من 11 عاماً في منتجات الويب والمنصات المحمولة والقيادة الهندسية والمصادر المفتوحة والتطوير المدعوم بالذكاء الاصطناعي." },
    work: { title: "أعمال Web وMobile والقيادة الهندسية", description: "أعمال مختارة لدينيس نادي في منتجات الويب والمنصات المحمولة والتقنية المالية والتسليم والمصادر المفتوحة." },
    "open-source": { title: "full_svg_flutter مفتوح المصدر", description: "القصة الهندسية وراء full_svg_flutter، وهو runtime مستقل لعرض SVG الثابت والمتحرك في Flutter." },
    services: { title: "خدمات هندسة Web وMobile وAI", description: "هندسة المنتجات وFlutter والبنية المعمارية وCI/CD وهندسة الإصدارات ومسارات عمل AI العملية." },
    experience: { title: "خبرة القيادة الهندسية", description: "مسار مهني من هندسة البرمجيات العملية إلى قيادة عدة فرق للهندسة المحمولة." },
    about: { title: "عن دينيس نادي", description: "مدير هندسة ومهندس منتجات عملي بخبرة في Web وMobile وAI والبنية المعمارية ومسؤولية الإنتاج." },
    contact: { title: "تواصل مع دينيس نادي", description: "ناقش منتج Web أوMobile أو تحدياً في القيادة الهندسية أو نظام تسليم أو مسار عمل AI عملياً." },
  },
  nav: { home: "الرئيسية", work: "الأعمال", "open-source": "المصدر المفتوح", services: "الخدمات", experience: "الخبرة", about: "عني", contact: "التواصل" },
  common: {
    role: "مدير هندسة · مهندس منتجات Web وMobile وAI",
    location: "تبليسي، جورجيا", availability: "الانتقال إلى أوروبا / العمل عن بُعد",
    menu: "القائمة", language: "اللغة", close: "إغلاق", skip: "الانتقال إلى المحتوى", selectedEvidence: "أدلة مختارة · السيرة الذاتية الحالية",
    discuss: "ناقش مشروعاً", exploreWork: "استكشف الأعمال المختارة", downloadCv: "تنزيل السيرة الذاتية", viewOpenSource: "عرض المصدر المفتوح", viewServices: "عرض الخدمات",
    readArticle: "اقرأ الشرح التقني", visitGithub: "عرض على GitHub", visitPub: "عرض على pub.dev",
    finalTitle: "هل تحتاج إلى بناء منتج رقمي أو تحديثه أو إزالة عوائقه؟", finalBody: "أحضر القيد الحقيقي: Web أوMobile أوتسليم الفريق أومسار عمل AI يجب أن يصبح جاهزاً للإنتاج.",
    contactDenis: "تواصل مع دينيس", external: "يفتح في علامة تبويب جديدة", current: "الصفحة الحالية",
  },
  home: {
    titleLead: "أبني منتجات رقمية —", titleEmphasis: "من Web وMobile إلى تسليم مدعوم بالذكاء الاصطناعي.",
    intro: "أكثر من 11 عاماً في Web وMobile والقيادة الهندسية: أكثر من 100 مشروع ويب، ومنصات Flutter في الإنتاج، وتسليم عبر عدة فرق، وAI كأداة هندسية جدية لا كشعار.",
    proof: [{ value: "+100", label: "منتج Web تم تسليمه" }, { value: "15", label: "مهندساً تمت قيادتهم" }, { value: "+80", label: "إصداراً إنتاجياً" }, { value: "10", label: "تطبيقات على Flutter core مشترك" }, { value: "5 أشهر", label: "من greenfield إلى الإنتاج" }],
    mandateLabel: "نطاق المسؤولية", mandateTitle: "عمق تقني. أثر تنظيمي. نقطة مسؤولية واحدة.", mandateBody: "انتقل دينيس من التسليم العملي إلى القيادة من دون الابتعاد عن البنية المعمارية ومراجعة الكود وحوكمة الإصدارات وتصعيدات الإنتاج. لذلك يستطيع مناقشة خارطة الطريق مع Product، ونمط الفشل مع المهندس، وقرار الإصدار مع Compliance.",
    workLabel: "أعمال مختارة", workTitle: "منتجات معقدة، قابلة للتسليم.", workIntro: "أفضل الأعمال ليست جداراً من الشعارات، بل النظام خلف الإطلاق: مسؤولية واضحة، وبنية معمارية، وضوابط إصدار، وحكم هندسي يعرف متى يبسّط.",
    servicesLabel: "اعمل معي", servicesTitle: "أدخل senior ownership عندما يغيّر النتيجة.", servicesIntro: "للمنتج الذي يحتاج إلى البناء أو الإنقاذ أو التحديث أو التدقيق أو الاستعداد للإنتاج، وللفرق التي تحتاج إلى قيادة تقنية من دون فقدان العمق العملي.",
    openLabel: "هندسة مفتوحة المصدر", openTitle: "يجب أن يبقى SVG بصيغة SVG.", openIntro: "full_svg_flutter هو renderer مستقل لملفات SVG الثابتة والمتحركة في Flutter: ‏SMIL وCSS keyframes وpath morphing وfilters وmasks وtext وملفات SVGator المعتمدة على JavaScript والتحكم بالتشغيل، من دون تحويل الصيغة.",
    careerLabel: "المسار المهني", careerTitle: "من التنفيذ إلى مسؤولية محفظة منتجات.", careerIntro: "أكثر من 11 عاماً عبر Web وfintech وmarketplaces والمنصات المحمولة والمنتجات المنظمة والقيادة الهندسية، مع زيادة النطاق والبقاء قريباً من التقنية.",
    principlesLabel: "نموذج العمل", principlesTitle: "اجعل القيود ظاهرة. وأبقِ المسؤولية صريحة.", principles: ["ابدأ بقيد العمل، لا بالـframework.", "اجعل البنية المعمارية متناسبة مع المنتج والفريق.", "اكشف مخاطر التسليم والإصدار مبكراً.", "أتمت العمل المتكرر في الإصدار ووثّق مسار الاستثناء.", "اشرح المفاضلات بلغة يستطيع صاحب القرار استخدامها.", "اترك المنصة أسهل في التشغيل مما وجدتها."],
  },
  work: {
    title: "أعمال تربط البنية المعمارية بالإنتاج.", intro: "برامج ومنتجات مختارة تحمّل فيها دينيس مسؤولية واضحة عن التسليم أو جودة المنصة أو جزء تقني صعب من النظام. تُعرض نتائج الفريق بوصفها نتائج للفريق.",
    labels: { context: "السياق", responsibility: "المسؤولية", approach: "النهج", outcome: "النتيجة", stack: "التقنيات المختارة" },
    nda: "تستبعد دراسات الحالة عمداً البنية الخاصة وبيانات الاعتماد وتفاصيل المنتجات غير المعلنة والمقاييس التجارية الداخلية.",
    cases: [
      { label: "01 · تسليم متعدد الأسواق", title: "ثلاثة إطلاقات منظمة عبر ثلاث خرائط طريق متوازية", summary: "قيادة محفظة Zinx Romania وBetoro Denmark وYoYo Sweden، مع وصول YoYo إلى الإنتاج خلال نحو خمسة أشهر.", context: "كانت ثلاثة فرق Mobile تعمل لأسواق منظمة مختلفة بينما تتغير الموارد والأولويات والاعتماديات ومتطلبات الامتثال.", responsibility: "قاد محفظة من 15 مهندساً، ودرب Team Lead اثنين، واحتفظ بمسؤولية التسليم وصحة الفرق، ونسّق مع Product وDesign وQA وBackend وPayments وCompliance.", approach: "أنشأ نموذج تشغيل موحداً للتقدير والسعة والاعتماديات والمراحل وبوابات الإصدار، وبقي قريباً من التصعيد التقني لمخاطر signing وnative SDK وWebView bridge والمتاجر والحوادث.", outcome: "وصلت المنتجات الثلاثة إلى مواعيد الإطلاق المنظمة في الوقت المحدد، وانتقل YoYo من التنفيذ الأولي إلى الإنتاج في نحو خمسة أشهر.", stack: "Flutter, Dart, Kotlin, Swift, REST/WebSockets, Firebase, GitLab CI/CD, Codemagic, Fastlane, Sentry/Crashlytics" },
      { label: "02 · تحديث المنصة", title: "Flutter core مشترك ونظام إصدار لعشرة تطبيقات", summary: "تحديث المنصة تحت محفظة متعددة العلامات مع استمرار المنتجات النشطة في التسليم.", context: "شاركت عشرة تطبيقات Flutter core وbrand configuration. أدى تباعد الإصدارات وتكرار إعداد الإطلاق إلى زيادة مخاطر الصيانة والإنتاج.", responsibility: "قاد ترحيل core من Flutter 3.19 إلى 3.38.1 ووحّد مسارات GitLab CI/CD وCodemagic القابلة لإعادة الاستخدام عبر الفرق.", approach: "وحّد إعداد المنصة وقوائم الإصدار ومعايير المراجعة والاختبارات الآلية والمراقبة ومتابعة الحوادث، مع تفويض التنفيذ اليومي إلى Team Leads.", outcome: "قلّل تباعد المنصة والعمل المتكرر، وحسّن ملكية الإصدار، وأنشأ معياراً موحداً للاستعداد للإنتاج عبر المحفظة.", stack: "Flutter 3.19–3.38.1, GitLab CI/CD, Codemagic, Fastlane, automated testing, Sentry, Crashlytics" },
      { label: "03 · عمليات Fintech", title: "منصة عمليات بأكثر من 100 شاشة بُنيت من الصفر", summary: "هندسة Flutter عملية لمنتج عمليات محمي بـVPN يغطي KYC وAML والبطاقات وIBAN والمعاملات والصلاحيات والدعم.", context: "احتاجت العمليات المالية الداخلية إلى واجهة كثيفة وموثوقة بحالات عمل كثيرة وقواعد وصول وتحديثات فورية ومسارات حساسة للامتثال.", responsibility: "كان مطور Flutter الوحيد للمنصة الموصوفة في السيرة الذاتية الحالية، ضمن مؤسسة هندسية أوسع.", approach: "أنشأ tables وforms وpermissions وaccess-control وrealtime components قابلة لإعادة الاستخدام ببنية modular ونموذج تسليم يركز على الاختبار.", outcome: "سلّم أكثر من 100 شاشة إنتاجية في 18 شهراً بنموذج مكونات مشترك حافظ على اتساق التنفيذ عبر مجالات العمليات.", stack: "Flutter Web/Desktop, Dart, Clean Architecture, BLoC, get_it, REST, WebSockets, TDD, unit and golden tests" },
      { label: "04 · تجارة جغرافية", title: "مطابقة التوصيل على مستوى المنزل من دون geocoder مدفوع", summary: "مسار عناوين مخصص مبني على OpenStreetMap لسوق أغذية زراعية يخدم 150,000 مستخدم مسجل.", context: "اعتمدت دقة التوصيل على توحيد العناوين غير المتناسقة ومطابقتها على مستوى المنزل من دون خدمة geocoding مدفوعة.", responsibility: "صمم ونفذ شخصياً مسار geocoding وتوحيد العناوين والمطابقة، إلى جانب catalogue وcart وcheckout وdelivery وsubscription flows.", approach: "دمج بيانات OpenStreetMap مع قواعد توحيد وجغرافيا خاصة بالمنتج ثم ربط النتيجة بمسارات العميل والعمليات.", outcome: "حسّن دقة عناوين التوصيل والموثوقية التشغيلية لمنتج يخدم 150,000 مستخدم مسجل.", stack: "Flutter, Dart, OpenStreetMap, Firebase, REST, Clean Architecture, TDD, native Android/iOS integrations" },
    ],
  },
  openSource: {
    title: "عقلية browser engine داخل Flutter SVG.", intro: "أنشأ دينيس full_svg_flutter ويواصل صيانته، وهو rendering runtime مستقل للفرق التي تحتاج إلى إبقاء ملفات SVG الحالية بصيغتها داخل Flutter.", versionLabel: "لقطة عامة · 17 أغسطس 2026",
    proof: [{ value: "1.4.2", label: "الإصدار الحالي" }, { value: "140", label: "pub points" }, { value: "12", label: "إصداراً عاماً" }, { value: "MIT", label: "رخصة مفتوحة المصدر" }],
    problemTitle: "يعمل الملف في المتصفح، لكن الحركة تختفي في Flutter.", problemBody: "تعالج مسارات كثيرة الفجوة بتحويل الملف إلى Lottie أوRive أوGIF أوWebP أوكود Flutter مخصص. قد تكون أدوات جيدة، لكن التحويل تكلفة خاطئة عندما يكون SVG هو المصدر الأصلي بالفعل.",
    engineTitle: "DOM-preserving engine واحد لـSVG الثابت والمتحرك", engineBody: "يحلل الحزمة document model وCSS وtiming وfilters وtext وحالة التفاعل ثم يرسم داخل Flutter. تعمل ملفات SVGator المدفوعة بـJavaScript عبر QuickJS مدمج؛ ولا تدفع ملفات SVG بلا scripts تكلفة تشغيل JavaScript.",
    coverageTitle: "ما يغطيه الـruntime", coverage: ["Static geometry وgradients وpatterns وclipping وmasks", "حركة SMIL وCSS @keyframes", "Path morphing وmotion paths والتحكم بالتشغيل", "جميع SVG filter primitives السبعة عشر", "Rich text وtextPath وbidi/RTL وaccessibility metadata", "Inline JavaScript وSVGator exports", "ترحيل static API متوافق مع flutter_svg", "Android وiOS وmacOS وWindows وLinux"],
    migrationTitle: "مسار ترحيل عملي", migrationBody: "يمكن غالباً نقل استخدام SvgPicture الثابت بتغيير import فقط. يكتشف FSvgPicture علامات الحركة تلقائياً، ويضيف AnimatedSvgController الإيقاف والبحث والسرعة والاتجاه والتحكم في SVG views.",
    demoTitle: "ملف SVG واحد. حركة أصلية في المتصفح هنا، ورسم Flutter أصلي في الحزمة.", demoBody: "تعرض هذه الصفحة ملف SVG المتحرك الخاص بالمشروع في المتصفح. داخل Flutter يرسم full_svg_flutter الصيغة نفسها من دون WebView أوتحويل.",
    relatedTitle: "حزمة مرتبطة: woff2", relatedBody: "كشف بناء SVG runtime جاد حالة حافة أخرى: الخطوط المضمنة بصيغة WOFF أوWOFF2. أصدر دينيس pure-Dart decoder مبكراً وFontLoader wrapper لتسجيل تلك الخطوط من دون native plugin خاص بالتطبيق.",
    writingTitle: "كتابة تقنية", articleTitle: "المشكلة: دعم SVG في Flutter ثابت غالباً", articleDescription: "شرح عملي لفجوة العرض والحلول الشائعة والتحكم بالتشغيل ومفاضلات الأداء ومتى يكون إبقاء SVG بصيغته هو الخيار الصحيح.",
  },
  services: {
    title: "Senior product engineering بحجم المشكلة.", intro: "للشركات التي تحتاج إلى إطلاق منتج، أوجعل المنصة المحمولة أكثر أماناً للتغيير، أومنح الفريق قيادة تقنية وتسليمية أوضح.", labels: { signal: "متى يفيد", action: "ما الذي يفعله دينيس", format: "صيغة التعاون" },
    items: [
      { title: "تسليم وإنقاذ منتجات Mobile", signal: "خارطة الطريق متأخرة، أوالمسؤولية مجزأة، أوللإصدار الحرج مجهولات كثيرة.", action: "يوضح القيود والاعتماديات والمراحل، ويتولى التصعيد التقني، ويؤسس نموذج تسليم جاهزاً للإنتاج.", format: "تقييم للتسليم يتبعه interim leadership عملي أوبرنامج تعافٍ مركز." },
      { title: "Flutter architecture والتحديث", signal: "يصعب تغيير التطبيق، أوتكسر الترقيات التسليم، أوتتباعد نسخ المنتجات.", action: "يراجع الحدود وإدارة الحالة والاعتماديات والتكامل الأصلي والاختبارات ومخاطر الترحيل، ثم يرتب التحديث حول التسليم النشط.", format: "مراجعة معمارية وخطة بالأولويات وقيادة تنفيذ اختيارية." },
      { title: "Native integration وهندسة الإصدارات", signal: "تمنع signing أوstores أوSDKs أوdeep links أوnotifications أوWebViews أوplatform channels إصداراً موثوقاً.", action: "يتتبع حد المنصة، ويصلح مشكلات التكامل ودورة الحياة، ويقوي مسار الإصدار، ويوثق المسؤولية التشغيلية.", format: "تعاون مركز حول مشكلة تكامل أوإصدار محددة." },
      { title: "Mobile CI/CD والاستعداد للإنتاج", signal: "تُعاد pipelines لكل تطبيق، أوتعتمد الإصدارات على معرفة يدوية، أوالحوادث بلا مسؤول واضح.", action: "يوحّد pipelines وsigning وenvironment flow وrelease gates والفحوص والمراقبة ومتابعة الحوادث من دون تعقيد زائد.", format: "تدقيق مع sprint للتنفيذ أوتمكين منصة عبر عدة فرق." },
      { title: "Fractional mobile technical leadership", signal: "تحتاج الشركة إلى اتجاه senior في Mobile قبل توظيف قائد بدوام كامل أوبدلاً منه.", action: "يمتلك قرارات البنية والتخطيط التقني ودعم التوظيف وتدريب Team Leads ومخاطر التسليم، مع البقاء متاحاً للتصعيد العملي.", format: "تكليف دوري بدوام جزئي مع نتائج وحقوق قرار صريحة." },
      { title: "تقييم Engineering delivery", signal: "تحتاج القيادة إلى رؤية مستقلة لسبب عدم قابلية تسليم Mobile للتنبؤ.", action: "يفحص شكل roadmap وواجهات الفرق والمخاطر التقنية وحوكمة الإصدار وإشارات الجودة والمسؤولية، ثم يقدم خطة عمل قابلة للدفاع.", format: "تشخيص قصير بمقابلات ومراجعة مواد وقراءة تنفيذية وتقنية." },
    ], boundaryTitle: "تبقى النصيحة متناسبة مع المنتج.", boundaryBody: "التدقيق ليس ذريعة لإعادة الكتابة. تميّز التوصيات بين مخاطر الإنتاج العاجلة وأعمال الصيانة، وتشرح المفاضلات، وتحدد ما ينبغي ألا يتغير.",
  },
  experience: {
    title: "نطاق أكبر من دون ترك الهندسة.", intro: "مسار مهني من تسليم منتجات Web إلى هندسة Flutter المتقدمة وملكية المنصة ومسؤولية Team Lead وقيادة عدة فرق Mobile.",
    roles: [
      { period: "يناير 2026 — يوليو 2026", company: "BrainRocket · ليماسول، قبرص", title: "Engineering Manager, Mobile", summary: "قاد ثلاثة فرق متزامنة و15 مهندساً في أسواق iGaming منظمة، وكان Team Lead اثنان من التقارير المباشرة.", evidence: "ثلاثة إطلاقات سوقية في الموعد؛ منتج greenfield إلى الإنتاج في نحو خمسة أشهر؛ core مشترك لعشرة تطبيقات؛ مسؤولية إصدار وحوادث على مستوى المحفظة." },
      { period: "ديسمبر 2024 — ديسمبر 2025", company: "BrainRocket · ليماسول، قبرص", title: "Flutter Team Lead", summary: "جمع قيادة الفريق مع modular architecture ومراجعة الكود والتصعيد الأصلي وملكية الإصدارات المنظمة.", evidence: "Swiper Ontario وإصدارات أخرى؛ Clean Architecture مع BLoC/Riverpod؛ Kotlin/Swift platform channels؛ تعافٍ بعد خروج فريق خارجي." },
      { period: "يوليو 2023 — ديسمبر 2024", company: "CFP Technology (CFPS) · عن بُعد", title: "Senior Flutter Developer", summary: "بنى منصة Flutter عملياتية محمية بـVPN في الإنتاج لمسارات fintech وcompliance.", evidence: "أكثر من 100 شاشة في 18 شهراً؛ forms وtables وpermissions وaccess control وrealtime components قابلة لإعادة الاستخدام." },
      { period: "يناير 2022 — يوليو 2023", company: "Esh Derevenskoye · عن بُعد", title: "Senior Flutter Developer", summary: "بنى marketplace وrecurring-order journeys لمنتج توصيل أغذية زراعية متميزة.", evidence: "صمم geocoding مخصصاً بـOpenStreetMap ومطابقة على مستوى المنزل لمنتج يخدم 150,000 مستخدم مسجل." },
      { period: "يناير 2021 — يناير 2022", company: "Rosselkhozbank · موسكو", title: "Flutter Developer", summary: "طوّر marketplace وB2B وP2P ومسارات خدمات مالية لمنتجات زراعية.", evidence: "أدخل CI/CD وDocker Compose environments واختبارات golden وwidget وintegration." },
      { period: "2015 — 2020", company: "نوفوروسيسك", title: "Web engineering وقيادة استوديو وبدايات Flutter", summary: "أسس استوديو صغيراً وسلّم أكثر من 100 مشروع Web ثم قاد تنفيذ AngularDart/Flutter لمنتج Edakratia.", evidence: "استوديو من شخصين إلى أربعة؛ أنظمة دفع وlead generation؛ منتج توصيل طعام بأكثر من 10,000 مستخدم مسجل في عامه الأول." },
    ], educationTitle: "التعليم", educationBody: "42 Paris، برنامج هندسة البرمجيات (2022–الآن، دوام جزئي)؛ School 21 (2020–2022، انتقال إلى 42 Paris)؛ Novorossiysk College of Construction and Economics، Applied Informatics / Software Engineering Technician ‏(2015–2019).",
    languagesTitle: "اللغات", languagesBody: "الروسية — لغة أم. الإنجليزية — B2+، تُستخدم يومياً في التواصل مع stakeholders والوثائق التقنية والمقابلات والتسليم متعدد الوظائف. اللاتفية — A2.",
  },
  about: {
    title: "مدير ما زال يريد فهم نمط الفشل.", intro: "دينيس مدير هندسة ومهندس عملي بخبرة تزيد على 11 عاماً في هندسة البرمجيات وأكثر من 6 أعوام في Flutter.",
    paragraphs: ["بدأت مسيرته بمنتجات Web واستوديو تسليم صغير، ثم انتقلت عبر banking وmarketplaces وfintech operations وأدوار Flutter متقدمة، قبل أن تتسع إلى مسؤولية Team Lead ومدير هندسة لعدة فرق.", "الخيط المشترك هو ownership عبر الحدود: قيود المنتج وبنية التطبيق وتكامل Android/iOS وCI/CD وإصدارات المتاجر والمراقبة وتصحيح الإنتاج ونظام الفريق اللازم لعمل هذه الأجزاء معاً.", "لم تستبدل القيادة الهندسة. يكون دينيس أكثر فائدة عندما يحتاج الفريق إلى شخص يتخذ قرار محفظة، ويدرّب Team Lead، ويراجع البنية، وينضم إلى التصعيد التقني عندما يكون الإصدار في خطر."],
    usefulTitle: "مشكلات تستحق النقاش", usefulItems: ["منتج Mobile يحتاج إلى مسار موثوق من roadmap إلى الإنتاج", "منصة Flutter تراكم فيها divergence أومخاطر ترقية", "Native SDK أوsigning أوWebView أوrelease tooling يمنع التسليم", "عدة فرق تحتاج إلى operating model واحد من دون فقدان الاستقلالية", "شركة تحتاج إلى fractional mobile leadership أوتقييم تقني مستقل", "Flutter pipeline كثيف SVG يحتاج إلى أكثر من static rendering"],
    nowTitle: "الموقع والتوافر", nowBody: "مقيم في تبليسي، جورجيا. متاح للعمل عن بُعد والانتقال إلى أوروبا. تشمل المحادثات المناسبة Engineering Manager وMobile Engineering Manager وMobile Tech Lead وLead Flutter Engineer والاستشارات المعمارية وتعاونات التسليم المركزة.",
  },
  contact: {
    title: "أحضر مشكلة المنتج الحقيقية.", intro: "إصدار لا يستقر، أوبنية تبطئ كل تغيير، أوفريق يحتاج إلى مسؤولية أوضح، أومنتج يحتاج إلى مسار موثوق نحو الإنتاج.", directTitle: "تواصل مباشر", response: "البريد الإلكتروني هو المفضل. يتوفر أيضاً LinkedIn وGitHub وTelegram.",
    formTitle: "حضّر طلب مشروع", formIntro: "يتحقق النموذج من الأساسيات ثم يفتح مسودة منظمة في تطبيق بريدك. لا يُرفع أويتتبع أي شيء.",
    name: "الاسم", email: "البريد الإلكتروني", company: "الشركة", need: "بماذا تحتاج إلى المساعدة؟", budget: "نطاق الميزانية", timeline: "الجدول الزمني", optional: "اختياري", send: "تحضير البريد",
    prepared: "مسودة بريدك جاهزة. إن لم تُفتح، استخدم عنوان البريد المباشر في هذه الصفحة.", privacy: "خصوصية من أساس التصميم: لا يخزن الموقع بيانات النموذج ولا يرسلها. الإرسال يفتح تطبيق بريدك فقط.",
    errors: { name: "يرجى إدخال اسمك.", email: "أدخل عنوان بريد إلكتروني صالحاً.", need: "أضف وصفاً قصيراً للمشكلة." },
    budgetOptions: ["غير محدد", "أقل من €10k", "€10k–€25k", "€25k–€50k", "+€50k"], timelineOptions: ["غير محدد", "عاجل / الإصدار الحالي", "خلال شهر", "1–3 أشهر", "أكثر من 3 أشهر"],
  },
};
