import type { SiteCopy } from "./types";

export const de: SiteCopy = {
  localeName: "Deutsch",
  seo: {
    home: { title: "Engineering Manager & Mobile Engineer", description: "Denis Nadey führt Mobile-Teams, entwickelt Flutter-Plattformen und bringt komplexe Produkte zuverlässig in Produktion." },
    work: { title: "Mobile-Engineering-Projekte", description: "Ausgewählte Arbeiten zu Mobile Delivery, Plattformmodernisierung, Fintech und Geodaten." },
    "open-source": { title: "Open Source: full_svg_flutter", description: "Die technische Geschichte hinter full_svg_flutter, einer eigenständigen SVG-Runtime für Flutter." },
    services: { title: "Flutter- & Mobile-Engineering-Beratung", description: "Produktdelivery, Flutter-Architektur, CI/CD, Release Engineering, Audits und technische Führung." },
    experience: { title: "Erfahrung in Engineering Leadership", description: "Vom hands-on Software Engineering zur Führung mehrerer Mobile-Teams." },
    about: { title: "Über Denis Nadey", description: "Engineering Manager und hands-on Mobile Engineer für Architektur, Delivery und Produktion." },
    contact: { title: "Denis Nadey kontaktieren", description: "Mobile-Produkte, Flutter-Architektur, Delivery-Probleme, Beratung oder Führungsrollen besprechen." },
  },
  nav: { home: "Start", work: "Projekte", "open-source": "Open Source", services: "Leistungen", experience: "Erfahrung", about: "Über mich", contact: "Kontakt" },
  common: { role: "Engineering Manager & Hands-on Mobile Engineer", location: "Tiflis, Georgien", availability: "Europa-Umzug / remote", menu: "Menü", language: "Sprache", close: "Schließen", skip: "Zum Inhalt", selectedEvidence: "Ausgewählte Fakten · aktueller Lebenslauf", discuss: "Projekt besprechen", exploreWork: "Projekte ansehen", downloadCv: "CV herunterladen", viewOpenSource: "Open Source ansehen", viewServices: "Leistungen ansehen", readArticle: "Technischen Beitrag lesen", visitGithub: "Auf GitHub ansehen", visitPub: "Auf pub.dev ansehen", finalTitle: "Muss ein Mobile-Produkt ausgeliefert, modernisiert oder stabilisiert werden?", finalBody: "Beschreiben Sie das Produktziel, wo die Delivery stockt und wie ein gutes Ergebnis aussieht.", contactDenis: "Denis kontaktieren", external: "öffnet in neuem Tab", current: "Aktuelle Seite" },
  home: {
    titleLead: "Ich baue Mobile-Produkte—", titleEmphasis: "und die Engineering-Systeme dahinter.", intro: "Engineering Leadership, Flutter-Architektur, Delivery über mehrere Teams, CI/CD und Produktionsverantwortung—nah am Code.",
    proof: [{ value: "3", label: "parallele Produktteams" }, { value: "15", label: "geführte Engineers" }, { value: "80+", label: "Produktions-Releases" }, { value: "10", label: "Apps auf gemeinsamem Flutter-Core" }, { value: "5 Mon.", label: "von Greenfield bis Produktion" }],
    mandateLabel: "Der Auftrag", mandateTitle: "Technische Tiefe. Organisatorische Hebelwirkung. Klare Verantwortung.", mandateBody: "Denis wechselte in die Führung, ohne Architektur, Code Review, Release Governance und Produktionseskalationen abzugeben. So verbindet er Roadmap, Fehleranalyse und Release-Entscheidung.",
    workLabel: "Ausgewählte Projekte", workTitle: "Komplexe Produkte lieferbar machen.", workIntro: "Entscheidend ist nicht eine Logo-Wand, sondern das System hinter dem Launch: Ownership, Architektur, Release-Kontrollen und angemessene Vereinfachung.",
    servicesLabel: "Zusammenarbeit", servicesTitle: "Senior Mobile Ownership dort einsetzen, wo es das Ergebnis verändert.", servicesIntro: "Für Produkte, die gebaut, gerettet, modernisiert, geprüft oder produktionsreif gemacht werden müssen—und für Teams, die technische Führung mit hands-on Tiefe brauchen.",
    openLabel: "Open-Source-Engineering", openTitle: "SVG soll SVG bleiben.", openIntro: "full_svg_flutter rendert statisches und animiertes SVG in Flutter: SMIL, CSS Keyframes, Path Morphing, Filter, Masken, Text, SVGator-JavaScript und Playback-Steuerung—ohne Formatkonvertierung.",
    careerLabel: "Entwicklung", careerTitle: "Von Umsetzung zu Portfolio-Verantwortung.", careerIntro: "Mehr als elf Jahre in Web, Fintech, Marketplaces, Mobile-Plattformen, regulierten Produkten und Engineering Leadership—mit wachsendem Umfang und technischer Nähe.",
    principlesLabel: "Arbeitsweise", principlesTitle: "Rahmenbedingungen sichtbar machen. Verantwortung klären.", principles: ["Mit der geschäftlichen Einschränkung beginnen, nicht mit dem Framework.", "Architektur an Produkt und Team ausrichten.", "Delivery- und Release-Risiken früh sichtbar machen.", "Wiederkehrende Release-Arbeit automatisieren.", "Trade-offs entscheidungsfähig erklären.", "Die Plattform besser betreibbar hinterlassen."],
  },
  work: {
    title: "Arbeit, die Architektur mit Produktion verbindet.", intro: "Ausgewählte Programme, bei denen Denis Verantwortung für Delivery, Plattformqualität oder einen schwierigen technischen Teil trug. Teamergebnisse bleiben Teamergebnisse.", labels: { context: "Kontext", responsibility: "Verantwortung", approach: "Vorgehen", outcome: "Ergebnis", stack: "Technologie" }, nda: "Private Architektur, Zugangsdaten, unveröffentlichte Details und interne Geschäftszahlen bleiben bewusst außen vor.",
    cases: [
      { label: "01 · Multi-Market-Delivery", title: "Drei regulierte Launches über drei parallele Roadmaps", summary: "Portfolio-Führung für Zinx Romania, Betoro Denmark und YoYo Sweden; YoYo erreichte Produktion in rund fünf Monaten.", context: "Drei Mobile-Teams lieferten für verschiedene regulierte Märkte bei wechselnden Prioritäten, Abhängigkeiten und Compliance-Vorgaben.", responsibility: "Führung von 15 Engineers und zwei Team Leads; Abstimmung von Product, Design, QA, Backend, Payments und Compliance.", approach: "Einheitliches Modell für Schätzung, Kapazität, Abhängigkeiten, Meilensteine und Release Gates; technische Eskalation für Stores, Signing, SDKs und Incidents.", outcome: "Alle drei Produkte erreichten ihre geplanten Go-live-Fenster; YoYo kam in etwa fünf Monaten von der ersten Umsetzung in Produktion.", stack: "Flutter, Dart, Kotlin, Swift, REST/WebSockets, Firebase, GitLab CI/CD, Codemagic, Fastlane, Sentry/Crashlytics" },
      { label: "02 · Plattformmodernisierung", title: "Gemeinsamer Flutter-Core und Release-System für zehn Apps", summary: "Modernisierung einer Multi-Brand-Plattform bei laufender Auslieferung.", context: "Zehn Apps teilten Core und markenspezifische Konfiguration; Versionsdrift und wiederholtes Release-Setup erhöhten Risiko und Aufwand.", responsibility: "Leitung der Migration von Flutter 3.19 auf 3.38.1 sowie Standardisierung wiederverwendbarer GitLab-CI/CD- und Codemagic-Workflows.", approach: "Gemeinsame Konfiguration, Release-Checklisten, Reviews, Tests, Observability und Incident Follow-up.", outcome: "Weniger Plattformdrift und Setup-Arbeit, klareres Release Ownership und ein konsistenter Produktionsstandard.", stack: "Flutter 3.19-3.38.1, GitLab CI/CD, Codemagic, Fastlane, Tests, Sentry, Crashlytics" },
      { label: "03 · Fintech Operations", title: "Eine Operations-Plattform mit über 100 Screens von Grund auf", summary: "Flutter-Engineering für KYC, AML, Karten, IBAN, Transaktionen, Berechtigungen und Support.", context: "Interne Finanzprozesse brauchten eine dichte, sichere Oberfläche mit vielen Zuständen, Zugriffskontrollen und Echtzeitdaten.", responsibility: "Laut aktuellem CV alleiniger Flutter-Entwickler dieser Plattform innerhalb einer größeren Engineering-Organisation.", approach: "Wiederverwendbare Tabellen, Formulare, Berechtigungen, Zugriffskontrolle und Echtzeit-Komponenten mit modularer Architektur.", outcome: "Über 100 produktive Screens in 18 Monaten und ein gemeinsames Komponentenmodell für mehrere Operations-Domänen.", stack: "Flutter Web/Desktop, Dart, Clean Architecture, BLoC, get_it, REST, WebSockets, TDD, Unit- und Golden-Tests" },
      { label: "04 · Geospatial Commerce", title: "Hausgenaue Zustellung ohne kostenpflichtigen Geocoder", summary: "OpenStreetMap-basierte Adresspipeline für einen Marketplace mit 150.000 registrierten Kunden.", context: "Unterschiedliche Adressformate mussten ohne externen Bezahl-Geocoder bis zur Hausebene normalisiert werden.", responsibility: "Persönliche Konzeption und Umsetzung von Geocoding, Normalisierung und Matching neben den Commerce-Flows.", approach: "Verknüpfung von OpenStreetMap-Daten mit produktspezifischen Regeln und Integration in Kunden- und Betriebsabläufe.", outcome: "Bessere Adressgenauigkeit und betriebliche Zuverlässigkeit für das Produkt.", stack: "Flutter, Dart, OpenStreetMap, Firebase, REST, Clean Architecture, TDD, Android/iOS" },
    ],
  },
  openSource: {
    title: "Browser-Engine-Denken für Flutter-SVG.", intro: "Denis entwickelt full_svg_flutter, eine eigenständige Runtime für Teams, die vorhandene SVG-Assets als SVG in Flutter behalten müssen.", versionLabel: "Öffentlicher Stand · 17. Aug. 2026", proof: [{ value: "1.4.2", label: "aktuelle Version" }, { value: "140", label: "pub points" }, { value: "12", label: "öffentliche Versionen" }, { value: "MIT", label: "Lizenz" }], problemTitle: "Im Browser funktioniert das Asset. In Flutter verschwindet die Animation.", problemBody: "Lottie, Rive, GIF, WebP oder eigene Animationen sind gute Werkzeuge, aber Konvertierung ist unnötig, wenn SVG bereits die Quelle ist.", engineTitle: "Eine DOM-erhaltende Engine für statisches und animiertes SVG", engineBody: "Das Paket verarbeitet Dokumentmodell, CSS, Timing, Filter, Text und Interaktion und zeichnet in Flutter. SVGator-JavaScript läuft in einer gebündelten QuickJS-Engine; SVG ohne Skripte startet kein JavaScript.", coverageTitle: "Abdeckung", coverage: ["Geometrie, Verläufe, Patterns, Clipping und Masken", "SMIL und CSS @keyframes", "Path Morphing, Motion Paths und Playback", "Alle 17 SVG-Filterprimitive", "Rich Text, textPath, bidi/RTL und Accessibility", "Inline JavaScript und SVGator", "flutter_svg-kompatible Migration", "Android, iOS, macOS, Windows und Linux"], migrationTitle: "Praktische Migration", migrationBody: "Bestehendes SvgPicture kann oft mit einem Importwechsel bleiben. FSvgPicture erkennt Animation, AnimatedSvgController steuert Pause, Seek, Geschwindigkeit, Richtung und SVG Views.", demoTitle: "Eine SVG-Datei. Hier Browser-Animation, im Paket natives Flutter-Rendering.", demoBody: "Diese Seite zeigt ein eigenes animiertes Projekt-Asset im Browser. In Flutter rendert full_svg_flutter dieselbe Quelldatei ohne WebView oder Konvertierung.", relatedTitle: "Verwandtes Paket: woff2", relatedBody: "Für in SVG eingebettete WOFF/WOFF2-Schriften veröffentlichte Denis einen frühen Pure-Dart-Decoder mit FontLoader-Wrapper ohne app-spezifischen nativen Plugin-Code.", writingTitle: "Technische Beiträge", articleTitle: "Das Problem: Flutter-SVG-Unterstützung ist meist statisch", articleDescription: "Rendering-Lücke, Workarounds, Playback, Performance-Trade-offs und der richtige Einsatz von SVG als Quelle.",
  },
  services: {
    title: "Senior Mobile Ownership, passend zum Problem.", intro: "Für Unternehmen, die ein Produkt ausliefern, ihre Mobile-Plattform veränderbar machen oder ihrem Team klare technische Führung geben müssen.", labels: { signal: "Wann es hilft", action: "Was Denis macht", format: "Typisches Format" },
    items: [
      { title: "Mobile Product Delivery & Rescue", signal: "Roadmap rutscht, Ownership ist unklar oder ein kritischer Release hat zu viele Unbekannte.", action: "Rahmen, Abhängigkeiten und Meilensteine klären; technische Eskalation und Produktionspfad übernehmen.", format: "Assessment plus Interim-Führung oder fokussiertes Recovery-Programm." },
      { title: "Flutter-Architektur & Modernisierung", signal: "Änderungen sind langsam, Upgrades brechen Delivery oder Produktvarianten driften.", action: "Architektur, State, Abhängigkeiten, Native Integration, Tests und Migration prüfen und priorisieren.", format: "Architektur-Review, Plan und optional Umsetzungsführung." },
      { title: "Native Integration & Release Engineering", signal: "Signing, Stores, SDKs, Deep Links, Notifications, WebViews oder Platform Channels blockieren Releases.", action: "Plattformgrenze analysieren, Integration stabilisieren und operatives Ownership dokumentieren.", format: "Fokussierter technischer Einsatz für Integration oder Release." },
      { title: "Mobile CI/CD & Produktionsreife", signal: "Pipelines werden pro App neu gebaut, Releases hängen an Einzelwissen oder Incidents haben keine Besitzer.", action: "Pipelines, Signing, Environments, Gates, Checks und Observability pragmatisch standardisieren.", format: "Audit plus Implementierungs-Sprint oder Enablement mehrerer Teams." },
      { title: "Fractional Mobile Technical Leadership", signal: "Senior Mobile Direction wird vor oder statt einer Vollzeiteinstellung gebraucht.", action: "Architektur, Planung, Hiring, Team-Lead-Coaching und Delivery-Risiko mit hands-on Eskalation führen.", format: "Wiederkehrendes Teilzeitmandat mit klaren Entscheidungsrechten." },
      { title: "Engineering Delivery Assessment", signal: "Leadership braucht eine unabhängige Erklärung für unberechenbare Delivery.", action: "Roadmap, Team-Schnittstellen, technische Risiken, Release Governance, Qualität und Ownership prüfen.", format: "Kurze Diagnose mit Interviews, Artefakt-Review und Management-/Technik-Readout." },
    ], boundaryTitle: "Empfehlungen bleiben proportional.", boundaryBody: "Ein Audit ist kein Vorwand für einen Rewrite. Es trennt akutes Produktionsrisiko von Wartbarkeit und sagt auch, was unverändert bleiben sollte.",
  },
  experience: {
    title: "Mehr Verantwortung, ohne Engineering zu verlassen.", intro: "Vom Web Engineering über Senior Flutter und Plattform-Ownership zu Team Lead und Multi-Team-Führung.",
    roles: [
      { period: "Jan. 2026 — Juli 2026", company: "BrainRocket · Limassol, Zypern", title: "Engineering Manager, Mobile", summary: "Führung von drei Teams und 15 Engineers; zwei Team Leads als Direct Reports.", evidence: "Drei pünktliche Marktstarts, Greenfield in rund fünf Monaten, gemeinsamer Core für zehn Apps und Portfolio-Release-Verantwortung." },
      { period: "Dez. 2024 — Dez. 2025", company: "BrainRocket · Limassol, Zypern", title: "Flutter Team Lead", summary: "Teamführung kombiniert mit Architektur, Code Review, Native-Eskalation und regulierten Releases.", evidence: "Swiper Ontario, Clean Architecture mit BLoC/Riverpod, Kotlin/Swift Platform Channels und Recovery nach Vendor-Ausstieg." },
      { period: "Juli 2023 — Dez. 2024", company: "CFP Technology (CFPS) · Remote", title: "Senior Flutter Developer", summary: "Aufbau einer VPN-gesicherten Operations-Plattform für Fintech und Compliance.", evidence: "100+ Screens in 18 Monaten; wiederverwendbare Formulare, Tabellen, Berechtigungen und Echtzeit-Komponenten." },
      { period: "Jan. 2022 — Juli 2023", company: "Esh Derevenskoye · Remote", title: "Senior Flutter Developer", summary: "Marketplace- und Abo-Flows für Premium-Lebensmittellieferung.", evidence: "OpenStreetMap-Geocoding und Haus-Matching für ein Produkt mit 150.000 registrierten Kunden." },
      { period: "Jan. 2021 — Jan. 2022", company: "Rosselkhozbank · Moskau", title: "Flutter Developer", summary: "Marketplace-, B2B-, P2P- und Finanzflüsse für Agrarprodukte.", evidence: "CI/CD, Docker Compose sowie Golden-, Widget- und Integrationstests eingeführt." },
      { period: "2015 — 2020", company: "Noworossijsk", title: "Web Engineering, Studioführung & frühes Flutter", summary: "Kleines Studio gegründet, 100+ Webprojekte geliefert und später AngularDart/Flutter für Edakratia geführt.", evidence: "2–4 Personen; Payment- und Lead-Systeme; Food-Delivery mit 10.000+ Nutzern im ersten Jahr." },
    ], educationTitle: "Ausbildung", educationBody: "42 Paris, Software Engineering Program (seit 2022, Teilzeit); School 21 (2020–2022, Wechsel zu 42 Paris); College für Bauwesen und Wirtschaft Noworossijsk, Angewandte Informatik (2015–2019).", languagesTitle: "Sprachen", languagesBody: "Russisch — Muttersprache. Englisch — B2+, täglich für Stakeholder, Dokumentation, Interviews und Delivery. Lettisch — A2.",
  },
  about: {
    title: "Ein Manager, der den Fehlerzustand noch selbst verstehen will.", intro: "Denis ist Engineering Manager und hands-on Mobile Engineer mit 11+ Jahren Software- und 6+ Jahren Flutter-Erfahrung.", paragraphs: ["Sein Weg begann mit Webprodukten und einem kleinen Studio, führte durch Banking, Marketplaces, Fintech Operations und Senior-Flutter-Rollen und wuchs zu Team Lead und Multi-Team-Management.", "Der rote Faden ist Ownership über Grenzen hinweg: Produktbedingungen, Architektur, native Android/iOS-Integration, CI/CD, Store Releases, Observability, Debugging und Teamstruktur.", "Leadership ersetzte Engineering nicht. Denis ist dort besonders wirksam, wo Portfolio-Entscheidung, Team-Lead-Coaching, Architektur-Review und technische Release-Eskalation zusammenkommen."], usefulTitle: "Sinnvolle Gespräche", usefulItems: ["Ein Mobile-Produkt braucht einen glaubwürdigen Weg von Roadmap zu Produktion", "Eine Flutter-Plattform hat Drift oder Upgrade-Risiko", "Native SDKs, Signing, WebViews oder Release Tooling blockieren Delivery", "Mehrere Teams brauchen ein gemeinsames Modell ohne Autonomieverlust", "Fractional Leadership oder unabhängiges Assessment wird gebraucht", "Eine SVG-intensive Flutter-Pipeline braucht mehr als statisches Rendering"], nowTitle: "Standort & Verfügbarkeit", nowBody: "Wohnhaft in Tiflis, Georgien. Offen für Remote-Arbeit und Umzug nach Europa. Passend sind Engineering Manager, Mobile Engineering Manager, Mobile Tech Lead, Lead Flutter Engineer sowie Architektur- und Delivery-Beratung.",
  },
  contact: {
    title: "Bringen Sie das echte Mobile-Problem mit.", intro: "Ein instabiler Release, eine bremsende Architektur, unklare Teamverantwortung oder ein Produkt ohne glaubwürdigen Produktionspfad.", directTitle: "Direkter Kontakt", response: "E-Mail ist bevorzugt. LinkedIn, GitHub und Telegram sind ebenfalls verfügbar.", formTitle: "Projektanfrage vorbereiten", formIntro: "Das Formular prüft die Angaben und öffnet einen strukturierten Entwurf in Ihrem E-Mail-Programm. Nichts wird hochgeladen oder getrackt.", name: "Name", email: "E-Mail", company: "Unternehmen", need: "Wobei brauchen Sie Hilfe?", budget: "Budgetrahmen", timeline: "Zeitrahmen", optional: "optional", send: "E-Mail vorbereiten", prepared: "Der Entwurf ist bereit. Falls er nicht geöffnet wurde, nutzen Sie die direkte E-Mail-Adresse.", privacy: "Datenschutzfreundlich: Die Website speichert oder überträgt keine Formulardaten. Absenden öffnet Ihr E-Mail-Programm.", errors: { name: "Bitte Namen eingeben.", email: "Bitte gültige E-Mail eingeben.", need: "Bitte das Problem kurz beschreiben." }, budgetOptions: ["Nicht angegeben", "Unter 10.000 €", "10.000–25.000 €", "25.000–50.000 €", "50.000 €+"], timelineOptions: ["Nicht angegeben", "Dringend / aktueller Release", "Innerhalb eines Monats", "1–3 Monate", "3+ Monate"],
  },
};

