import type { SiteCopy } from "./types";

export const de: SiteCopy = {
  localeName: "Deutsch",
  seo: {
    home: { title: "Engineering Manager · Web, Mobile & AI", description: "Denis Nadey: über 11 Jahre Erfahrung in Web-Produkten, Mobile-Plattformen, Engineering-Führung, Open Source und KI-gestützter Entwicklung." },
    work: { title: "Web, Mobile & Engineering Leadership", description: "Ausgewählte Arbeiten von Denis Nadey: Web-Produkte, Mobile-Plattformen, Fintech, Auslieferungsprozesse und Open Source." },
    "open-source": { title: "Open Source: full_svg_flutter", description: "Die technische Geschichte hinter full_svg_flutter, einer eigenständigen Runtime für statisches und animiertes SVG in Flutter." },
    services: { title: "Flutter-, Web- & KI-Engineering", description: "Senior Product Engineering für Web, Flutter, Architektur, Auslieferungsprozesse und praxistaugliche KI-Workflows." },
    experience: { title: "Erfahrung in Engineering Leadership", description: "Werdegang von Denis Nadey: vom Hands-on-Software-Engineering über Senior-Flutter-Rollen und Team Lead bis zur Führung mehrerer Mobile-Teams." },
    about: { title: "Denis Nadey · Web, Mobile & AI", description: "Engineering Manager und Hands-on-Product-Engineer: Wurzeln im Web, Tiefe im Mobile-Bereich und eine Arbeitsweise, in der KI fest verankert ist." },
    contact: { title: "Denis Nadey kontaktieren", description: "Ein Web- oder Mobile-Produkt, eine Führungsaufgabe im Engineering, einen Auslieferungsprozess oder einen konkreten KI-Workflow mit Denis Nadey besprechen." },
  },
  nav: { home: "Start", work: "Projekte", "open-source": "Open Source", services: "Leistungen", experience: "Erfahrung", about: "Über mich", contact: "Kontakt" },
  common: {
    role: "Engineering Manager · Web, Mobile & AI Product Engineer",
    location: "Tiflis, Georgien",
    availability: "Umzug innerhalb Europas möglich / Remote",
    menu: "Menü",
    language: "Sprache",
    close: "Schließen",
    skip: "Zum Inhalt springen",
    selectedEvidence: "Ausgewählte Fakten · aktueller CV",
    discuss: "Projekt besprechen",
    exploreWork: "Projekte ansehen",
    viewExperience: "Gesamten Werdegang ansehen",
    downloadCv: "CV herunterladen",
    viewOpenSource: "Open Source ansehen",
    viewServices: "Leistungen ansehen",
    readArticle: "Technischen Deep-Dive lesen",
    visitGithub: "Auf GitHub ansehen",
    visitPub: "Auf pub.dev ansehen",
    finalTitle: "Ein digitales Produkt bauen, modernisieren oder wieder in Bewegung bringen?",
    finalBody: "Beschreiben Sie das eigentliche Problem – Web, Mobile, die Auslieferung im Team oder ein KI-Workflow, der produktionsreif werden muss.",
    contactDenis: "Denis kontaktieren",
    external: "öffnet in neuem Tab",
    current: "Aktuelle Seite",
  },
  home: {
    titleLead: "Ich baue digitale Produkte – ",
    titleEmphasis: "von Web und Mobile bis zur KI-gestützten Entwicklung.",
    intro: "Über 11 Jahre in Web, Mobile und Engineering-Führung: 100+ Web-Projekte, Flutter-Plattformen in Produktion, mehrere Teams parallel und KI als ernsthaftes Engineering-Werkzeug – nicht als Schlagwort.",
    proof: [
      { value: "11+", label: "Jahre Software Engineering" },
      { value: "100+", label: "ausgelieferte Web-Produkte" },
      { value: "3", label: "Produktteams parallel" },
      { value: "15", label: "geführte Engineers" },
      { value: "3", label: "öffentliche Runtime-Pakete" },
    ],
    mandateLabel: "Engineering über die gesamte Breite",
    mandateTitle: "Breite im Web. Tiefe im Mobile-Bereich. KI fest im Arbeitsablauf.",
    mandateBody: "Denis hat mit Websites, Shops, Admin-Tools, Rechnern, Payment- und Lead-Systemen angefangen. Später kamen Mobile-Plattformen und die Führung mehrerer Teams dazu. Heute ist KI Teil des Engineering-Zyklus – von Recherche und Prototyp bis zu Implementierung, Tests und Dokumentation –, die Verantwortung für das Ergebnis bleibt beim Menschen.",
    workLabel: "Ausgewählte Projekte",
    workTitle: "Komplexe Produkte, die tatsächlich ausgeliefert werden.",
    workIntro: "Was zählt, ist keine Logo-Wand, sondern das System hinter dem Launch: klare Verantwortung, Architektur, Release-Kontrollen und das Urteilsvermögen, im richtigen Moment zu vereinfachen.",
    servicesLabel: "Zusammenarbeit",
    servicesTitle: "Senior-Verantwortung dort, wo sie das Ergebnis verändert.",
    servicesIntro: "Für Produkte, die gebaut, gerettet, modernisiert, geprüft oder produktionsreif gemacht werden müssen – und für Teams, die technische Führung brauchen, ohne die Hands-on-Tiefe zu verlieren.",
    openLabel: "Open-Source-Engineering",
    openTitle: "SVG soll SVG bleiben.",
    openIntro: "full_svg_flutter ist ein eigenständiger Renderer für statisches und animiertes SVG in Flutter: SMIL, CSS @keyframes, Path Morphing, Filter, Masken, Text, JavaScript-basierte SVGator-Exporte und Playback-Steuerung – ohne das Asset in ein anderes Format zu konvertieren.",
    careerLabel: "Werdegang",
    careerTitle: "Vom Web über Mobile-Plattformen zum Engineering mit KI.",
    careerIntro: "Der Weg ist kumulativ: Breite aus Web-Produkten, Tiefe aus Mobile-Systemen, Engineering-Management und eine moderne, KI-gestützte Arbeitsweise, die schneller macht, ohne Verantwortung abzugeben.",
    principlesLabel: "Arbeitsweise",
    principlesTitle: "Rahmenbedingungen sichtbar machen. Verantwortung klar halten.",
    principles: [
      "Mit der geschäftlichen Einschränkung anfangen, nicht mit dem Framework.",
      "Architektur im Verhältnis zu Produkt und Team dimensionieren.",
      "Auslieferungs- und Release-Risiken früh auf den Tisch bringen.",
      "Wiederkehrende Release-Arbeit automatisieren und den Ausnahmepfad dokumentieren.",
      "Trade-offs in der Sprache erklären, mit der Entscheider arbeiten können.",
      "Die Plattform leichter betreibbar hinterlassen, als sie vorgefunden wurde.",
    ],
  },
  work: {
    title: "Web-Produkte, Mobile-Plattformen und Auslieferungssysteme.",
    intro: "Ausgewählte Programme, in denen Denis für die Auslieferung, die Plattformqualität oder eine schwierige Systemgrenze verantwortlich war. Das Portfolio beginnt im Web Product Engineering und weitet sich auf Mobile-Architektur und die Verantwortung für mehrere Teams aus.",
    labels: { context: "Kontext", responsibility: "Verantwortung", approach: "Vorgehen", outcome: "Ergebnis", stack: "Stack" },
    nda: "Die Fallstudien lassen bewusst private Architektur, Zugangsdaten, unveröffentlichte Produktdetails und interne Geschäftszahlen aus.",
    cases: [
      {
        label: "01 · Delivery in mehreren Märkten",
        title: "Drei regulierte Launches über drei parallele Roadmaps",
        summary: "Portfolio-Führung für Zinx Romania, Betoro Denmark und YoYo Sweden; YoYo war nach rund fünf Monaten in Produktion.",
        context: "Drei Mobile-Teams lieferten gleichzeitig für unterschiedliche regulierte Märkte, während sich Besetzung, Prioritäten, Abhängigkeiten und Compliance-Anforderungen laufend änderten.",
        responsibility: "Führte das Portfolio mit 15 Engineers, coachte zwei Team Leads, trug die Verantwortung für Auslieferung und Teamgesundheit und stimmte Product, Design, QA, Backend, Payments und Compliance aufeinander ab.",
        approach: "Führte ein gemeinsames Betriebsmodell für Schätzung, Kapazität, Abhängigkeiten, Meilensteine und Release-Gates ein. Blieb technisch nah genug dran, um Eskalationen bei Signierung, nativen SDKs, WebView-Bridge, App-Stores und Incidents selbst zu lösen.",
        outcome: "Alle drei Produkte erreichten ihre regulierten Go-live-Fenster termingerecht. YoYo ging in rund fünf Monaten von der ersten Implementierung in Produktion.",
        stack: "Flutter, Dart, Kotlin, Swift, REST/WebSockets, Firebase, GitLab CI/CD, Codemagic, Fastlane, Sentry/Crashlytics",
      },
      {
        label: "02 · Plattformmodernisierung",
        title: "Ein gemeinsamer Flutter-Core und ein Release-System für zehn Apps",
        summary: "Modernisierte die Plattform unter einem Multi-Brand-Portfolio, während die aktiven Produkte weiter ausgeliefert wurden.",
        context: "Zehn Apps teilten sich einen Flutter-Core und markenspezifische Konfigurationen. Auseinanderlaufende Versionen und wiederholtes Release-Setup erhöhten Wartungsaufwand und Produktionsrisiko.",
        responsibility: "Leitete die Migration des gemeinsamen Cores von Flutter 3.19 auf 3.38.1 und standardisierte wiederverwendbare GitLab-CI/CD- und Codemagic-Workflows für alle Produktteams.",
        approach: "Konsolidierte Plattformkonfiguration, Release-Checklisten, Review-Standards, automatisierte Tests, Observability und Incident-Nachbereitung und delegierte das Tagesgeschäft der Teams an die Team Leads.",
        outcome: "Weniger Plattformdrift und Doppelarbeit beim Setup, klarere Release-Verantwortung und ein einheitlicher Produktionsstandard für das gesamte Portfolio.",
        stack: "Flutter 3.19–3.38.1, GitLab CI/CD, Codemagic, Fastlane, automatisierte Tests, Sentry, Crashlytics",
      },
      {
        label: "03 · Fintech-Operations",
        title: "Eine Operations-Plattform mit über 100 Screens, von Grund auf gebaut",
        summary: "Hands-on-Flutter-Engineering für ein VPN-gesichertes Operations-Produkt mit KYC, AML, Karten, IBAN, Transaktionen, Berechtigungen und Support-Workflows.",
        context: "Interne Finanzoperationen brauchten eine dichte, verlässliche Oberfläche mit vielen Geschäftszuständen, Zugriffsregeln, Echtzeit-Updates und compliance-kritischen Abläufen.",
        responsibility: "Einziger Flutter-Entwickler der Plattform innerhalb einer größeren Engineering-Organisation.",
        approach: "Baute wiederverwendbare Tabellen, Formulare, Berechtigungen, Zugriffskontrolle und Echtzeit-Komponenten auf einer modularen Architektur mit testgetriebenem Vorgehen.",
        outcome: "Über 100 produktive Screens in 18 Monaten und ein gemeinsames Komponentenmodell, das eine einheitliche Umsetzung über alle operativen Bereiche hinweg trug.",
        stack: "Flutter Web/Desktop, Dart, Clean Architecture, BLoC, get_it, REST, WebSockets, TDD, Unit- und Golden-Tests",
      },
      {
        label: "04 · Geodaten im Handel",
        title: "Hausgenaue Zustellung ohne kostenpflichtigen Geocoder",
        summary: "Eine eigene Adress-Pipeline auf Basis von OpenStreetMap für einen Marktplatz für Hoflebensmittel mit 150.000 registrierten Kunden.",
        context: "Die Zustellgenauigkeit hing davon ab, uneinheitliche Adressen zu normalisieren und hausgenau zuzuordnen – ohne einen kostenpflichtigen externen Geocoding-Dienst.",
        responsibility: "Entwarf und lieferte die Pipeline für Geocoding, Adressnormalisierung und Matching persönlich, parallel zu Katalog, Warenkorb, Checkout, Lieferung und Abos für Endkunden.",
        approach: "Kombinierte OpenStreetMap-Daten mit produktspezifischer Normalisierung und Geo-Regeln und band das Ergebnis in die operativen Abläufe und die Kundenzustellung ein.",
        outcome: "Genauere Lieferadressen und verlässlichere Abläufe für ein Produkt mit 150.000 registrierten Kunden.",
        stack: "Flutter, Dart, OpenStreetMap, Firebase, REST, Clean Architecture, TDD, native Android/iOS-Integrationen",
      },
    ],
  },
  openSource: {
    title: "Browser-Engine-Denken für SVG in Flutter.",
    intro: "Denis hat full_svg_flutter entwickelt und pflegt es weiter: eine eigenständige Rendering-Runtime für Teams, deren vorhandene SVG-Assets in Flutter SVG bleiben müssen.",
    versionLabel: "Öffentlicher Stand · 17. August 2026",
    proof: [
      { value: "1.4.2", label: "aktuelle Version" },
      { value: "140", label: "pub points" },
      { value: "12", label: "öffentliche Versionen" },
      { value: "MIT", label: "Open-Source-Lizenz" },
    ],
    problemTitle: "Im Browser funktioniert das Asset. In Flutter verschwindet die Animation.",
    problemBody: "Viele Pipelines schließen diese Lücke, indem sie das Asset nach Lottie, Rive, GIF, WebP oder in handgeschriebenen Flutter-Animationscode konvertieren. Das können gute Werkzeuge sein – aber Konvertierung ist der falsche Preis, wenn SVG ohnehin die Quelle der Wahrheit ist.",
    engineTitle: "Eine DOM-erhaltende Engine für statisches und animiertes SVG",
    engineBody: "Das Paket parst Dokumentmodell, CSS, Timing, Filter, Text und Interaktionszustand und zeichnet dann in Flutter. JavaScript-basierte SVGator-Exporte laufen in einer gebündelten QuickJS-Engine; SVGs ohne Skripte zahlen keine JavaScript-Startkosten.",
    coverageTitle: "Was die Runtime abdeckt",
    coverage: [
      "Statische Geometrie, Verläufe, Muster, Clipping und Masken",
      "SMIL- und CSS-@keyframes-Animation",
      "Path Morphing, Motion Paths und Playback-Steuerung",
      "Alle 17 SVG-Filterprimitive",
      "Rich Text, textPath, Bidi/RTL und Accessibility-Metadaten",
      "Inline-JavaScript und SVGator-Exporte",
      "flutter_svg-kompatible Migration des statischen APIs",
      "Android, iOS, macOS, Windows und Linux",
    ],
    migrationTitle: "Ein praktikabler Migrationspfad",
    migrationBody: "Bestehende statische SvgPicture-Aufrufe lassen sich oft mit einem geänderten Import übernehmen. FSvgPicture erkennt Animationsmarker automatisch, und AnimatedSvgController ergänzt Pause, Seek, Geschwindigkeit, Richtung und den Wechsel von SVG-Views, wenn das Produkt sie braucht.",
    demoTitle: "Eine SVG-Datei. Hier nativ im Browser animiert, im Paket nativ in Flutter gerendert.",
    demoBody: "Diese Seite zeigt das animierte SVG-Asset des Projekts im Browser. In einer Flutter-App rendert full_svg_flutter dieselbe Quelldatei direkt in Flutter – ohne WebView und ohne Konvertierung.",
    relatedTitle: "Verwandtes Paket: woff2",
    relatedBody: "Beim Bau einer ernsthaften SVG-Runtime tauchte ein weiterer Grenzfall auf: eingebettete Schriften im WOFF- oder WOFF2-Format. Denis hat einen frühen Pure-Dart-Decoder mit FontLoader-Wrapper veröffentlicht, damit Flutter-Pipelines diese Formate ohne app-spezifischen nativen Plugin-Code registrieren können.",
    writingTitle: "Technische Beiträge",
    articleTitle: "Das Problem: SVG-Unterstützung in Flutter ist meist statisch",
    articleDescription: "Eine praxisnahe Erklärung der Rendering-Lücke, der üblichen Workarounds, der Playback-Steuerung, der Performance-Trade-offs – und wann es richtig ist, SVG als SVG zu belassen.",
  },
  services: {
    title: "Senior Product Engineering für Web, Mobile und KI.",
    intro: "Holen Sie Denis dazu, wenn ein digitales Produkt belastbare Verantwortung über Interface, Architektur, Auslieferung, Produktion und die modernen KI-Workflows braucht, die jede dieser Phasen beschleunigen können.",
    labels: { signal: "Wann es hilft", action: "Was Denis macht", format: "Typischer Einsatz" },
    items: [
      { title: "Mobile-Produkte ausliefern & retten", signal: "Die Roadmap rutscht, die Verantwortung ist zersplittert oder ein kritischer Release hat zu viele Unbekannte.", action: "Klärt Rahmenbedingungen, kartiert Abhängigkeiten, setzt Meilensteine neu, übernimmt die technische Eskalation und etabliert ein produktionsreifes Auslieferungsmodell.", format: "Delivery-Assessment, gefolgt von hands-on Interimsführung oder einem fokussierten Recovery-Programm." },
      { title: "Flutter-Architektur & Modernisierung", signal: "Die App lässt sich schwer ändern, Upgrades brechen immer wieder die Auslieferung oder Marken- und Produktvarianten laufen auseinander.", action: "Prüft Modulgrenzen, State Management, Abhängigkeiten, native Integration, Tests und Migrationsrisiken und plant die Modernisierung so, dass die laufende Auslieferung nicht stillsteht.", format: "Architektur-Review, priorisierter Plan und auf Wunsch Führung der Umsetzung." },
      { title: "Native Integration & Release Engineering", signal: "Signierung, App-Stores, SDKs, Deep Links, Push-Benachrichtigungen, WebViews oder Platform Channels blockieren einen verlässlichen Release.", action: "Analysiert die Plattformgrenze, behebt Integrations- und Lifecycle-Probleme, härtet den Release-Pfad und dokumentiert die operative Verantwortung.", format: "Fokussierter technischer Einsatz rund um ein klar umrissenes Integrations- oder Release-Problem." },
      { title: "Mobile CI/CD & Produktionsreife", signal: "Pipelines werden pro App neu gebaut, Releases hängen an Einzelwissen oder Incidents haben keine klaren Verantwortlichen.", action: "Standardisiert Pipelines, Signierung und Umgebungen, Release-Gates, Checks, Observability und Incident-Nachbereitung – ohne die Plattform zu überbauen.", format: "Audit plus Implementierungssprint oder Plattform-Enablement für mehrere Teams." },
      { title: "Technische Mobile-Führung auf Teilzeitbasis", signal: "Ein Unternehmen braucht erfahrene Mobile-Führung, bevor – oder statt – es eine Vollzeitstelle besetzt.", action: "Übernimmt Architekturentscheidungen, technische Planung, Unterstützung beim Recruiting, Coaching der Team Leads und das Delivery-Risiko und bleibt für Hands-on-Eskalationen erreichbar.", format: "Wiederkehrendes Teilzeitmandat mit klaren Ergebnissen und Entscheidungsrechten." },
      { title: "Engineering-Delivery-Assessment", signal: "Die Führung braucht eine unabhängige Einschätzung, warum sich die Mobile-Auslieferung unberechenbar anfühlt.", action: "Untersucht Roadmap-Zuschnitt, Schnittstellen zwischen Teams, technische Risiken, Release-Governance, Qualitätssignale und Verantwortlichkeiten und liefert einen priorisierten, belastbaren Maßnahmenplan.", format: "Kurze Diagnose mit Interviews, Sichtung der Artefakte und einem Readout für Management und Technik." },
    ],
    boundaryTitle: "Empfehlungen bleiben verhältnismäßig.",
    boundaryBody: "Ein Audit ist kein Vorwand für einen Rewrite. Die Empfehlungen trennen akutes Produktionsrisiko von Wartbarkeitsarbeit, erklären die Trade-offs und benennen auch, was unverändert bleiben sollte.",
  },
  experience: {
    title: "Mehr Verantwortung, ohne das Engineering zu verlassen.",
    intro: "Ein Werdegang von der Web-Produktentwicklung über Senior-Flutter-Engineering, Plattformverantwortung und die Rolle als Team Lead bis zur Führung mehrerer Mobile-Teams.",
    roles: [
      { period: "Jan. 2026 – Juli 2026", company: "BrainRocket · Limassol, Zypern", title: "Engineering Manager, Mobile", summary: "Führte drei parallele Teams mit 15 Engineers in regulierten iGaming-Märkten; zwei Team Leads als Direct Reports.", evidence: "Drei termingerechte Marktstarts; ein Greenfield-Produkt in rund fünf Monaten in Produktion; gemeinsamer Core für zehn Apps; Release- und Incident-Verantwortung auf Portfolioebene." },
      { period: "Dez. 2024 – Dez. 2025", company: "BrainRocket · Limassol, Zypern", title: "Flutter Team Lead", summary: "Verband Teamführung mit modularer Architektur, Code Review, nativer Eskalation und der Verantwortung für regulierte Releases.", evidence: "Swiper Ontario und weitere Releases; Clean Architecture mit BLoC/Riverpod; Platform Channels in Kotlin/Swift; Recovery nach dem Ausstieg eines externen Teams." },
      { period: "Juli 2023 – Dez. 2024", company: "CFP Technology (CFPS) · Remote", title: "Senior Flutter Developer", summary: "Baute eine produktive, VPN-gesicherte Flutter-Operations-Plattform für Fintech- und Compliance-Workflows.", evidence: "100+ Screens in 18 Monaten; wiederverwendbare Formulare, Tabellen, Berechtigungen, Zugriffskontrolle und Echtzeit-Komponenten." },
      { period: "Jan. 2022 – Juli 2023", company: "Esh Derevenskoye · Remote", title: "Senior Flutter Developer", summary: "Entwickelte Marktplatz- und Abo-Bestellstrecken für einen Premium-Lieferdienst für Hoflebensmittel.", evidence: "Entwarf eine eigene Pipeline für OpenStreetMap-Geocoding und hausgenaues Matching für ein Produkt mit 150.000 registrierten Kunden." },
      { period: "Jan. 2021 – Jan. 2022", company: "Rosselkhozbank · Moskau", title: "Flutter Developer", summary: "Entwickelte Marktplatz-, B2B-, P2P- und Finanzdienstleistungs-Flows für Agrarprodukte.", evidence: "Führte CI/CD, Docker-Compose-Umgebungen sowie Golden-, Widget- und Integrationstests ein." },
      { period: "2015 – 2020", company: "Noworossijsk", title: "Web-Engineering, eigenes Studio & erste Flutter-Projekte", summary: "Gründete ein kleines Studio, lieferte über 100 Web-Projekte aus und leitete später die AngularDart/Flutter-Umsetzung für Edakratia.", evidence: "Studio mit zwei bis vier Personen; Payment- und Lead-Generierungssysteme; Essenslieferprodukt mit 10.000+ registrierten Nutzern im ersten Jahr." },
    ],
    educationTitle: "Ausbildung",
    educationBody: "42 Paris, Software Engineering Program (seit 2022, Teilzeit); School 21 (2020–2022, Wechsel zu 42 Paris); College für Bauwesen und Wirtschaft Noworossijsk, Angewandte Informatik / Softwaretechniker (2015–2019).",
    languagesTitle: "Sprachen",
    languagesBody: "Russisch – Muttersprache. Englisch – B2+, täglich im Einsatz für Stakeholder-Kommunikation, technische Dokumentation, Interviews und die Zusammenarbeit über Teamgrenzen hinweg. Lettisch – A2.",
  },
  about: {
    title: "Product Engineer, bevor es um ein einzelnes Framework geht.",
    intro: "Denis ist Engineering Manager und Hands-on-Engineer mit über 11 Jahren Erfahrung in Web-Produkten, Mobile-Plattformen, Open-Source-Runtimes und KI-gestützter Entwicklung.",
    paragraphs: [
      "Die Laufbahn begann im Web: ein kleines Studio, über 100 ausgelieferte Projekte, Shops, Admin-Systeme, Payments, Rechner und Lead-Strecken. Diese Breite hat den Blick fürs Produkt geschärft, lange vor Banking, Marktplätzen, Fintech und Flutter.",
      "Mobile brachte härtere Plattformgrenzen dazu: Kotlin- und Swift-Integration, Signierung, App-Stores, CI/CD, Observability, Incidents in Produktion und eine gemeinsame Architektur über mehrere Apps. Die Führungsrolle weitete diese Verantwortung später auf Team Leads, Roadmaps, Recruiting und drei parallele Teams aus.",
      "KI gehört heute zur Arbeitsweise. Denis nutzt sie, um Recherche zu verdichten, Architekturvarianten zu erkunden, Interfaces zu prototypen, Code zu schreiben und zu reviewen, Tests zu entwerfen und Dokumentation zu erstellen. Der Maßstab bleibt derselbe: Belege, explizite Trade-offs und ein Mensch, der für das verantwortlich ist, was in Produktion geht.",
    ],
    usefulTitle: "Themen, über die sich ein Gespräch lohnt",
    usefulItems: [
      "Ein Mobile-Produkt braucht einen glaubwürdigen Weg von der Roadmap in die Produktion",
      "Eine Flutter-Plattform hat Drift oder Upgrade-Risiken angesammelt",
      "Native SDKs, Signierung, WebViews oder Release-Tooling blockieren die Auslieferung",
      "Mehrere Teams brauchen ein gemeinsames Betriebsmodell, ohne ihre Autonomie zu verlieren",
      "Ein Unternehmen braucht technische Mobile-Führung auf Teilzeitbasis oder eine unabhängige technische Einschätzung",
      "Eine SVG-lastige Flutter-Pipeline braucht mehr als statisches Rendering",
    ],
    nowTitle: "Standort & Verfügbarkeit",
    nowBody: "Lebt in Tiflis, Georgien. Offen für Remote-Arbeit und einen Umzug innerhalb Europas. Passende Rollen und Mandate: Engineering Manager, Mobile Engineering Manager, Mobile Tech Lead, Lead Flutter Engineer, Architekturberatung und fokussierte Delivery-Einsätze.",
  },
  contact: {
    title: "Kommen Sie mit dem echten Problem.",
    intro: "Ein Web-Produkt ohne Weg in die Produktion, ein Mobile-Release, der nicht stabil wird, ein Team mit unklarer Verantwortung oder ein KI-Workflow, der verlässliches Engineering werden muss.",
    directTitle: "Direkter Kontakt",
    response: "E-Mail ist der beste Weg. LinkedIn, GitHub und Telegram funktionieren ebenfalls.",
    formTitle: "Projektanfrage vorbereiten",
    formIntro: "Das Formular prüft das Wesentliche und öffnet dann einen strukturierten Entwurf in Ihrem E-Mail-Programm. Nichts wird hochgeladen oder getrackt.",
    name: "Name",
    email: "E-Mail",
    company: "Unternehmen",
    need: "Wobei brauchen Sie Unterstützung?",
    budget: "Budgetrahmen",
    timeline: "Zeitrahmen",
    optional: "optional",
    send: "E-Mail vorbereiten",
    prepared: "Ihr E-Mail-Entwurf ist fertig. Falls er sich nicht geöffnet hat, nutzen Sie die direkte E-Mail-Adresse auf dieser Seite.",
    privacy: "Datenschutz von Anfang an: Diese Website speichert und überträgt keine Formulardaten. Beim Absenden öffnet sich Ihr eigenes E-Mail-Programm.",
    errors: { name: "Bitte geben Sie Ihren Namen ein.", email: "Bitte geben Sie eine gültige E-Mail-Adresse ein.", need: "Beschreiben Sie das Problem kurz." },
    budgetOptions: ["Nicht angegeben", "Unter 10.000 €", "10.000–25.000 €", "25.000–50.000 €", "Über 50.000 €"],
    timelineOptions: ["Nicht angegeben", "Dringend / laufender Release", "Innerhalb eines Monats", "1–3 Monate", "Über 3 Monate"],
  },
};
