import type { Locale } from "./types";

export type PackageSlug = "full-svg-flutter" | "woff2" | "quickjs-engine";

type PackageText = {
  tagline: string;
  problem: string;
  architecture: string;
  useCases: string[];
  limits: string[];
  apiDescriptions: string[];
};

type LocaleDocsText = {
  navLabel: string;
  title: string;
  intro: string;
  snapshot: string;
  labels: {
    problem: string;
    install: string;
    quickStart: string;
    capabilities: string;
    architecture: string;
    api: string;
    useWhen: string;
    limits: string;
    source: string;
    pub: string;
  };
  packages: Record<PackageSlug, PackageText>;
};

export type PackageDoc = PackageText & {
  slug: PackageSlug;
  name: string;
  version: string;
  license: string;
  pubPoints: string;
  install: string;
  quickStart: string;
  capabilities: string[];
  api: string[];
  sourceUrl: string;
  pubUrl: string;
};

export type DocsCopy = Omit<LocaleDocsText, "packages"> & {
  seo: { title: string; description: string };
  packages: PackageDoc[];
};

export const packageSlugs: PackageSlug[] = ["full-svg-flutter", "woff2", "quickjs-engine"];

const sourceUrl = "https://github.com/denisnadey/flutter_full_svg_support";
const meta: Record<PackageSlug, Omit<PackageDoc, keyof PackageText>> = {
  "full-svg-flutter": {
    slug: "full-svg-flutter",
    name: "full_svg_flutter",
    version: "1.4.2",
    license: "MIT",
    pubPoints: "140 / 160",
    install: "flutter pub add full_svg_flutter",
    quickStart: `import 'package:full_svg_flutter/full_svg_flutter.dart';

// Static or animated — the runtime detects the document.
FSvgPicture.asset(
  'assets/hero.svg',
  width: 240,
  semanticsLabel: 'Product illustration',
);

// Existing static flutter_svg usage can keep the familiar API.
SvgPicture.asset('assets/icon.svg');`,
    capabilities: ["Static SVG and DOM-preserving rendering", "SMIL and CSS @keyframes animation", "Path morphing and motion paths", "All 17 SVG filter primitives", "Masks, clipping, gradients, patterns, and rich text", "Inline JavaScript and SVGator exports", "Playback control and SVG <view> navigation", "flutter_svg-compatible static API"],
    api: ["FSvgPicture", "SvgPicture", "AnimatedSvgController", "renderSvgToPicture", "svg.cache"],
    sourceUrl,
    pubUrl: "https://pub.dev/packages/full_svg_flutter",
  },
  woff2: {
    slug: "woff2",
    name: "woff2",
    version: "0.1.0",
    license: "Apache-2.0",
    pubPoints: "150 / 160",
    install: "flutter pub add woff2",
    quickStart: `import 'package:flutter/material.dart';
import 'package:woff2/woff2.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await loadWoffFontFromAsset(
    fontFamily: 'Inter',
    assetPath: 'assets/fonts/Inter.woff2',
  );
  runApp(const MyApp());
}`,
    capabilities: ["WOFF1 and WOFF2 to SFNT decoding", "One-call Flutter FontLoader integration", "Pure-Dart font pipeline for app code", "CSS @font-face parsing", "Batch registration for weights and styles", "Embedded data: URL fonts", "Low-level byte decoder", "35 focused unit tests in the public package"],
    api: ["loadWoffFontFromAsset", "loadWoffFontFromBytes", "WoffFontRegistry", "extractFontFaceRules", "decodeFontIfWoff"],
    sourceUrl: `${sourceUrl}/tree/main/packages/woff2`,
    pubUrl: "https://pub.dev/packages/woff2",
  },
  "quickjs-engine": {
    slug: "quickjs-engine",
    name: "quickjs_engine",
    version: "0.1.3",
    license: "MIT",
    pubPoints: "120 / 160",
    install: "flutter pub add quickjs_engine",
    quickStart: `import 'package:quickjs_engine/quickjs_engine.dart';

final js = getJavascriptRuntime(xhr: false);
final result = js.evaluate('2 + 2');
print(result.stringResult); // 4

js.onMessage('bridge', (dynamic value) => 'pong');
js.evaluate('sendMessage("bridge", "ping")');
js.dispose();`,
    capabilities: ["QuickJS-NG 0.14.0 bundled with Flutter", "One engine across Android, iOS, macOS, Linux, and Windows", "Modern ES2020+ language features", "Dart ↔ JavaScript message bridge", "Optional fetch, XHR, and Promise helpers", "flutter_js-compatible entry points", "Native builds integrated with Flutter tooling", "16 KB Android ELF page alignment"],
    api: ["getJavascriptRuntime", "evaluate", "onMessage", "enableFetch", "enableHandlePromises"],
    sourceUrl: `${sourceUrl}/tree/main/packages/quickjs_engine`,
    pubUrl: "https://pub.dev/packages/quickjs_engine",
  },
};

const docsByLocale: Record<Locale, LocaleDocsText> = {
  en: {
    navLabel: "Docs",
    title: "Documentation for the runtimes behind real edge cases.",
    intro: "Three focused Flutter packages: a full SVG runtime, a WOFF/WOFF2 font pipeline, and one modern JavaScript engine across native platforms. Start with the problem, then copy the smallest working example.",
    snapshot: "Public package snapshot · 17 Aug 2026",
    labels: { problem: "Why it exists", install: "Install", quickStart: "Quick start", capabilities: "Coverage", architecture: "How it works", api: "API map", useWhen: "Use it when", limits: "Know before shipping", source: "Source & full README", pub: "Package on pub.dev" },
    packages: {
      "full-svg-flutter": { tagline: "Keep SVG as the source format inside Flutter.", problem: "Static icons are only a small part of SVG. Product assets may rely on SMIL, CSS animation, morphing, filters, text, or an inline JavaScript player. Converting them adds a second source of truth; a WebView adds a second rendering system.", architecture: "The package parses an SVG document into its own DOM-preserving model, evaluates style and animation state, then paints through Flutter. Static and animated content share the same engine. JavaScript starts lazily only when a script element is present.", useCases: ["You receive animated SVG or SVGator assets and cannot change the source format.", "You need filter, mask, text, or animation fidelity beyond static icon rendering.", "You want a familiar flutter_svg-style API and a migration path without a WebView."], limits: ["It is an SVG runtime, not a complete browser DOM; foreignObject and browser-dependent frameworks are outside scope.", "Validate complex filter and mixed-direction text assets visually before release."], apiDescriptions: ["Primary widget for static or animated assets from asset, network, string, file, or bytes.", "Static, flutter_svg-compatible entry point.", "Play, pause, seek, change rate or direction, and switch SVG views.", "Record an SVG into a Picture for custom painting or rasterization.", "Configurable decoded-source cache shared across widgets."] },
      woff2: { tagline: "Load web-font containers through Flutter's FontLoader.", problem: "Flutter accepts TTF/OTF through FontLoader but does not decode WOFF or WOFF2. Passing compressed web-font bytes directly can produce missing-glyph boxes without a useful error.", architecture: "The decoder reconstructs SFNT bytes from WOFF1/WOFF2, then registers the result with FontLoader. A CSS parser and registry cover SVG, HTML, EPUB, and other content pipelines that carry @font-face rules.", useCases: ["An SVG, EPUB, HTML export, or design asset embeds WOFF/WOFF2 fonts.", "You need to load a font downloaded at runtime or stored as a regular asset.", "You are building a renderer and need low-level WOFF bytes converted to SFNT."], limits: ["WOFF2 TTC collections are not supported in 0.1.0.", "Flutter Web already handles WOFF2 in the browser; the package targets native Flutter platforms."], apiDescriptions: ["Decode and register a bundled WOFF/WOFF2 asset in one call.", "Register font bytes fetched from network, disk, or memory.", "Batch-register families, weights, and styles.", "Extract @font-face rules, including data URLs and quoted values.", "Low-level container detection and conversion to SFNT bytes."] },
      "quickjs-engine": { tagline: "Run the same modern JavaScript engine on every Flutter platform.", problem: "A mixed JavaScriptCore/old-QuickJS setup can behave differently per platform, especially around numeric edge cases, Proxy, iteration, promises, or animation runtimes. That divergence is difficult to reproduce and harder to trust.", architecture: "The package bundles QuickJS-NG 0.14.0 and routes every supported native platform through the same engine and FFI bridge. Flutter's build pipeline compiles or bundles the native library; Dart owns evaluation, messaging, and optional web-style helpers.", useCases: ["A Flutter product needs embedded JavaScript evaluation with consistent cross-platform behavior.", "You are migrating from flutter_js and want its familiar entry points on a current engine.", "You need a small scripting layer, expression engine, validator, or SVG player without a WebView."], limits: ["Treat evaluated code as a deliberate trust boundary and expose only the host capabilities it needs.", "Desktop unit tests may require building or pointing to the native library outside the normal plugin pipeline."], apiDescriptions: ["Create the platform-consistent QuickJS runtime.", "Evaluate JavaScript and inspect the result.", "Expose named Dart callbacks to JavaScript.", "Opt into fetch/XHR behavior when the workload requires it.", "Bridge promise completion back into Dart." ] },
    },
  },
  ru: {
    navLabel: "Документация", title: "Документация рантаймов, выросших из реальных пограничных случаев.", intro: "Три узкоспециализированных Flutter-пакета: полный SVG-рантайм, пайплайн шрифтов WOFF/WOFF2 и один современный JavaScript-движок для всех нативных платформ. Сначала проблема, потом минимальный рабочий пример.", snapshot: "Публичный срез пакетов · 17 августа 2026", labels: { problem: "Зачем он нужен", install: "Установка", quickStart: "Быстрый старт", capabilities: "Покрытие", architecture: "Как устроен", api: "Карта API", useWhen: "Когда использовать", limits: "Знать до релиза", source: "Исходники и полный README", pub: "Пакет на pub.dev" },
    packages: {
      "full-svg-flutter": { tagline: "Оставить SVG исходным форматом внутри Flutter.", problem: "Статические иконки — лишь малая часть SVG. Продуктовые ассеты могут опираться на SMIL, CSS-анимацию, морфинг, фильтры, текст или встроенный JavaScript-плеер. Конвертация плодит второй источник истины, WebView — вторую систему рендеринга.", architecture: "Пакет разбирает SVG-документ в собственную модель с сохранением DOM, вычисляет стили и состояние анимации и рисует средствами Flutter. Статический и анимированный контент идут через один движок. JavaScript запускается лениво и только при наличии элемента script.", useCases: ["Вы получаете анимированные SVG или экспорты SVGator и не можете поменять исходный формат.", "Нужна точность фильтров, масок, текста или анимации, а не только статические иконки.", "Нужен знакомый API в духе flutter_svg и путь миграции без WebView."], limits: ["Это SVG-рантайм, а не полный DOM браузера: foreignObject и зависящие от браузера фреймворки вне области применения.", "Сложные фильтры и текст со смешанным направлением письма проверяйте глазами до релиза."], apiDescriptions: ["Основной виджет для статических и анимированных ассетов из asset, сети, строки, файла или байтов.", "Статическая точка входа, совместимая с flutter_svg.", "Запуск, пауза, перемотка, скорость, направление и переключение SVG-видов.", "Запись SVG в Picture для кастомной отрисовки или растеризации.", "Настраиваемый кэш декодированных исходников, общий для виджетов."] },
      woff2: { tagline: "Загружать веб-шрифты через FontLoader во Flutter.", problem: "FontLoader во Flutter принимает TTF/OTF, но не декодирует WOFF и WOFF2. Если передать сжатые байты напрямую, вместо глифов появятся пустые квадраты, а полезной ошибки не будет.", architecture: "Декодер восстанавливает SFNT-байты из WOFF1/WOFF2 и регистрирует результат через FontLoader. CSS-парсер и реестр покрывают SVG, HTML, EPUB и другие пайплайны с правилами @font-face.", useCases: ["В SVG, EPUB, HTML-экспорте или дизайн-ассете встроены шрифты WOFF/WOFF2.", "Нужно загрузить шрифт, скачанный в рантайме или лежащий обычным asset.", "Вы пишете рендерер, и вам нужно низкоуровневое преобразование WOFF → SFNT."], limits: ["Коллекции WOFF2 TTC в версии 0.1.0 не поддерживаются.", "Во Flutter Web браузер уже умеет WOFF2; пакет нацелен на нативные платформы Flutter."], apiDescriptions: ["Декодировать и зарегистрировать WOFF/WOFF2 из assets одним вызовом.", "Зарегистрировать байты шрифта из сети, с диска или из памяти.", "Пакетная регистрация семейств, начертаний и стилей.", "Извлечь правила @font-face, включая data URL и значения в кавычках.", "Низкоуровневое определение контейнера и преобразование в SFNT."] },
      "quickjs-engine": { tagline: "Один и тот же современный JavaScript-движок на каждой платформе Flutter.", problem: "Смесь JavaScriptCore и старого QuickJS ведёт себя по-разному на разных платформах — особенно в пограничных случаях с числами, Proxy, итераторами, промисами и анимационными рантаймами. Такие расхождения трудно воспроизвести и нельзя игнорировать.", architecture: "Пакет включает QuickJS-NG 0.14.0 и проводит все поддерживаемые нативные платформы через один движок и один FFI-мост. Сборку или подключение нативной библиотеки берёт на себя пайплайн Flutter; на стороне Dart — выполнение кода, обмен сообщениями и необязательные веб-хелперы.", useCases: ["Flutter-продукту нужен встроенный JavaScript с одинаковым поведением на всех платформах.", "Вы мигрируете с flutter_js и хотите привычные точки входа на современном движке.", "Нужен небольшой слой скриптов, вычислитель выражений, валидатор или SVG-плеер без WebView."], limits: ["Считайте выполняемый код осознанной границей доверия и открывайте ему только нужные возможности хоста.", "Для unit-тестов на десктопе может понадобиться отдельно собрать нативную библиотеку или указать путь к ней."], apiDescriptions: ["Создать единый для всех платформ рантайм QuickJS.", "Выполнить JavaScript и посмотреть результат.", "Открыть JavaScript именованные callback-и на стороне Dart.", "Включить fetch/XHR, когда это нужно задаче.", "Прокинуть завершение промисов обратно в Dart."] },
    },
  },
  de: {
    navLabel: "Docs", title: "Dokumentation für Runtimes, die aus echten Grenzfällen entstanden sind.", intro: "Drei fokussierte Flutter-Pakete: eine vollständige SVG-Runtime, eine WOFF/WOFF2-Font-Pipeline und eine moderne JavaScript-Engine für alle nativen Plattformen. Erst das Problem, dann das kleinste lauffähige Beispiel.", snapshot: "Öffentlicher Paketstand · 17. August 2026", labels: { problem: "Warum es das gibt", install: "Installation", quickStart: "Schnellstart", capabilities: "Abdeckung", architecture: "So funktioniert es", api: "API-Übersicht", useWhen: "Einsetzen, wenn", limits: "Vor dem Release wissen", source: "Quellcode & vollständiges README", pub: "Paket auf pub.dev" },
    packages: {
      "full-svg-flutter": { tagline: "SVG als Quellformat in Flutter behalten.", problem: "Statische Icons sind nur ein kleiner Teil von SVG. Produkt-Assets nutzen oft SMIL, CSS-Animation, Morphing, Filter, Text oder einen eingebetteten JavaScript-Player. Konvertierung schafft eine zweite Quelle der Wahrheit, ein WebView ein zweites Rendering-System.", architecture: "Das Paket parst ein SVG-Dokument in ein eigenes DOM-erhaltendes Modell, wertet Style- und Animationszustand aus und zeichnet über Flutter. Statischer und animierter Inhalt laufen durch dieselbe Engine. JavaScript startet erst, wenn tatsächlich ein script-Element vorhanden ist.", useCases: ["Sie bekommen animierte SVG- oder SVGator-Assets und können das Quellformat nicht ändern.", "Sie brauchen Filter-, Masken-, Text- oder Animationstreue jenseits statischer Icons.", "Sie wollen ein vertrautes API im Stil von flutter_svg und einen Migrationspfad ohne WebView."], limits: ["Es ist eine SVG-Runtime, kein vollständiges Browser-DOM; foreignObject und browserabhängige Frameworks liegen außerhalb des Scopes.", "Komplexe Filter und Text mit gemischter Schreibrichtung vor dem Release visuell prüfen."], apiDescriptions: ["Primäres Widget für statische oder animierte Assets aus Asset, Netzwerk, String, Datei oder Bytes.", "Statischer, flutter_svg-kompatibler Einstiegspunkt.", "Abspielen, pausieren, springen, Geschwindigkeit und Richtung ändern, SVG-Views wechseln.", "Ein SVG in ein Picture zeichnen – für eigenes Painting oder Rasterisierung.", "Konfigurierbarer Cache für dekodierte Quellen, geteilt über alle Widgets."] },
      woff2: { tagline: "Webfont-Container über Flutters FontLoader laden.", problem: "Flutter nimmt TTF/OTF über FontLoader an, dekodiert aber weder WOFF noch WOFF2. Wer komprimierte Webfont-Bytes direkt übergibt, bekommt leere Glyphenkästen – ohne brauchbare Fehlermeldung.", architecture: "Der Decoder rekonstruiert SFNT-Bytes aus WOFF1/WOFF2 und registriert das Ergebnis über FontLoader. Ein CSS-Parser und eine Registry decken SVG-, HTML-, EPUB- und andere Content-Pipelines mit @font-face-Regeln ab.", useCases: ["Ein SVG, EPUB, HTML-Export oder Design-Asset bettet WOFF/WOFF2-Schriften ein.", "Eine Schrift wird zur Laufzeit heruntergeladen oder liegt als normales Asset vor.", "Sie bauen einen Renderer und brauchen die Low-Level-Konvertierung von WOFF-Bytes nach SFNT."], limits: ["WOFF2-TTC-Sammlungen werden in 0.1.0 nicht unterstützt.", "Flutter Web überlässt WOFF2 dem Browser; das Paket zielt auf die nativen Flutter-Plattformen."], apiDescriptions: ["Ein gebündeltes WOFF/WOFF2-Asset in einem Aufruf dekodieren und registrieren.", "Font-Bytes aus Netzwerk, Datei oder Speicher registrieren.", "Familien, Schnitte und Stile gesammelt registrieren.", "@font-face-Regeln extrahieren, inklusive Data-URLs und Werten in Anführungszeichen.", "Low-Level-Erkennung des Containers und Konvertierung nach SFNT."] },
      "quickjs-engine": { tagline: "Dieselbe moderne JavaScript-Engine auf jeder Flutter-Plattform.", problem: "Eine Mischung aus JavaScriptCore und altem QuickJS verhält sich je nach Plattform unterschiedlich – besonders bei numerischen Grenzfällen, Proxy, Iteration, Promises oder Animations-Runtimes. Solche Abweichungen sind schwer zu reproduzieren und noch schwerer zu vertrauen.", architecture: "Das Paket bündelt QuickJS-NG 0.14.0 und führt jede unterstützte native Plattform über dieselbe Engine und dieselbe FFI-Bridge. Flutters Build-Pipeline kompiliert oder bündelt die native Bibliothek; Dart übernimmt Auswertung, Messaging und optionale Web-Helfer.", useCases: ["Ein Flutter-Produkt braucht eingebettetes JavaScript mit konsistentem Verhalten über alle Plattformen.", "Sie migrieren von flutter_js und wollen dessen vertraute Einstiegspunkte auf einer aktuellen Engine.", "Sie brauchen eine kleine Scripting-Schicht, eine Expression-Engine, einen Validator oder einen SVG-Player ohne WebView."], limits: ["Ausgeführten Code als bewusste Vertrauensgrenze behandeln und nur die Host-Fähigkeiten freigeben, die er braucht.", "Desktop-Unit-Tests können erfordern, die native Bibliothek außerhalb der normalen Plugin-Pipeline zu bauen oder zu referenzieren."], apiDescriptions: ["Die plattformübergreifend konsistente QuickJS-Runtime erzeugen.", "JavaScript auswerten und das Ergebnis inspizieren.", "Benannte Dart-Callbacks für JavaScript bereitstellen.", "fetch/XHR-Verhalten aktivieren, wenn die Aufgabe es verlangt.", "Promise-Auflösung zurück nach Dart bringen."] },
    },
  },
  fr: {
    navLabel: "Docs", title: "La documentation de runtimes nés de vrais cas limites.", intro: "Trois packages Flutter ciblés : un runtime SVG complet, un pipeline de polices WOFF/WOFF2 et un même moteur JavaScript moderne sur toutes les plateformes natives. Commencez par le problème, puis copiez le plus petit exemple qui fonctionne.", snapshot: "État public des packages · 17 août 2026", labels: { problem: "Pourquoi il existe", install: "Installation", quickStart: "Démarrage rapide", capabilities: "Couverture", architecture: "Comment ça marche", api: "Carte de l'API", useWhen: "À utiliser quand", limits: "À savoir avant la mise en production", source: "Source et README complet", pub: "Package sur pub.dev" },
    packages: {
      "full-svg-flutter": { tagline: "Garder le SVG comme format source dans Flutter.", problem: "Les icônes statiques ne sont qu'une petite partie du SVG. Les assets produit peuvent reposer sur SMIL, des animations CSS, du morphing, des filtres, du texte ou un lecteur JavaScript inline. Les convertir ajoute une seconde source de vérité ; un WebView ajoute un second système de rendu.", architecture: "Le package analyse un document SVG dans son propre modèle préservant le DOM, évalue les styles et l'état d'animation, puis dessine via Flutter. Contenu statique et contenu animé partagent le même moteur. JavaScript ne démarre que si un élément script est présent.", useCases: ["Vous recevez des SVG animés ou des assets SVGator et ne pouvez pas changer le format source.", "Vous avez besoin d'une fidélité des filtres, masques, textes ou animations qui dépasse le rendu d'icônes statiques.", "Vous voulez une API familière, dans l'esprit de flutter_svg, et un chemin de migration sans WebView."], limits: ["C'est un runtime SVG, pas un DOM de navigateur complet ; foreignObject et les frameworks dépendants du navigateur sont hors périmètre.", "Validez visuellement les filtres complexes et les textes à direction mixte avant la mise en production."], apiDescriptions: ["Widget principal pour les assets statiques ou animés depuis un asset, le réseau, une chaîne, un fichier ou des bytes.", "Point d'entrée statique compatible avec flutter_svg.", "Lecture, pause, seek, changement de vitesse ou de direction, et bascule entre vues SVG.", "Enregistrement d'un SVG dans un Picture pour un painting personnalisé ou une rastérisation.", "Cache configurable des sources décodées, partagé entre les widgets."] },
      woff2: { tagline: "Charger des conteneurs de polices web via le FontLoader de Flutter.", problem: "Flutter accepte le TTF/OTF via FontLoader mais ne décode ni WOFF ni WOFF2. Lui passer directement des bytes de police web compressés produit des glyphes vides, sans erreur exploitable.", architecture: "Le décodeur reconstruit les bytes SFNT à partir du WOFF1/WOFF2, puis enregistre le résultat auprès de FontLoader. Un parseur CSS et un registre couvrent les pipelines SVG, HTML, EPUB et autres contenus qui transportent des règles @font-face.", useCases: ["Un SVG, un EPUB, un export HTML ou un asset de design embarque des polices WOFF/WOFF2.", "Vous devez charger une police téléchargée à l'exécution ou stockée comme un asset ordinaire.", "Vous construisez un moteur de rendu et avez besoin de convertir des bytes WOFF en SFNT à bas niveau."], limits: ["Les collections WOFF2 TTC ne sont pas prises en charge en 0.1.0.", "Flutter Web gère déjà le WOFF2 dans le navigateur ; le package vise les plateformes Flutter natives."], apiDescriptions: ["Décoder et enregistrer un asset WOFF/WOFF2 embarqué en un seul appel.", "Enregistrer des bytes de police venant du réseau, du disque ou de la mémoire.", "Enregistrer en lot des familles, des graisses et des styles.", "Extraire les règles @font-face, y compris les data URL et les valeurs entre guillemets.", "Détection bas niveau du conteneur et conversion en bytes SFNT."] },
      "quickjs-engine": { tagline: "Le même moteur JavaScript moderne sur chaque plateforme Flutter.", problem: "Un mélange de JavaScriptCore et d'un vieux QuickJS peut se comporter différemment selon la plateforme, surtout sur les cas limites numériques, Proxy, l'itération, les promesses ou les runtimes d'animation. Ces divergences sont difficiles à reproduire et encore plus difficiles à assumer.", architecture: "Le package embarque QuickJS-NG 0.14.0 et fait passer chaque plateforme native prise en charge par le même moteur et le même pont FFI. Le pipeline de build de Flutter compile ou embarque la bibliothèque native ; Dart se charge de l'évaluation, de la messagerie et des helpers web optionnels.", useCases: ["Un produit Flutter a besoin d'évaluer du JavaScript embarqué avec un comportement cohérent sur toutes les plateformes.", "Vous migrez depuis flutter_js et voulez retrouver ses points d'entrée familiers sur un moteur à jour.", "Vous avez besoin d'une petite couche de scripting, d'un moteur d'expressions, d'un validateur ou d'un lecteur SVG sans WebView."], limits: ["Traitez le code évalué comme une frontière de confiance délibérée et n'exposez que les capacités hôtes dont il a besoin.", "Les tests unitaires desktop peuvent exiger de compiler ou de référencer la bibliothèque native en dehors du pipeline de plugin habituel."], apiDescriptions: ["Créer le runtime QuickJS cohérent sur toutes les plateformes.", "Évaluer du JavaScript et inspecter le résultat.", "Exposer des callbacks Dart nommés à JavaScript.", "Activer fetch/XHR quand la charge de travail l'exige.", "Ramener la résolution des promesses vers Dart."] },
    },
  },
  es: {
    navLabel: "Docs", title: "Documentación de los runtimes que hay detrás de casos límite reales.", intro: "Tres paquetes Flutter con un objetivo concreto: un runtime SVG completo, un pipeline de fuentes WOFF/WOFF2 y un único motor JavaScript moderno para todas las plataformas nativas. Empieza por el problema y copia después el ejemplo más pequeño que funcione.", snapshot: "Cifras públicas de los paquetes · 17 ago 2026", labels: { problem: "Por qué existe", install: "Instalación", quickStart: "Inicio rápido", capabilities: "Cobertura", architecture: "Cómo funciona", api: "Mapa de la API", useWhen: "Úsalo cuando", limits: "Antes de publicar", source: "Código fuente y README completo", pub: "Paquete en pub.dev" },
    packages: {
      "full-svg-flutter": { tagline: "Mantén el SVG como formato fuente dentro de Flutter.", problem: "Los iconos estáticos son solo una pequeña parte del SVG. Los assets de producto pueden depender de SMIL, animación CSS, morphing, filtros, texto o un reproductor JavaScript inline. Convertirlos añade una segunda fuente de verdad; un WebView añade un segundo sistema de renderizado.", architecture: "El paquete analiza el documento SVG en su propio modelo, que conserva el DOM, evalúa el estilo y el estado de la animación y después pinta a través de Flutter. El contenido estático y el animado comparten el mismo motor. JavaScript solo se inicia cuando hay un elemento script, y no antes.", useCases: ["Recibes SVG animados o assets de SVGator y no puedes cambiar el formato de origen.", "Necesitas fidelidad en filtros, máscaras, texto o animación más allá del renderizado de iconos estáticos.", "Quieres una API al estilo de flutter_svg y una ruta de migración sin WebView."], limits: ["Es un runtime SVG, no un DOM de navegador completo; foreignObject y los frameworks que dependen del navegador quedan fuera del alcance.", "Valida visualmente los assets con filtros complejos y texto de dirección mixta antes de la release."], apiDescriptions: ["Widget principal para assets estáticos o animados desde asset, red, string, archivo o bytes.", "Punto de entrada estático compatible con flutter_svg.", "Reproduce, pausa, hace seek, cambia la velocidad o la dirección y alterna vistas SVG.", "Graba un SVG en un Picture para pintado personalizado o rasterización.", "Caché configurable de fuentes decodificadas, compartida entre widgets."] },
      woff2: { tagline: "Carga contenedores de fuentes web a través del FontLoader de Flutter.", problem: "Flutter acepta TTF/OTF a través de FontLoader, pero no decodifica WOFF ni WOFF2. Pasar directamente los bytes comprimidos de una fuente web puede producir cajas de glifos ausentes sin ningún error útil.", architecture: "El decoder reconstruye los bytes SFNT a partir de WOFF1/WOFF2 y registra el resultado con FontLoader. Un parser de CSS y un registro cubren SVG, HTML, EPUB y otros pipelines de contenido que llevan reglas @font-face.", useCases: ["Un SVG, un EPUB, una exportación HTML o un asset de diseño incrusta fuentes WOFF/WOFF2.", "Necesitas cargar una fuente descargada en tiempo de ejecución o guardada como un asset normal.", "Estás construyendo un renderizador y necesitas convertir bytes WOFF de bajo nivel a SFNT."], limits: ["Las colecciones WOFF2 TTC no están soportadas en la 0.1.0.", "Flutter Web ya gestiona WOFF2 en el navegador; el paquete está pensado para las plataformas nativas de Flutter."], apiDescriptions: ["Decodifica y registra un asset WOFF/WOFF2 empaquetado en una sola llamada.", "Registra bytes de fuente obtenidos de la red, del disco o de memoria.", "Registra por lotes familias, pesos y estilos.", "Extrae reglas @font-face, incluidas data URLs y valores entre comillas.", "Detección de contenedor de bajo nivel y conversión a bytes SFNT."] },
      "quickjs-engine": { tagline: "Ejecuta el mismo motor JavaScript moderno en todas las plataformas Flutter.", problem: "Una combinación de JavaScriptCore y un QuickJS antiguo puede comportarse distinto en cada plataforma, sobre todo en casos límite numéricos, Proxy, iteración, Promises o runtimes de animación. Esa divergencia es difícil de reproducir y todavía más difícil de dar por fiable.", architecture: "El paquete incluye QuickJS-NG 0.14.0 y hace pasar todas las plataformas nativas soportadas por el mismo motor y el mismo puente FFI. El pipeline de build de Flutter compila o empaqueta la biblioteca nativa; Dart se encarga de la evaluación, la mensajería y los helpers opcionales al estilo web.", useCases: ["Un producto Flutter necesita evaluar JavaScript embebido con un comportamiento coherente entre plataformas.", "Migras desde flutter_js y quieres sus puntos de entrada de siempre sobre un motor actual.", "Necesitas una capa de scripting pequeña, un motor de expresiones, un validador o un reproductor SVG sin WebView."], limits: ["Trata el código evaluado como una frontera de confianza deliberada y expón solo las capacidades del host que necesite.", "Los tests unitarios en escritorio pueden requerir compilar la biblioteca nativa o apuntar a ella fuera del pipeline normal del plugin."], apiDescriptions: ["Crea el runtime QuickJS, coherente entre plataformas.", "Evalúa JavaScript e inspecciona el resultado.", "Expone callbacks de Dart con nombre a JavaScript.", "Activa el comportamiento de fetch/XHR cuando la carga de trabajo lo requiere.", "Devuelve a Dart la finalización de las Promises."] },
    },
  },
  it: {
    navLabel: "Docs", title: "Documentazione dei runtime nati da casi limite reali.", intro: "Tre package Flutter mirati: un runtime SVG completo, una pipeline per font WOFF/WOFF2 e un unico motore JavaScript moderno per tutte le piattaforme native. Parti dal problema, poi copia l'esempio funzionante più piccolo.", snapshot: "Snapshot pubblico dei package · 17 agosto 2026", labels: { problem: "Perché esiste", install: "Installazione", quickStart: "Quick start", capabilities: "Copertura", architecture: "Come funziona", api: "Mappa dell'API", useWhen: "Usalo quando", limits: "Da sapere prima del rilascio", source: "Sorgente e README completo", pub: "Package su pub.dev" },
    packages: {
      "full-svg-flutter": { tagline: "Tieni l'SVG come formato sorgente dentro Flutter.", problem: "Le icone statiche sono solo una piccola parte di SVG. Gli asset di prodotto possono dipendere da SMIL, animazioni CSS, morphing, filtri, testo o un player JavaScript inline. Convertirli aggiunge una seconda fonte di verità; una WebView aggiunge un secondo sistema di rendering.", architecture: "Il package analizza il documento SVG in un proprio modello che preserva il DOM, valuta lo stato di stile e animazione, poi disegna tramite Flutter. Contenuto statico e animato condividono lo stesso motore. JavaScript parte in modo lazy, solo quando è presente un elemento script.", useCases: ["Ricevi asset SVG animati o SVGator e non puoi cambiare il formato sorgente.", "Ti serve una fedeltà di filtri, maschere, testo o animazioni che vada oltre il rendering di icone statiche.", "Vuoi un'API familiare in stile flutter_svg e un percorso di migrazione senza WebView."], limits: ["È un runtime SVG, non un DOM browser completo: foreignObject e i framework che dipendono dal browser sono fuori scope.", "Verifica visivamente gli asset con filtri complessi e testo a direzione mista prima del rilascio."], apiDescriptions: ["Widget principale per asset statici o animati da asset, rete, stringa, file o byte.", "Entry point statico, compatibile con flutter_svg.", "Play, pausa, seek, cambio di velocità o direzione e passaggio tra view SVG.", "Registra un SVG in una Picture per painting custom o rasterizzazione.", "Cache configurabile delle sorgenti decodificate, condivisa tra i widget."] },
      woff2: { tagline: "Carica i container di web font attraverso il FontLoader di Flutter.", problem: "Flutter accetta TTF/OTF tramite FontLoader ma non decodifica WOFF né WOFF2. Passare direttamente i byte compressi di un web font può produrre rettangoli di glifi mancanti senza un errore utile.", architecture: "Il decoder ricostruisce i byte SFNT da WOFF1/WOFF2, poi registra il risultato con FontLoader. Un parser CSS e un registry coprono SVG, HTML, EPUB e altre pipeline di contenuti che portano regole @font-face.", useCases: ["Un SVG, un EPUB, un export HTML o un asset di design incorpora font WOFF/WOFF2.", "Devi caricare un font scaricato a runtime o salvato come asset normale.", "Stai costruendo un renderer e ti servono byte WOFF di basso livello convertiti in SFNT."], limits: ["Le collezioni WOFF2 TTC non sono supportate nella 0.1.0.", "Flutter Web gestisce già WOFF2 nel browser; il package è pensato per le piattaforme native di Flutter."], apiDescriptions: ["Decodifica e registra un asset WOFF/WOFF2 incluso nell'app in una sola chiamata.", "Registra byte di font ottenuti da rete, disco o memoria.", "Registra in batch famiglie, pesi e stili.", "Estrae le regole @font-face, inclusi data URL e valori tra virgolette.", "Rilevamento del container a basso livello e conversione in byte SFNT."] },
      "quickjs-engine": { tagline: "Lo stesso motore JavaScript moderno su ogni piattaforma Flutter.", problem: "Una configurazione mista JavaScriptCore/vecchio QuickJS può comportarsi in modo diverso su ogni piattaforma, soprattutto su casi limite numerici, Proxy, iterazione, promise o runtime di animazione. Quella divergenza è difficile da riprodurre e ancora più difficile da considerare affidabile.", architecture: "Il package include QuickJS-NG 0.14.0 e fa passare ogni piattaforma nativa supportata dallo stesso motore e dallo stesso bridge FFI. La pipeline di build di Flutter compila o include la libreria nativa; Dart gestisce valutazione, messaggistica e gli helper opzionali in stile web.", useCases: ["Un prodotto Flutter ha bisogno di valutare JavaScript embedded con un comportamento coerente tra piattaforme.", "Stai migrando da flutter_js e vuoi i suoi entry point familiari su un motore aggiornato.", "Ti serve un piccolo livello di scripting, un motore di espressioni, un validatore o un player SVG senza WebView."], limits: ["Tratta il codice valutato come un confine di fiducia esplicito ed esponi solo le capacità dell'host di cui ha davvero bisogno.", "I test unitari su desktop possono richiedere di compilare la libreria nativa, o di puntare a essa, fuori dalla normale pipeline del plugin."], apiDescriptions: ["Crea il runtime QuickJS coerente tra piattaforme.", "Valuta JavaScript e ispeziona il risultato.", "Espone a JavaScript callback Dart con nome.", "Abilita il comportamento fetch/XHR quando il carico di lavoro lo richiede.", "Riporta in Dart il completamento delle promise."] },
    },
  },
  pl: {
    navLabel: "Dokumentacja", title: "Dokumentacja runtime'ów, które powstały z prawdziwych przypadków brzegowych.", intro: "Trzy wyspecjalizowane pakiety Flutter: pełny runtime SVG, pipeline fontów WOFF/WOFF2 i jeden nowoczesny silnik JavaScript na wszystkich platformach natywnych. Zacznij od problemu, potem skopiuj najmniejszy działający przykład.", snapshot: "Publiczne pakiety · stan na 17 sierpnia 2026", labels: { problem: "Po co powstał", install: "Instalacja", quickStart: "Szybki start", capabilities: "Zakres", architecture: "Jak działa", api: "Mapa API", useWhen: "Użyj, gdy", limits: "Zanim wydasz", source: "Kod źródłowy i pełne README", pub: "Pakiet na pub.dev" },
    packages: {
      "full-svg-flutter": { tagline: "Zachowaj SVG jako format źródłowy we Flutterze.", problem: "Statyczne ikony to tylko mały wycinek SVG. Assety produktowe mogą opierać się na SMIL, animacjach CSS, morphingu, filtrach, tekście albo wbudowanym odtwarzaczu w JavaScripcie. Konwersja dokłada drugie źródło prawdy, a WebView – drugi system renderowania.", architecture: "Pakiet parsuje dokument SVG do własnego modelu zachowującego DOM, wylicza style i stan animacji, a potem rysuje przez Flutter. Treść statyczna i animowana korzysta z tego samego silnika. JavaScript startuje leniwie i tylko wtedy, gdy w dokumencie jest element script.", useCases: ["Dostajesz animowane SVG albo assety z SVGator i nie możesz zmienić formatu źródłowego.", "Potrzebujesz wierności filtrów, masek, tekstu lub animacji wykraczającej poza statyczne ikony.", "Chcesz znajomego API w stylu flutter_svg i ścieżki migracji bez WebView."], limits: ["To runtime SVG, nie pełny DOM przeglądarki – foreignObject i frameworki zależne od przeglądarki są poza zakresem.", "Złożone filtry i tekst o mieszanym kierunku sprawdź wizualnie przed wydaniem."], apiDescriptions: ["Główny widget dla statycznych i animowanych assetów ładowanych z assetów, sieci, stringa, pliku lub bajtów.", "Statyczny punkt wejścia zgodny z flutter_svg.", "Odtwarzanie, pauza, seek, zmiana tempa lub kierunku i przełączanie widoków SVG.", "Zapis SVG do Picture na potrzeby własnego rysowania lub rasteryzacji.", "Konfigurowalny cache zdekodowanych źródeł, współdzielony między widgetami."] },
      woff2: { tagline: "Ładuj kontenery fontów webowych przez FontLoader Fluttera.", problem: "Flutter przyjmuje TTF/OTF przez FontLoader, ale nie dekoduje WOFF ani WOFF2. Podanie skompresowanych bajtów fontu webowego wprost może skończyć się pustymi prostokątami zamiast glifów – bez żadnego sensownego błędu.", architecture: "Dekoder odtwarza bajty SFNT z WOFF1/WOFF2, a wynik rejestruje w FontLoaderze. Parser CSS i rejestr obsługują SVG, HTML, EPUB i inne pipeline'y treści, które niosą reguły @font-face.", useCases: ["SVG, EPUB, eksport HTML albo asset projektowy ma osadzone fonty WOFF/WOFF2.", "Musisz załadować font pobrany w czasie działania aplikacji albo trzymany jako zwykły asset.", "Budujesz renderer i potrzebujesz niskopoziomowej konwersji bajtów WOFF do SFNT."], limits: ["Kolekcje WOFF2 TTC nie są wspierane w wersji 0.1.0.", "Flutter Web obsługuje WOFF2 już w przeglądarce; pakiet celuje w natywne platformy Flutter."], apiDescriptions: ["Dekoduje i rejestruje dołączony asset WOFF/WOFF2 jednym wywołaniem.", "Rejestruje bajty fontu pobrane z sieci, dysku lub pamięci.", "Rejestruje hurtowo rodziny, grubości i style.", "Wyciąga reguły @font-face, w tym data URL i wartości w cudzysłowach.", "Niskopoziomowe wykrywanie kontenera i konwersja do bajtów SFNT."] },
      "quickjs-engine": { tagline: "Ten sam nowoczesny silnik JavaScript na każdej platformie Flutter.", problem: "Mieszanka JavaScriptCore i starego QuickJS może zachowywać się inaczej na każdej platformie – zwłaszcza przy numerycznych przypadkach brzegowych, Proxy, iteracji, Promise czy runtime'ach animacji. Takie rozjazdy trudno odtworzyć, a jeszcze trudniej im zaufać.", architecture: "Pakiet dołącza QuickJS-NG 0.14.0 i kieruje każdą wspieraną platformę natywną przez ten sam silnik i most FFI. Pipeline buildu Fluttera kompiluje lub dołącza bibliotekę natywną; po stronie Darta jest ewaluacja, wymiana wiadomości i opcjonalne helpery w stylu webowym.", useCases: ["Produkt Flutter potrzebuje osadzonej ewaluacji JavaScriptu o spójnym zachowaniu na wszystkich platformach.", "Migrujesz z flutter_js i chcesz zachować znajome punkty wejścia na aktualnym silniku.", "Potrzebujesz małej warstwy skryptowej, silnika wyrażeń, walidatora albo odtwarzacza SVG bez WebView."], limits: ["Traktuj wykonywany kod jako świadomą granicę zaufania i udostępniaj mu tylko te możliwości hosta, których naprawdę potrzebuje.", "Testy jednostkowe na desktopie mogą wymagać zbudowania biblioteki natywnej albo wskazania jej poza zwykłym pipeline'em pluginu."], apiDescriptions: ["Tworzy runtime QuickJS spójny między platformami.", "Wykonuje JavaScript i pozwala sprawdzić wynik.", "Udostępnia nazwane callbacki Darta w JavaScripcie.", "Włącza fetch/XHR, gdy wymaga tego obciążenie.", "Przekazuje zakończenie Promise z powrotem do Darta."] },
    },
  },
  pt: {
    navLabel: "Docs", title: "Documentação dos runtimes por trás de edge cases reais.", intro: "Três pacotes Flutter focados: um runtime SVG completo, um pipeline de fontes WOFF/WOFF2 e um único motor JavaScript moderno para todas as plataformas nativas. Comece pelo problema, depois copie o menor exemplo que funciona.", snapshot: "Snapshot público dos pacotes · 17 ago 2026", labels: { problem: "Por que existe", install: "Instalação", quickStart: "Início rápido", capabilities: "Cobertura", architecture: "Como funciona", api: "Mapa da API", useWhen: "Use quando", limits: "Saiba antes de publicar", source: "Código-fonte e README completo", pub: "Pacote no pub.dev" },
    packages: {
      "full-svg-flutter": { tagline: "Mantenha o SVG como formato de origem dentro do Flutter.", problem: "Ícones estáticos são só uma pequena parte do SVG. Assets de produto podem depender de SMIL, animação CSS, morphing, filtros, texto ou de um player JavaScript inline. Converter cria uma segunda fonte da verdade; uma WebView adiciona um segundo sistema de renderização.", architecture: "O pacote faz o parsing do documento SVG em um modelo próprio que preserva o DOM, avalia o estado de estilo e animação e então pinta pelo Flutter. Conteúdo estático e animado compartilham o mesmo motor. O JavaScript só inicia, sob demanda, quando existe um elemento script.", useCases: ["Você recebe SVGs animados ou assets do SVGator e não pode mudar o formato de origem.", "Você precisa de fidelidade em filtros, máscaras, texto ou animação além da renderização de ícones estáticos.", "Você quer uma API familiar no estilo do flutter_svg e um caminho de migração sem WebView."], limits: ["É um runtime SVG, não um DOM de navegador completo; foreignObject e frameworks que dependem do navegador estão fora do escopo.", "Valide visualmente assets com filtros complexos e texto em direções mistas antes da release."], apiDescriptions: ["Widget principal para assets estáticos ou animados a partir de asset, rede, string, arquivo ou bytes.", "Ponto de entrada estático, compatível com o flutter_svg.", "Reproduz, pausa, faz seek, muda velocidade ou direção e alterna views do SVG.", "Grava um SVG em um Picture para pintura customizada ou rasterização.", "Cache configurável de documentos decodificados, compartilhado entre widgets."] },
      woff2: { tagline: "Carregue contêineres de web fonts pelo FontLoader do Flutter.", problem: "O Flutter aceita TTF/OTF pelo FontLoader, mas não decodifica WOFF nem WOFF2. Passar os bytes comprimidos de uma web font diretamente pode gerar caixas de glifos ausentes, sem nenhum erro útil.", architecture: "O decoder reconstrói os bytes SFNT a partir de WOFF1/WOFF2 e registra o resultado no FontLoader. Um parser de CSS e um registry cobrem pipelines de conteúdo de SVG, HTML, EPUB e outros que carregam regras @font-face.", useCases: ["Um SVG, EPUB, exportação HTML ou asset de design embute fontes WOFF/WOFF2.", "Você precisa carregar uma fonte baixada em runtime ou guardada como um asset comum.", "Você está construindo um renderizador e precisa converter bytes WOFF de baixo nível em SFNT."], limits: ["Coleções WOFF2 TTC não são suportadas na 0.1.0.", "O Flutter Web já trata WOFF2 no navegador; o pacote é voltado às plataformas nativas do Flutter."], apiDescriptions: ["Decodifica e registra um asset WOFF/WOFF2 empacotado em uma única chamada.", "Registra bytes de fonte obtidos da rede, do disco ou da memória.", "Registra famílias, pesos e estilos em lote.", "Extrai regras @font-face, incluindo data URLs e valores entre aspas.", "Detecção de contêiner de baixo nível e conversão para bytes SFNT."] },
      "quickjs-engine": { tagline: "Rode o mesmo motor JavaScript moderno em todas as plataformas Flutter.", problem: "Uma configuração mista de JavaScriptCore com um QuickJS antigo pode se comportar de forma diferente em cada plataforma, principalmente em edge cases numéricos, Proxy, iteração, promises ou runtimes de animação. É difícil reproduzir essa divergência, e mais difícil ainda confiar nela.", architecture: "O pacote embarca o QuickJS-NG 0.14.0 e faz todas as plataformas nativas suportadas passarem pelo mesmo motor e pela mesma ponte FFI. O pipeline de build do Flutter compila ou empacota a biblioteca nativa; o Dart cuida da avaliação, das mensagens e dos helpers opcionais no estilo web.", useCases: ["Um produto Flutter precisa avaliar JavaScript embutido com comportamento consistente entre plataformas.", "Você está migrando do flutter_js e quer os mesmos pontos de entrada familiares em um motor atual.", "Você precisa de uma pequena camada de scripting, um motor de expressões, um validador ou um player SVG sem WebView."], limits: ["Trate o código avaliado como uma fronteira de confiança deliberada e exponha apenas as capacidades do host de que ele realmente precisa.", "Testes unitários em desktop podem exigir compilar a biblioteca nativa ou apontar para ela fora do pipeline normal do plugin."], apiDescriptions: ["Cria o runtime QuickJS consistente entre plataformas.", "Avalia JavaScript e inspeciona o resultado.", "Expõe callbacks Dart nomeados ao JavaScript.", "Habilita o comportamento de fetch/XHR quando a carga de trabalho exige.", "Traz a conclusão das promises de volta para o Dart."] },
    },
  },
  ka: {
    navLabel: "დოკუმენტაცია", title: "რეალური ზღვრული შემთხვევებიდან დაბადებული runtime-ების დოკუმენტაცია.", intro: "სამი ფოკუსირებული Flutter-პაკეტი: სრული SVG runtime, WOFF/WOFF2 შრიფტების ჩატვირთვის მექანიზმი და ერთი თანამედროვე JavaScript-ძრავი ყველა ნატიური პლატფორმისთვის. დაიწყეთ პრობლემით და შემდეგ დააკოპირეთ უმცირესი მომუშავე მაგალითი.", snapshot: "პაკეტების საჯარო მდგომარეობა · 17 აგვისტო 2026",
    labels: { problem: "რატომ არსებობს", install: "ინსტალაცია", quickStart: "სწრაფი დაწყება", capabilities: "რას ფარავს", architecture: "როგორ მუშაობს", api: "API-ს რუკა", useWhen: "გამოიყენეთ, როცა", limits: "გაითვალისწინეთ რელიზამდე", source: "წყარო და სრული README", pub: "პაკეტი pub.dev-ზე" },
    packages: {
      "full-svg-flutter": { tagline: "შეინარჩუნეთ SVG საწყის ფორმატად Flutter-ის შიგნით.", problem: "სტატიკური ხატულები SVG-ის მხოლოდ მცირე ნაწილია. პროდუქტის ასეტები შეიძლება SMIL-ს, CSS-ანიმაციას, path morphing-ს, ფილტრებს, ტექსტს ან ჩაშენებულ JavaScript-ფლეერს ეყრდნობოდეს. კონვერტაცია მეორე პირველწყაროს ამატებს; WebView — მეორე რენდერინგის სისტემას.", architecture: "პაკეტი SVG-დოკუმენტს საკუთარ, DOM-ის სტრუქტურის შემნახველ მოდელში პარსავს, ითვლის სტილისა და ანიმაციის მდგომარეობას და შემდეგ Flutter-ის მეშვეობით ხატავს. სტატიკური და ანიმირებული კონტენტი ერთსა და იმავე ძრავს იყენებს. JavaScript მხოლოდ მაშინ იტვირთება, როცა დოკუმენტში script ელემენტია.", useCases: ["იღებთ ანიმირებულ SVG-ს ან SVGator-ის ასეტებს და საწყისი ფორმატის შეცვლა არ შეგიძლიათ.", "გჭირდებათ ფილტრების, მასკების, ტექსტის ან ანიმაციის სიზუსტე, რომელიც სტატიკური ხატულების რენდერინგს სცდება.", "გსურთ flutter_svg-ის სტილის ნაცნობი API და მიგრაციის გზა WebView-ს გარეშე."], limits: ["ეს SVG runtime-ია და არა სრული ბრაუზერის DOM; foreignObject და ბრაუზერზე დამოკიდებული ფრეიმვორკები მის ფარგლებს გარეთაა.", "რთული ფილტრებისა და შერეული მიმართულების ტექსტის მქონე ასეტები რელიზამდე ვიზუალურად შეამოწმეთ."], apiDescriptions: ["მთავარი ვიჯეტი სტატიკური ან ანიმირებული ასეტისთვის — asset-იდან, ქსელიდან, სტრიქონიდან, ფაილიდან ან ბაიტებიდან.", "სტატიკური, flutter_svg-თან თავსებადი შესასვლელი წერტილი.", "დაკვრა, პაუზა, გადახვევა, სიჩქარისა და მიმართულების შეცვლა და SVG-ის ხედებს შორის გადართვა.", "SVG-ის Picture-ში ჩაწერა საკუთარი ხატვისთვის ან რასტერიზაციისთვის.", "ვიჯეტებს შორის გაზიარებული, კონფიგურირებადი ქეში დეკოდირებული წყაროებისთვის."] },
      woff2: { tagline: "ჩატვირთეთ ვებშრიფტების კონტეინერები Flutter-ის FontLoader-ით.", problem: "Flutter FontLoader-ის მეშვეობით TTF/OTF-ს იღებს, მაგრამ WOFF-სა და WOFF2-ს არ დეკოდირებს. შეკუმშული ვებშრიფტის ბაიტების პირდაპირ გადაცემას შეიძლება გამოტოვებული გლიფების კვადრატები მოჰყვეს — გამოსადეგი შეცდომის შეტყობინების გარეშე.", architecture: "დეკოდერი WOFF1/WOFF2-დან SFNT-ბაიტებს აღადგენს და შედეგს FontLoader-ში არეგისტრირებს. CSS-პარსერი და რეესტრი ფარავს SVG-ს, HTML-ს, EPUB-სა და კონტენტის სხვა ნაკადებს, რომლებიც @font-face წესებს შეიცავს.", useCases: ["SVG, EPUB, HTML-ექსპორტი ან დიზაინის ასეტი WOFF/WOFF2 შრიფტებს შეიცავს.", "გჭირდებათ შრიფტის ჩატვირთვა, რომელიც აპლიკაციის მუშაობისას ჩამოიტვირთა ან ჩვეულებრივ ასეტად ინახება.", "რენდერერს აშენებთ და დაბალ დონეზე WOFF-ბაიტების SFNT-ში გადაყვანა გჭირდებათ."], limits: ["WOFF2 TTC კოლექციები 0.1.0 ვერსიაში მხარდაჭერილი არ არის.", "Flutter Web-ში WOFF2-ს ბრაუზერი უკვე ამუშავებს; პაკეტი ნატიურ Flutter-პლატფორმებზეა გათვლილი."], apiDescriptions: ["პაკეტში ჩადებული WOFF/WOFF2 ასეტის დეკოდირება და რეგისტრაცია ერთი გამოძახებით.", "ქსელიდან, დისკიდან ან მეხსიერებიდან მიღებული შრიფტის ბაიტების რეგისტრაცია.", "ოჯახების, სისქეებისა და სტილების ჯგუფური რეგისტრაცია.", "@font-face წესების ამოღება, data URL-ებისა და ბრჭყალებში ჩასმული მნიშვნელობების ჩათვლით.", "კონტეინერის დაბალი დონის ამოცნობა და SFNT-ბაიტებში გადაყვანა."] },
      "quickjs-engine": { tagline: "გაუშვით ერთი და იგივე თანამედროვე JavaScript-ძრავი ყველა Flutter-პლატფორმაზე.", problem: "JavaScriptCore-ისა და ძველი QuickJS-ის შერეული კონფიგურაცია პლატფორმების მიხედვით სხვადასხვანაირად შეიძლება მოიქცეს — განსაკუთრებით რიცხვით ზღვრულ შემთხვევებში, Proxy-ში, იტერაციაში, Promise-ებსა და ანიმაციის runtime-ებში. ასეთი განსხვავებების გამეორება რთულია, ნდობა კი — კიდევ უფრო.", architecture: "პაკეტი QuickJS-NG 0.14.0-ს შეიცავს და ყველა მხარდაჭერილ ნატიურ პლატფორმას ერთი და იმავე ძრავსა და FFI-ხიდზე ატარებს. ნატიურ ბიბლიოთეკას Flutter-ის build-პროცესი აკომპილირებს ან პაკეტში დებს; შესრულება, შეტყობინებების გაცვლა და არასავალდებულო ვებსტილის დამხმარეები Dart-ის მხარესაა.", useCases: ["Flutter-პროდუქტს ჩაშენებული JavaScript-ის შესრულება სჭირდება პლატფორმებს შორის ერთგვაროვანი ქცევით.", "flutter_js-იდან მიგრირებთ და მის ნაცნობ შესასვლელ წერტილებს თანამედროვე ძრავზე გსურთ.", "გჭირდებათ მცირე სკრიპტული ფენა, გამოსახულებების ძრავი, ვალიდატორი ან SVG-ფლეერი WebView-ს გარეშე."], limits: ["შესრულებულ კოდს განზრახ დადგენილ ნდობის საზღვრად მოეპყარით და მას მხოლოდ ის ჰოსტის შესაძლებლობები გაუხსენით, რომლებიც ნამდვილად სჭირდება.", "დესკტოპზე unit tests-ს შეიძლება ნატიური ბიბლიოთეკის აწყობა ან მასზე მითითება დასჭირდეს ჩვეულებრივი plugin-ის build-პროცესის გარეთ."], apiDescriptions: ["პლატფორმებს შორის ერთგვაროვანი QuickJS runtime-ის შექმნა.", "JavaScript-ის შესრულება და შედეგის დათვალიერება.", "სახელდებული Dart-ფუნქციების (callback) გახსნა JavaScript-ისთვის.", "fetch/XHR ქცევის ჩართვა, როცა ამოცანა ამას მოითხოვს.", "Promise-ის დასრულების Dart-ში დაბრუნება."] },
    },
  },
  ar: {
    navLabel: "الوثائق", title: "وثائق حزم runtime وُلدت من حالات حدّية حقيقية.", intro: "ثلاث حزم Flutter مركّزة: runtime كامل لـ SVG، ومسار خطوط WOFF/WOFF2، ومحرك JavaScript حديث واحد عبر المنصات الأصلية. ابدأ من المشكلة، ثم انسخ أصغر مثال يعمل.", snapshot: "لقطة عامة للحزم · 17 أغسطس 2026",
    labels: { problem: "لماذا وُجدت", install: "التثبيت", quickStart: "بداية سريعة", capabilities: "التغطية", architecture: "كيف تعمل", api: "خريطة API", useWhen: "استخدمها عندما", limits: "اعرف قبل الإصدار", source: "المصدر و README الكامل", pub: "الحزمة على pub.dev" },
    packages: {
      "full-svg-flutter": { tagline: "أبقِ SVG صيغةَ المصدر داخل Flutter.", problem: "الأيقونات الثابتة ليست سوى جزء صغير من SVG. قد تعتمد أصول المنتج على SMIL أو حركة CSS أو path morphing أو الفلاتر أو النصوص أو مشغّل JavaScript مضمّن. تحويلها يضيف مصدر حقيقة ثانياً، واستخدام WebView يضيف نظام عرض ثانياً.", architecture: "تحلّل الحزمة مستند SVG إلى نموذج خاص بها يحافظ على DOM، وتحسب الأنماط وحالة الحركة، ثم ترسم عبر Flutter. يتشارك المحتوى الثابت والمتحرك المحرك نفسه، ولا يبدأ JavaScript إلا عند وجود عنصر script.", useCases: ["تستقبل ملفات SVG متحركة أو أصول SVGator ولا تستطيع تغيير صيغة المصدر.", "تحتاج إلى دقة في الفلاتر أو الأقنعة أو النصوص أو الحركة تتجاوز عرض الأيقونات الثابتة.", "تريد API مألوفة على غرار flutter_svg ومسار ترحيل من دون WebView."], limits: ["هي runtime لـ SVG، لا نسخة كاملة من DOM المتصفح؛ foreignObject والأطر المعتمدة على المتصفح خارج النطاق.", "تحقّق بصرياً من الأصول ذات الفلاتر المعقدة أو النصوص مختلطة الاتجاه قبل الإصدار."], apiDescriptions: ["الـ widget الرئيسي للأصول الثابتة أو المتحركة من asset أو network أو string أو file أو bytes.", "نقطة دخول ثابتة متوافقة مع flutter_svg.", "التشغيل والإيقاف المؤقت و seek وتغيير السرعة أو الاتجاه والتبديل بين SVG views.", "تسجيل SVG في Picture للرسم المخصص أو التحويل إلى صورة نقطية.", "ذاكرة تخزين مؤقت قابلة للضبط للمصادر المفكوكة، مشتركة بين الـ widgets."] },
      woff2: { tagline: "حمّل حاويات خطوط الويب عبر FontLoader في Flutter.", problem: "يقبل Flutter ملفات TTF/OTF عبر FontLoader، لكنه لا يفكّ ترميز WOFF أو WOFF2. وتمرير bytes خط الويب المضغوط مباشرةً قد ينتج مربعات بدل الحروف من دون رسالة خطأ مفيدة.", architecture: "يعيد الـ decoder بناء bytes بصيغة SFNT من WOFF1/WOFF2، ثم يسجّل النتيجة عبر FontLoader. ويغطي محلّل CSS وسجلّ الخطوط ملفات SVG و HTML و EPUB وغيرها من المحتوى الذي يحمل قواعد @font-face.", useCases: ["يضمّن ملف SVG أو EPUB أو تصدير HTML أو أصل تصميمي خطوطاً بصيغة WOFF/WOFF2.", "تحتاج إلى تحميل خط نُزّل وقت التشغيل أو خُزّن كـ asset عادي.", "تبني renderer وتحتاج إلى تحويل bytes بصيغة WOFF إلى SFNT على مستوى منخفض."], limits: ["مجموعات WOFF2 TTC غير مدعومة في الإصدار 0.1.0.", "Flutter Web يتعامل مع WOFF2 في المتصفح أصلاً؛ الحزمة تستهدف منصات Flutter الأصلية."], apiDescriptions: ["فكّ ترميز asset بصيغة WOFF/WOFF2 وتسجيله بنداء واحد.", "تسجيل bytes خط جُلبت من الشبكة أو القرص أو الذاكرة.", "تسجيل دفعي للعائلات والأوزان والأنماط.", "استخراج قواعد @font-face بما فيها data URLs والقيم المقتبسة.", "كشف نوع الحاوية وتحويلها إلى bytes بصيغة SFNT على مستوى منخفض."] },
      "quickjs-engine": { tagline: "شغّل محرك JavaScript الحديث نفسه على كل منصات Flutter.", problem: "قد يتصرف مزيج JavaScriptCore و QuickJS القديم بشكل مختلف من منصة إلى أخرى، خصوصاً في الحالات الحدّية العددية و Proxy والتكرار و promises ومكتبات تشغيل الحركة. هذا التباعد يصعب إعادة إنتاجه، والوثوق به أصعب.", architecture: "تضمّ الحزمة QuickJS-NG 0.14.0 وتمرّر كل منصة أصلية مدعومة عبر المحرك نفسه وجسر FFI نفسه. يتولى نظام البناء في Flutter تجميع المكتبة الأصلية أو تضمينها، بينما يملك Dart التقييم والرسائل والمساعدات الاختيارية على نمط الويب.", useCases: ["يحتاج منتج Flutter إلى تقييم JavaScript مضمّن بسلوك متسق عبر المنصات.", "تنتقل من flutter_js وتريد نقاط الدخول المألوفة نفسها على محرك حديث.", "تحتاج إلى طبقة scripting صغيرة أو محرك تعبيرات أو مدقّق أو مشغّل SVG من دون WebView."], limits: ["تعامل مع الكود المقيَّم بوصفه حدّ ثقة متعمّداً، ولا تعرض له من قدرات المضيف إلا ما يحتاج إليه.", "قد تتطلب اختبارات الوحدة على سطح المكتب بناء المكتبة الأصلية أو الإشارة إلى مسارها خارج مسار بناء الـ plugin المعتاد."], apiDescriptions: ["إنشاء runtime لـ QuickJS بسلوك متسق عبر المنصات.", "تقييم JavaScript وفحص النتيجة.", "إتاحة دوال Dart مسمّاة لاستدعائها من JavaScript.", "تفعيل سلوك fetch/XHR عندما يتطلبه العمل.", "إعادة اكتمال Promise إلى Dart."] },
    },
  },
};

export function getDocsCopy(locale: Locale): DocsCopy {
  const text = docsByLocale[locale];
  return {
    ...text,
    seo: {
      title: `${text.navLabel} · full_svg_flutter, woff2 & quickjs_engine`,
      description: text.intro,
    },
    packages: packageSlugs.map((slug) => ({ ...meta[slug], ...text.packages[slug] })),
  };
}
