import type { SiteCopy } from "./types";

export const en: SiteCopy = {
  localeName: "English",
  seo: {
    home: { title: "Engineering Manager & Mobile Engineer", description: "Denis Nadey leads mobile teams, architects Flutter platforms, improves delivery systems, and takes complex products into production." },
    work: { title: "Mobile Engineering Work", description: "Selected mobile delivery, platform modernization, fintech, and geospatial engineering work by Denis Nadey." },
    "open-source": { title: "full_svg_flutter Open Source", description: "The engineering story behind full_svg_flutter, a self-contained static and animated SVG runtime for Flutter." },
    services: { title: "Flutter & Mobile Engineering Services", description: "Mobile product delivery, Flutter architecture, CI/CD, release engineering, technical audits, and fractional leadership." },
    experience: { title: "Engineering Leadership Experience", description: "Career progression from hands-on software engineering to multi-team mobile engineering leadership." },
    about: { title: "About Denis Nadey", description: "Engineering Manager and hands-on mobile engineer focused on architecture, delivery, and production responsibility." },
    contact: { title: "Contact Denis Nadey", description: "Discuss a mobile product, Flutter architecture, delivery challenge, consulting engagement, or engineering leadership role." },
  },
  nav: { home: "Home", work: "Work", "open-source": "Open source", services: "Services", experience: "Experience", about: "About", contact: "Contact" },
  common: {
    role: "Engineering Manager · Web, Mobile & AI Product Engineer",
    location: "Tbilisi, Georgia",
    availability: "Europe relocation / remote",
    menu: "Menu",
    language: "Language",
    close: "Close",
    skip: "Skip to content",
    selectedEvidence: "Selected evidence · current CV",
    discuss: "Discuss a project",
    exploreWork: "Explore selected work",
    viewExperience: "View full experience",
    downloadCv: "Download CV",
    viewOpenSource: "View open source",
    viewServices: "View services",
    readArticle: "Read the technical breakdown",
    visitGithub: "View on GitHub",
    visitPub: "View on pub.dev",
    finalTitle: "Need to ship, modernize, or stabilize a mobile product?",
    finalBody: "Tell me what the product needs to do, where delivery is stuck, and what a good outcome looks like.",
    contactDenis: "Contact Denis",
    external: "opens in a new tab",
    current: "Current page",
  },
  home: {
    titleLead: "I build digital products—",
    titleEmphasis: "from web and mobile to AI-enabled delivery.",
    intro: "Eleven-plus years across web, mobile, and engineering leadership: 100+ web projects, production Flutter platforms, multi-team delivery, and AI used as a serious engineering tool—not a badge.",
    proof: [
      { value: "100+", label: "web products delivered" },
      { value: "15", label: "engineers led" },
      { value: "80+", label: "production releases" },
      { value: "10", label: "apps on a shared Flutter core" },
      { value: "5 mo", label: "greenfield to production" },
    ],
    mandateLabel: "The mandate",
    mandateTitle: "Technical depth. Organisational leverage. One point of ownership.",
    mandateBody: "Denis moved from hands-on delivery into leadership without leaving architecture, code review, release governance, and production escalation behind. The result is a manager who can discuss the roadmap with Product, the failure mode with an engineer, and the release decision with Compliance.",
    workLabel: "Selected work",
    workTitle: "Complex products, made deliverable.",
    workIntro: "The strongest work is not a logo wall. It is the system behind a launch: ownership, architecture, release controls, and the judgment to simplify at the right moment.",
    servicesLabel: "Work with me",
    servicesTitle: "Bring in senior mobile ownership where it changes the outcome.",
    servicesIntro: "For a product that needs to be built, rescued, modernized, audited, or prepared for production—and for teams that need technical leadership without losing hands-on depth.",
    openLabel: "Open-source engineering",
    openTitle: "SVG should stay SVG.",
    openIntro: "full_svg_flutter is a self-contained renderer for static and animated SVG in Flutter: SMIL, CSS keyframes, path morphing, filters, masks, text, JavaScript-driven SVGator assets, and playback control—without converting the asset to another format.",
    careerLabel: "Career progression",
    careerTitle: "From implementation to portfolio responsibility.",
    careerIntro: "Eleven-plus years across web, fintech, marketplaces, mobile platforms, regulated products, and engineering leadership—growing scope while staying technically active.",
    principlesLabel: "Working model",
    principlesTitle: "Make constraints visible. Keep ownership explicit.",
    principles: [
      "Start with the business constraint, not the framework.",
      "Make architecture proportional to the product and team.",
      "Surface delivery and release risk early.",
      "Automate repeated release work and document the exception path.",
      "Communicate trade-offs in language the decision-maker can use.",
      "Leave the platform easier to operate than it was found.",
    ],
  },
  work: {
    title: "Work that connects architecture to production.",
    intro: "Selected programs and products where Denis held clear responsibility for delivery, platform quality, or a technically difficult part of the system. Team outcomes are presented as team outcomes.",
    labels: { context: "Context", responsibility: "Responsibility", approach: "Approach", outcome: "Outcome", stack: "Selected stack" },
    nda: "The case studies intentionally omit private architecture, credentials, unreleased product detail, and internal commercial metrics.",
    cases: [
      {
        label: "01 · Multi-market delivery",
        title: "Three regulated launches across three parallel roadmaps",
        summary: "Portfolio leadership for Zinx Romania, Betoro Denmark, and YoYo Sweden, with YoYo reaching production in approximately five months.",
        context: "Three concurrent mobile teams were delivering for different regulated markets while staffing, priorities, dependencies, and compliance requirements continued to move.",
        responsibility: "Led the 15-engineer portfolio, coached two Team Leads, retained accountability for delivery and team health, and aligned Product, Design, QA, Backend, Payments, and Compliance.",
        approach: "Introduced one operating model for estimation, capacity, dependency mapping, milestones, and release gates. Kept technical escalation close enough to resolve signing, native SDK, WebView bridge, store, and incident risks.",
        outcome: "All three products reached their regulated go-live windows on schedule. YoYo moved from initial implementation to production in about five months.",
        stack: "Flutter, Dart, Kotlin, Swift, REST/WebSockets, Firebase, GitLab CI/CD, Codemagic, Fastlane, Sentry/Crashlytics",
      },
      {
        label: "02 · Platform modernization",
        title: "A shared Flutter core and release system for ten applications",
        summary: "Modernized the platform underneath a multi-brand portfolio while active products continued to ship.",
        context: "Ten applications shared a Flutter core and brand-specific configuration. Version divergence and repeated release setup increased maintenance and production risk.",
        responsibility: "Led the shared core migration from Flutter 3.19 to 3.38.1 and standardized reusable GitLab CI/CD and Codemagic workflows across product teams.",
        approach: "Consolidated platform configuration, release checklists, review standards, automated testing, observability, and incident follow-up while delegating day-to-day team execution through Team Leads.",
        outcome: "Reduced platform divergence and repeated setup work, improved release ownership, and created a consistent production-readiness baseline across the portfolio.",
        stack: "Flutter 3.19-3.38.1, GitLab CI/CD, Codemagic, Fastlane, automated testing, Sentry, Crashlytics",
      },
      {
        label: "03 · Fintech operations",
        title: "A 100+ screen operations platform built from the ground up",
        summary: "Hands-on Flutter engineering for a VPN-secured operations product spanning KYC, AML, cards, IBAN, transactions, permissions, and support workflows.",
        context: "Internal finance operations required a dense, reliable interface with many business states, access rules, real-time updates, and compliance-sensitive workflows.",
        responsibility: "Served as the sole Flutter developer for the platform described in the current CV, while working within the wider engineering organization.",
        approach: "Created reusable tables, forms, permissions, access-control, and real-time components using a modular architecture and a test-focused delivery model.",
        outcome: "Delivered more than 100 production screens in 18 months with a shared component model that supported consistent implementation across operational domains.",
        stack: "Flutter Web/Desktop, Dart, Clean Architecture, BLoC, get_it, REST, WebSockets, TDD, unit and golden tests",
      },
      {
        label: "04 · Geospatial commerce",
        title: "House-level delivery matching without a paid geocoder",
        summary: "A custom OpenStreetMap-based address pipeline for a farm-food marketplace serving 150,000 registered customers.",
        context: "Delivery accuracy depended on normalizing inconsistent addresses and matching them at house level without relying on a paid external geocoding service.",
        responsibility: "Personally designed and delivered the geocoding, address-normalization, and matching pipeline alongside user-facing catalogue, cart, checkout, delivery, and subscription work.",
        approach: "Combined OpenStreetMap data with product-specific normalization and geospatial rules, then integrated the output into operational and customer delivery flows.",
        outcome: "Improved delivery-address accuracy and operational reliability for a product serving 150,000 registered customers.",
        stack: "Flutter, Dart, OpenStreetMap, Firebase, REST, Clean Architecture, TDD, native Android/iOS integrations",
      },
    ],
  },
  openSource: {
    title: "A browser-engine mindset, brought to Flutter SVG.",
    intro: "Denis created and maintains full_svg_flutter, a self-contained rendering runtime for teams that need existing SVG assets to remain SVG inside Flutter.",
    versionLabel: "Public snapshot · 17 Aug 2026",
    proof: [
      { value: "1.4.2", label: "current release" },
      { value: "140", label: "pub points" },
      { value: "12", label: "public versions" },
      { value: "MIT", label: "open-source license" },
    ],
    problemTitle: "The asset works in a browser. In Flutter, the animation disappears.",
    problemBody: "Many pipelines solve that gap by converting the asset to Lottie, Rive, GIF, WebP, or custom Flutter animation code. Those can be good tools—but conversion is the wrong cost when SVG is already the source of truth.",
    engineTitle: "One DOM-preserving engine for static and animated SVG",
    engineBody: "The package parses the document model, CSS, timing, filters, text, and interaction state, then paints inside Flutter. JavaScript-driven SVGator exports run through a bundled QuickJS engine; SVGs without scripts pay no JavaScript startup cost.",
    coverageTitle: "What the runtime covers",
    coverage: ["Static geometry, gradients, patterns, clipping, and masks", "SMIL and CSS @keyframes animation", "Path morphing, motion paths, and playback control", "All 17 SVG filter primitives", "Rich text, textPath, bidi/RTL, and accessibility metadata", "Inline JavaScript and SVGator exports", "flutter_svg-compatible static API migration", "Android, iOS, macOS, Windows, and Linux"],
    migrationTitle: "A practical migration path",
    migrationBody: "Existing static SvgPicture usage can often move with an import change. FSvgPicture auto-detects animation markers, while AnimatedSvgController adds pause, seek, rate, direction, and SVG view control when the product needs it.",
    demoTitle: "One SVG file. Native browser animation here; native Flutter rendering in the package.",
    demoBody: "This page displays the project's own animated SVG asset in the browser. In a Flutter application, full_svg_flutter renders the same source format inside Flutter without a WebView or conversion step.",
    relatedTitle: "Related package: woff2",
    relatedBody: "Building a serious SVG runtime exposed another edge case: fonts embedded as WOFF or WOFF2. Denis released an early-stage pure-Dart decoder and FontLoader wrapper so Flutter pipelines can register those font formats without app-specific native plugin code.",
    writingTitle: "Technical writing",
    articleTitle: "The problem: Flutter SVG support is usually static",
    articleDescription: "A practical explanation of the rendering gap, common workarounds, playback control, performance trade-offs, and when keeping SVG as SVG is the right choice.",
  },
  services: {
    title: "Senior mobile ownership, shaped to the problem.",
    intro: "Engagements for companies that need a product shipped, a mobile platform made safer to change, or a team given clearer technical and delivery leadership.",
    labels: { signal: "When this helps", action: "What Denis does", format: "Typical engagement" },
    items: [
      { title: "Mobile product delivery & rescue", signal: "A roadmap is slipping, ownership is fragmented, or a critical release has too many unknowns.", action: "Clarify constraints, map dependencies, reset milestones, take technical escalation ownership, and establish a production-ready delivery model.", format: "Delivery assessment followed by hands-on interim leadership or a focused recovery program." },
      { title: "Flutter architecture & modernization", signal: "The app is difficult to change, upgrades keep breaking delivery, or brand/product variants are diverging.", action: "Review boundaries, state management, dependencies, native integration, testing, and migration risk; then sequence modernization around active delivery.", format: "Architecture review, prioritized plan, and optional implementation leadership." },
      { title: "Native integration & release engineering", signal: "Signing, stores, SDKs, deep links, notifications, WebViews, or platform channels are blocking a reliable release.", action: "Trace the platform boundary, fix integration and lifecycle issues, strengthen the release path, and document operational ownership.", format: "Focused technical engagement around a defined integration or release problem." },
      { title: "Mobile CI/CD & production readiness", signal: "Pipelines are rebuilt per app, releases depend on manual knowledge, or incidents have unclear owners.", action: "Standardize pipelines, signing and environment flow, release gates, checks, observability, and incident follow-up without over-engineering the platform.", format: "Audit plus implementation sprint, or platform enablement across several teams." },
      { title: "Fractional mobile technical leadership", signal: "A company needs senior mobile direction before—or instead of—hiring a full-time leader.", action: "Own architecture decisions, technical planning, hiring support, Team Lead coaching, and delivery risk while remaining available for hands-on escalation.", format: "Part-time recurring mandate with explicit outcomes and decision rights." },
      { title: "Engineering delivery assessment", signal: "Leadership needs an independent view of why mobile delivery feels unpredictable.", action: "Examine roadmap shape, team interfaces, technical risk, release governance, quality signals, and ownership; return a prioritized, defensible action plan.", format: "Short diagnostic engagement with interviews, artefact review, and an executive/technical readout." },
    ],
    boundaryTitle: "Advice stays proportional to the product.",
    boundaryBody: "An audit is not a pretext for a rewrite. Recommendations distinguish urgent production risk from maintainability work, explain trade-offs, and identify what should remain unchanged.",
  },
  experience: {
    title: "Increasing scope, without leaving engineering behind.",
    intro: "A career narrative from web product delivery to senior Flutter engineering, platform ownership, Team Lead responsibility, and multi-team mobile leadership.",
    roles: [
      { period: "Jan 2026 — Jul 2026", company: "BrainRocket · Limassol, Cyprus", title: "Engineering Manager, Mobile", summary: "Led three concurrent teams and 15 engineers across regulated iGaming markets, with two Team Leads as direct reports.", evidence: "Three on-schedule market launches; one greenfield product to production in about five months; shared core across ten apps; portfolio-level release and incident accountability." },
      { period: "Dec 2024 — Dec 2025", company: "BrainRocket · Limassol, Cyprus", title: "Flutter Team Lead", summary: "Combined team leadership with modular architecture, code review, native escalation, and regulated release ownership.", evidence: "Swiper Ontario and other releases; Clean Architecture with BLoC/Riverpod; Kotlin/Swift platform channels; recovery after an external team exit." },
      { period: "Jul 2023 — Dec 2024", company: "CFP Technology (CFPS) · Remote", title: "Senior Flutter Developer", summary: "Built a production VPN-secured Flutter operations platform covering fintech and compliance workflows.", evidence: "100+ screens in 18 months; reusable forms, tables, permissions, access control, and real-time components." },
      { period: "Jan 2022 — Jul 2023", company: "Esh Derevenskoye · Remote", title: "Senior Flutter Developer", summary: "Built marketplace and recurring-order journeys for a premium farm-food delivery product.", evidence: "Designed a custom OpenStreetMap geocoding and house-level matching pipeline for a product serving 150,000 registered customers." },
      { period: "Jan 2021 — Jan 2022", company: "Rosselkhozbank · Moscow", title: "Flutter Developer", summary: "Developed marketplace, B2B, P2P, and financial-service flows for agricultural products.", evidence: "Introduced CI/CD, Docker Compose environments, and golden, widget, and integration tests." },
      { period: "2015 — 2020", company: "Novorossiysk", title: "Web engineering, studio leadership & early Flutter", summary: "Founded a small studio, delivered more than 100 web projects, and later led AngularDart/Flutter implementation for Edakratia.", evidence: "Two-to-four-person studio; payment and lead-generation systems; food-delivery product with 10,000+ registered users in its first year." },
    ],
    educationTitle: "Education",
    educationBody: "42 Paris, Software Engineering Program (2022-present, part-time); School 21 (2020-2022, transferred to 42 Paris); Novorossiysk College of Construction and Economics, Applied Informatics / Software Engineering Technician (2015-2019).",
    languagesTitle: "Languages",
    languagesBody: "Russian — native. English — B2+, used daily for stakeholder communication, technical documentation, interviews, and cross-functional delivery. Latvian — A2.",
  },
  about: {
    title: "A manager who still wants to understand the failure mode.",
    intro: "Denis is an Engineering Manager and hands-on mobile engineer with 11+ years in software engineering and 6+ years in Flutter.",
    paragraphs: [
      "His career began with web products and a small delivery studio, moved through banking, marketplaces, fintech operations, and senior Flutter roles, then expanded into Team Lead and multi-team Engineering Manager responsibility.",
      "The common thread is ownership across the boundary: product constraints, application architecture, native Android/iOS integration, CI/CD, store release, observability, production debugging, and the team system required to make those parts work together.",
      "Leadership did not replace engineering. Denis remains most useful where a team needs someone who can make a portfolio decision, coach a Team Lead, review the architecture, and join the technical escalation when the release is at risk.",
    ],
    usefulTitle: "Problems worth a conversation",
    usefulItems: ["A mobile product needs a credible path from roadmap to production", "A Flutter platform has accumulated divergence or upgrade risk", "Native SDKs, signing, WebViews, or release tooling are blocking delivery", "Several teams need one operating model without losing autonomy", "A company needs fractional mobile leadership or an independent technical assessment", "An existing SVG-heavy Flutter pipeline needs capabilities beyond static rendering"],
    nowTitle: "Location & availability",
    nowBody: "Based in Tbilisi, Georgia. Open to remote work and European relocation. Relevant conversations include Engineering Manager, Mobile Engineering Manager, Mobile Tech Lead, Lead Flutter Engineer, architecture consulting, and focused delivery engagements.",
  },
  contact: {
    title: "Bring the real mobile problem.",
    intro: "A release that will not stabilize, an architecture that slows every change, a team that needs clearer ownership, or a product that needs a credible path to production.",
    directTitle: "Direct contact",
    response: "Email is preferred. LinkedIn, GitHub, and Telegram are also available.",
    formTitle: "Prepare a project enquiry",
    formIntro: "The form validates the essentials, then opens a structured draft in your email app. Nothing is uploaded or tracked.",
    name: "Name",
    email: "Email",
    company: "Company",
    need: "What do you need help with?",
    budget: "Budget range",
    timeline: "Timeline",
    optional: "optional",
    send: "Prepare email",
    prepared: "Your email draft is ready. If it did not open, use the direct email address on this page.",
    privacy: "Private by design: this site does not store or transmit form data. Submitting opens your own email application.",
    errors: { name: "Please enter your name.", email: "Enter a valid email address.", need: "Add a short description of the problem." },
    budgetOptions: ["Not specified", "Under €10k", "€10k–€25k", "€25k–€50k", "€50k+"],
    timelineOptions: ["Not specified", "Urgent / current release", "Within 1 month", "1–3 months", "3+ months"],
  },
};
