import type { SiteCopy } from "./types";

export const fr: SiteCopy = {
  localeName: "Français",
  seo: {
    home: { title: "Engineering Manager & ingénieur mobile", description: "Denis Nadey dirige des équipes mobiles, conçoit des plateformes Flutter et mène des produits complexes jusqu'en production." },
    work: { title: "Réalisations en ingénierie mobile", description: "Livraison mobile, modernisation de plateforme, fintech et ingénierie géospatiale." },
    "open-source": { title: "Open source : full_svg_flutter", description: "L'histoire technique de full_svg_flutter, moteur SVG autonome pour Flutter." },
    services: { title: "Conseil Flutter et mobile", description: "Delivery, architecture Flutter, CI/CD, release engineering, audits et leadership technique." },
    experience: { title: "Expérience en leadership technique", description: "De l'ingénierie hands-on à la direction de plusieurs équipes mobiles." },
    about: { title: "À propos de Denis Nadey", description: "Engineering Manager et ingénieur mobile hands-on, entre architecture, delivery et production." },
    contact: { title: "Contacter Denis Nadey", description: "Échangeons sur un produit mobile, une architecture Flutter, un problème de delivery ou une mission de leadership." },
  },
  nav: { home: "Accueil", work: "Réalisations", "open-source": "Open source", services: "Services", experience: "Parcours", about: "À propos", contact: "Contact" },
  common: { role: "Engineering Manager & ingénieur mobile hands-on", location: "Tbilissi, Géorgie", availability: "Mobilité Europe / remote", menu: "Menu", language: "Langue", close: "Fermer", skip: "Aller au contenu", selectedEvidence: "Repères vérifiés · CV actuel", discuss: "Discuter d'un projet", exploreWork: "Voir les réalisations", downloadCv: "Télécharger le CV", viewOpenSource: "Voir l'open source", viewServices: "Voir les services", readArticle: "Lire l'analyse technique", visitGithub: "Voir sur GitHub", visitPub: "Voir sur pub.dev", finalTitle: "Un produit mobile à livrer, moderniser ou stabiliser ?", finalBody: "Décrivez l'objectif du produit, le point de blocage et le résultat attendu.", contactDenis: "Contacter Denis", external: "s'ouvre dans un nouvel onglet", current: "Page actuelle" },
  home: {
    titleLead: "Je construis des produits mobiles—", titleEmphasis: "et les systèmes d'ingénierie qui les rendent livrables.", intro: "Leadership, architecture Flutter, delivery multi-équipes, CI/CD et responsabilité de production—au plus près du code.",
    proof: [{ value: "3", label: "équipes produit en parallèle" }, { value: "15", label: "ingénieurs encadrés" }, { value: "80+", label: "releases en production" }, { value: "10", label: "apps sur un cœur Flutter commun" }, { value: "5 mois", label: "du greenfield à la production" }],
    mandateLabel: "Le mandat", mandateTitle: "Profondeur technique. Levier organisationnel. Responsabilité claire.", mandateBody: "Denis a évolué vers le management sans quitter l'architecture, la code review, la gouvernance des releases ni les escalades de production. Il relie roadmap, diagnostic technique et décision de mise en ligne.",
    workLabel: "Réalisations", workTitle: "Rendre les produits complexes livrables.", workIntro: "La valeur n'est pas une galerie de logos, mais le système derrière le lancement : ownership, architecture, contrôles de release et arbitrages proportionnés.",
    servicesLabel: "Travailler ensemble", servicesTitle: "Apporter un ownership mobile senior là où il change l'issue.", servicesIntro: "Pour construire, reprendre, moderniser, auditer ou préparer un produit à la production—et pour des équipes qui ont besoin de leadership sans perdre la profondeur hands-on.",
    openLabel: "Ingénierie open source", openTitle: "Un SVG doit rester un SVG.", openIntro: "full_svg_flutter rend les SVG statiques et animés dans Flutter : SMIL, CSS keyframes, morphing, filtres, masques, texte, JavaScript SVGator et contrôle de lecture—sans conversion.",
    careerLabel: "Progression", careerTitle: "De l'implémentation à la responsabilité d'un portefeuille.", careerIntro: "Plus de onze ans entre web, fintech, marketplaces, plateformes mobiles, produits régulés et leadership, avec un périmètre croissant et une implication technique constante.",
    principlesLabel: "Mode de travail", principlesTitle: "Rendre les contraintes visibles. Clarifier l'ownership.", principles: ["Partir de la contrainte métier, pas du framework.", "Dimensionner l'architecture au produit et à l'équipe.", "Exposer tôt les risques de delivery et de release.", "Automatiser le travail répétitif de mise en production.", "Expliquer les arbitrages dans un langage actionnable.", "Laisser une plateforme plus facile à exploiter."],
  },
  work: {
    title: "Relier l'architecture à la production.", intro: "Des programmes où Denis portait une responsabilité nette sur le delivery, la plateforme ou une difficulté technique. Les résultats collectifs restent attribués à l'équipe.", labels: { context: "Contexte", responsibility: "Responsabilité", approach: "Approche", outcome: "Résultat", stack: "Stack" }, nda: "Les architectures privées, secrets, détails non publics et métriques commerciales internes sont volontairement exclus.",
    cases: [
      { label: "01 · Delivery multi-marchés", title: "Trois lancements régulés sur trois roadmaps", summary: "Pilotage de Zinx Romania, Betoro Denmark et YoYo Sweden ; YoYo en production en environ cinq mois.", context: "Trois équipes, des marchés et exigences de conformité différents, avec des priorités et dépendances mouvantes.", responsibility: "15 ingénieurs, deux Team Leads et coordination Product, Design, QA, Backend, Payments et Compliance.", approach: "Un modèle commun d'estimation, capacité, dépendances, jalons et release gates, avec prise en charge des escalades techniques.", outcome: "Trois fenêtres de go-live tenues ; YoYo livré de l'implémentation initiale à la production en cinq mois environ.", stack: "Flutter, Dart, Kotlin, Swift, REST/WebSockets, GitLab CI/CD, Codemagic, Fastlane, Sentry/Crashlytics" },
      { label: "02 · Modernisation de plateforme", title: "Un cœur Flutter et un système de release pour dix apps", summary: "Moderniser une plateforme multi-marques sans arrêter les releases.", context: "Dix apps partageaient un cœur commun ; la divergence et les setups répétés augmentaient le risque.", responsibility: "Migration de Flutter 3.19 à 3.38.1 et standardisation GitLab CI/CD / Codemagic.", approach: "Configuration, checklists, review, tests, observabilité et suivi d'incidents communs.", outcome: "Moins de divergence, moins de travail répété et un socle de production cohérent.", stack: "Flutter 3.19-3.38.1, GitLab CI/CD, Codemagic, Fastlane, tests, Sentry, Crashlytics" },
      { label: "03 · Opérations fintech", title: "Une plateforme opérationnelle de plus de 100 écrans", summary: "KYC, AML, cartes, IBAN, transactions, droits et support dans Flutter.", context: "Des workflows financiers denses, sensibles à la conformité et riches en états temps réel.", responsibility: "Seul développeur Flutter de la plateforme selon le CV actuel, au sein d'une organisation plus large.", approach: "Tables, formulaires, permissions et composants temps réel réutilisables, avec architecture modulaire et tests.", outcome: "Plus de 100 écrans de production en 18 mois et un modèle de composants partagé.", stack: "Flutter Web/Desktop, Dart, Clean Architecture, BLoC, REST, WebSockets, TDD" },
      { label: "04 · Commerce géospatial", title: "Correspondance à l'adresse sans géocodeur payant", summary: "Pipeline OpenStreetMap pour un marketplace de 150 000 clients inscrits.", context: "Normaliser des adresses hétérogènes jusqu'au niveau du bâtiment sans service payant.", responsibility: "Conception et livraison personnelles du géocodage, de la normalisation et du matching.", approach: "Données OpenStreetMap, règles produit et intégration dans les parcours client et opérationnels.", outcome: "Meilleure précision des adresses et fiabilité opérationnelle.", stack: "Flutter, Dart, OpenStreetMap, Firebase, REST, Clean Architecture, TDD, Android/iOS" },
    ],
  },
  openSource: {
    title: "Une approche de moteur de navigateur pour le SVG Flutter.", intro: "Denis développe full_svg_flutter, runtime autonome pour conserver les assets SVG tels quels dans Flutter.", versionLabel: "État public · 17 août 2026", proof: [{ value: "1.4.2", label: "version actuelle" }, { value: "140", label: "pub points" }, { value: "12", label: "versions publiques" }, { value: "MIT", label: "licence" }], problemTitle: "L'asset fonctionne dans le navigateur. Dans Flutter, l'animation disparaît.", problemBody: "Lottie, Rive, GIF, WebP ou une animation maison peuvent convenir, mais la conversion est un coût inutile quand le SVG est déjà la source de vérité.", engineTitle: "Un moteur qui préserve le DOM pour le statique et l'animé", engineBody: "Le package traite document, CSS, timing, filtres, texte et interactions puis peint dans Flutter. Les scripts SVGator utilisent QuickJS à la demande.", coverageTitle: "Couverture", coverage: ["Géométrie, dégradés, patterns, clipping et masques", "SMIL et CSS @keyframes", "Morphing, motion paths et contrôle de lecture", "Les 17 primitives de filtre SVG", "Texte riche, textPath, bidi/RTL et accessibilité", "JavaScript inline et SVGator", "Migration compatible avec flutter_svg", "Android, iOS, macOS, Windows et Linux"], migrationTitle: "Une migration pragmatique", migrationBody: "SvgPicture peut souvent rester après un changement d'import. FSvgPicture détecte l'animation et AnimatedSvgController ajoute pause, seek, vitesse, direction et SVG views.", demoTitle: "Un fichier SVG. Ici dans le navigateur, nativement dans Flutter avec le package.", demoBody: "Cette page affiche un asset animé du projet. full_svg_flutter rend la même source dans Flutter, sans WebView ni conversion.", relatedTitle: "Package associé : woff2", relatedBody: "Pour les polices WOFF/WOFF2 intégrées, Denis a publié un décodeur pure Dart avec wrapper FontLoader, sans plugin natif spécifique à l'app.", writingTitle: "Écriture technique", articleTitle: "Le problème : le support SVG de Flutter est généralement statique", articleDescription: "L'écart de rendu, les alternatives, le contrôle, les compromis de performance et le bon usage d'un SVG source.",
  },
  services: {
    title: "Un ownership mobile senior adapté au problème.", intro: "Pour livrer un produit, rendre une plateforme plus sûre à modifier ou donner à l'équipe un leadership technique clair.", labels: { signal: "Quand c'est utile", action: "Ce que Denis fait", format: "Format" },
    items: [
      { title: "Delivery et reprise de produit mobile", signal: "Roadmap en retard, ownership fragmenté ou release critique incertaine.", action: "Clarifier contraintes, dépendances et jalons ; reprendre les escalades et le chemin de production.", format: "Diagnostic puis leadership intérimaire ou programme de reprise." },
      { title: "Architecture Flutter et modernisation", signal: "Changements lents, upgrades risqués ou variantes divergentes.", action: "Auditer architecture, état, dépendances, natif, tests et migration puis prioriser.", format: "Revue, plan et pilotage optionnel de l'implémentation." },
      { title: "Intégration native et release engineering", signal: "Signing, stores, SDK, deep links, notifications, WebView ou channels bloquent la release.", action: "Diagnostiquer la frontière native, stabiliser et documenter l'ownership opérationnel.", format: "Mission ciblée sur l'intégration ou la release." },
      { title: "CI/CD mobile et préparation production", signal: "Pipelines recréés, savoir manuel ou incidents sans propriétaire.", action: "Standardiser pipelines, signing, environnements, gates, contrôles et observabilité.", format: "Audit et sprint d'implémentation ou enablement multi-équipes." },
      { title: "Leadership mobile fractionné", signal: "Une direction senior est nécessaire avant ou à la place d'un recrutement à plein temps.", action: "Piloter architecture, planification, recrutement, coaching et risques avec capacité d'escalade hands-on.", format: "Mandat récurrent à temps partiel avec droits de décision clairs." },
      { title: "Évaluation du delivery", signal: "La direction veut comprendre pourquoi le delivery mobile reste imprévisible.", action: "Examiner roadmap, interfaces d'équipe, risque, gouvernance, qualité et ownership.", format: "Diagnostic court, entretiens, revue d'artefacts et restitution." },
    ], boundaryTitle: "Des conseils proportionnés au produit.", boundaryBody: "Un audit n'est pas un prétexte à réécrire. Il sépare le risque de production urgent du travail de maintenabilité et précise ce qui doit rester intact.",
  },
  experience: {
    title: "Plus de portée, sans quitter l'ingénierie.", intro: "Du web à Flutter senior, à l'ownership de plateforme, au rôle de Team Lead puis au management multi-équipes.",
    roles: [
      { period: "jan. 2026 — juil. 2026", company: "BrainRocket · Limassol, Chypre", title: "Engineering Manager, Mobile", summary: "Trois équipes et 15 ingénieurs ; deux Team Leads en direct.", evidence: "Trois lancements à l'heure, greenfield en cinq mois, cœur partagé par dix apps et responsabilité release/incidents." },
      { period: "déc. 2024 — déc. 2025", company: "BrainRocket · Limassol, Chypre", title: "Flutter Team Lead", summary: "Leadership, architecture, code review, escalade native et releases régulées.", evidence: "Swiper Ontario, BLoC/Riverpod, Kotlin/Swift channels et reprise après le départ d'un fournisseur." },
      { period: "juil. 2023 — déc. 2024", company: "CFP Technology (CFPS) · Remote", title: "Senior Flutter Developer", summary: "Plateforme d'opérations fintech sécurisée par VPN.", evidence: "100+ écrans en 18 mois et composants partagés." },
      { period: "jan. 2022 — juil. 2023", company: "Esh Derevenskoye · Remote", title: "Senior Flutter Developer", summary: "Marketplace alimentaire, livraison et abonnements.", evidence: "Pipeline OpenStreetMap pour 150 000 clients inscrits." },
      { period: "jan. 2021 — jan. 2022", company: "Rosselkhozbank · Moscou", title: "Flutter Developer", summary: "Parcours marketplace, B2B, P2P et services financiers.", evidence: "CI/CD, Docker Compose et tests golden, widget et intégration." },
      { period: "2015 — 2020", company: "Novorossiïsk", title: "Web, studio et premiers projets Flutter", summary: "Studio de 2 à 4 personnes, plus de 100 projets, puis leadership AngularDart/Flutter.", evidence: "Paiements, génération de leads et produit de livraison à 10 000+ inscrits la première année." },
    ], educationTitle: "Formation", educationBody: "42 Paris, cursus Software Engineering (depuis 2022, temps partiel) ; School 21 (2020–2022) ; Collège de construction et d'économie de Novorossiïsk, informatique appliquée (2015–2019).", languagesTitle: "Langues", languagesBody: "Russe — langue maternelle. Anglais — B2+, utilisé quotidiennement. Letton — A2.",
  },
  about: {
    title: "Un manager qui veut encore comprendre le mode de panne.", intro: "Denis est Engineering Manager et ingénieur mobile hands-on, avec 11+ ans en logiciel et 6+ ans en Flutter.", paragraphs: ["Son parcours va des produits web et d'un petit studio au banking, aux marketplaces, à la fintech, aux rôles Flutter senior, puis au leadership multi-équipes.", "Le fil conducteur est l'ownership à la frontière : produit, architecture, Android/iOS natif, CI/CD, stores, observabilité, debugging et organisation d'équipe.", "Le leadership n'a pas remplacé l'ingénierie. Denis est utile quand il faut décider au niveau portefeuille, coacher un Team Lead, revoir l'architecture et rejoindre une escalade de release."], usefulTitle: "Sujets à discuter", usefulItems: ["Un produit mobile doit passer de la roadmap à la production", "Une plateforme Flutter dérive ou devient risquée à mettre à jour", "SDK natifs, signing, WebView ou tooling bloquent le delivery", "Plusieurs équipes ont besoin d'un modèle commun sans perdre leur autonomie", "Un leadership fractionné ou un avis indépendant est nécessaire", "Une pipeline Flutter riche en SVG dépasse le rendu statique"], nowTitle: "Localisation et disponibilité", nowBody: "Basé à Tbilissi, Géorgie. Ouvert au remote et à une mobilité européenne. Rôles et missions : Engineering Manager, Mobile Engineering Manager, Mobile Tech Lead, Lead Flutter Engineer, conseil architecture et delivery.",
  },
  contact: {
    title: "Parlons du vrai problème mobile.", intro: "Une release instable, une architecture qui ralentit chaque changement, un ownership flou ou un produit sans chemin crédible vers la production.", directTitle: "Contact direct", response: "L'e-mail est privilégié. LinkedIn, GitHub et Telegram sont aussi disponibles.", formTitle: "Préparer une demande", formIntro: "Le formulaire valide l'essentiel puis ouvre un brouillon structuré dans votre messagerie. Rien n'est envoyé ni suivi par le site.", name: "Nom", email: "E-mail", company: "Entreprise", need: "De quelle aide avez-vous besoin ?", budget: "Budget", timeline: "Délai", optional: "facultatif", send: "Préparer l'e-mail", prepared: "Le brouillon est prêt. S'il ne s'est pas ouvert, utilisez l'adresse directe.", privacy: "Confidentiel par conception : le site ne stocke ni ne transmet les données. L'envoi ouvre votre messagerie.", errors: { name: "Indiquez votre nom.", email: "Indiquez un e-mail valide.", need: "Décrivez brièvement le besoin." }, budgetOptions: ["Non précisé", "Moins de 10 k€", "10–25 k€", "25–50 k€", "50 k€+"], timelineOptions: ["Non précisé", "Urgent / release en cours", "Sous un mois", "1–3 mois", "3 mois+"],
  },
};

