import type { SiteCopy } from "./types";

export const fr: SiteCopy = {
  localeName: "Français",
  seo: {
    home: { title: "Engineering Manager · Web, Mobile & AI", description: "Denis Nadey : plus de 11 ans en produits web, plateformes mobiles, management d'équipes d'ingénierie, open source et développement assisté par l'IA." },
    work: { title: "Web, Mobile & Engineering Leadership", description: "Réalisations de Denis Nadey : produits web, plateformes mobiles, fintech, processus de mise en production et open source." },
    "open-source": { title: "Open source : full_svg_flutter", description: "L'histoire technique de full_svg_flutter, un moteur autonome pour le SVG statique et animé dans Flutter." },
    services: { title: "Ingénierie Flutter, web & IA", description: "Product engineering senior pour le web, Flutter, l'architecture, les processus de mise en production et des workflows IA concrets." },
    experience: { title: "Expérience en management d'ingénierie", description: "De l'ingénierie logicielle hands-on à la direction de plusieurs équipes mobiles." },
    about: { title: "Denis Nadey · Web, Mobile & AI", description: "Engineering Manager et product engineer hands-on : racines dans le web, expertise mobile approfondie et une pratique où l'IA fait partie du quotidien." },
    contact: { title: "Contacter Denis Nadey", description: "Parlez à Denis Nadey d'un produit web ou mobile, d'un enjeu de management technique, d'un processus de mise en production ou d'un workflow IA concret." },
  },
  nav: { home: "Accueil", work: "Réalisations", "open-source": "Open source", services: "Services", experience: "Parcours", about: "À propos", contact: "Contact" },
  common: {
    role: "Engineering Manager · Web, Mobile & AI Product Engineer",
    location: "Tbilissi, Géorgie",
    availability: "Ouvert à une relocalisation en Europe / remote",
    menu: "Menu",
    language: "Langue",
    close: "Fermer",
    skip: "Aller au contenu",
    selectedEvidence: "Faits marquants · CV à jour",
    discuss: "Parler d'un projet",
    exploreWork: "Voir les réalisations",
    viewExperience: "Voir tout le parcours",
    downloadCv: "Télécharger le CV",
    viewOpenSource: "Voir l'open source",
    viewServices: "Voir les services",
    readArticle: "Lire l'analyse technique",
    visitGithub: "Voir sur GitHub",
    visitPub: "Voir sur pub.dev",
    finalTitle: "Un produit numérique à construire, moderniser ou débloquer ?",
    finalBody: "Décrivez le vrai problème – web, mobile, organisation de l'équipe ou workflow IA qui doit devenir fiable en production.",
    contactDenis: "Contacter Denis",
    external: "s'ouvre dans un nouvel onglet",
    current: "Page actuelle",
  },
  home: {
    titleLead: "Je construis des produits numériques – ",
    titleEmphasis: "du web et du mobile au développement assisté par l'IA.",
    intro: "Plus de 11 ans entre web, mobile et management d'ingénierie : 100+ projets web, des plateformes Flutter en production, plusieurs équipes en parallèle et l'IA utilisée comme un vrai outil d'ingénierie, pas comme un argument marketing.",
    proof: [
      { value: "11+", label: "ans d'ingénierie logicielle" },
      { value: "100+", label: "produits web livrés" },
      { value: "3", label: "équipes produit en parallèle" },
      { value: "15", label: "ingénieurs encadrés" },
      { value: "3", label: "packages runtime publics" },
    ],
    mandateLabel: "Ingénierie de bout en bout",
    mandateTitle: "L'étendue du web. La profondeur du mobile. L'IA dans la pratique.",
    mandateBody: "Denis a commencé par livrer des sites, des boutiques en ligne, des outils d'administration, des calculateurs, des paiements et des systèmes de génération de leads. Il est ensuite passé aux plateformes mobiles et au management de plusieurs équipes. Aujourd'hui, l'IA fait partie du cycle d'ingénierie – de la recherche et du prototypage à l'implémentation, aux tests et à la documentation –, mais la responsabilité du résultat reste humaine.",
    workLabel: "Réalisations",
    workTitle: "Des produits complexes, réellement livrés.",
    workIntro: "Ce qui compte, ce n'est pas une galerie de logos, mais le système derrière chaque lancement : des responsabilités claires, l'architecture, le contrôle des releases et le discernement pour simplifier au bon moment.",
    servicesLabel: "Travailler ensemble",
    servicesTitle: "Une expertise senior là où elle change le résultat.",
    servicesIntro: "Pour un produit à construire, reprendre, moderniser, auditer ou préparer à la production – et pour des équipes qui ont besoin d'un leadership technique sans perdre la profondeur hands-on.",
    openLabel: "Ingénierie open source",
    openTitle: "Un SVG doit rester un SVG.",
    openIntro: "full_svg_flutter est un moteur de rendu autonome pour le SVG statique et animé dans Flutter : SMIL, CSS @keyframes, path morphing, filtres, masques, texte, exports SVGator pilotés par JavaScript et contrôle de la lecture – sans convertir l'asset dans un autre format.",
    careerLabel: "Parcours",
    careerTitle: "Du web aux plateformes mobiles – et maintenant à l'ingénierie avec l'IA.",
    careerIntro: "Une progression cumulative : l'étendue des produits web, la profondeur des systèmes mobiles, le management d'ingénierie et une pratique moderne assistée par l'IA, qui accélère sans diluer la responsabilité.",
    principlesLabel: "Façon de travailler",
    principlesTitle: "Rendre les contraintes visibles. Garder les responsabilités explicites.",
    principles: [
      "Partir de la contrainte métier, pas du framework.",
      "Dimensionner l'architecture au produit et à l'équipe.",
      "Faire remonter tôt les risques de livraison et de release.",
      "Automatiser le travail répétitif de release et documenter le chemin d'exception.",
      "Expliquer les arbitrages dans un langage que le décideur peut utiliser.",
      "Laisser la plateforme plus facile à exploiter qu'on ne l'a trouvée.",
    ],
  },
  work: {
    title: "Produits web, plateformes mobiles et systèmes de mise en production.",
    intro: "Une sélection de programmes où Denis portait la responsabilité de la livraison, de la qualité de la plateforme ou d'une frontière technique difficile. Le portfolio commence par le web product engineering, puis s'étend à l'architecture mobile et à la responsabilité de plusieurs équipes.",
    labels: { context: "Contexte", responsibility: "Responsabilité", approach: "Approche", outcome: "Résultat", stack: "Stack" },
    nda: "Les études de cas excluent volontairement l'architecture confidentielle, les identifiants, les détails de produits non annoncés et les métriques commerciales internes.",
    cases: [
      {
        label: "01 · Livraison multi-marchés",
        title: "Trois lancements régulés sur trois roadmaps parallèles",
        summary: "Pilotage du portefeuille Zinx Romania, Betoro Denmark et YoYo Sweden ; YoYo a atteint la production en cinq mois environ.",
        context: "Trois équipes mobiles livraient en même temps pour des marchés régulés différents, alors que les effectifs, les priorités, les dépendances et les exigences de conformité ne cessaient de bouger.",
        responsibility: "A dirigé le portefeuille de 15 ingénieurs, accompagné deux Team Leads, gardé la responsabilité de la livraison et de la santé des équipes, et aligné Product, Design, QA, Backend, Payments et Compliance.",
        approach: "A mis en place un modèle opérationnel commun pour l'estimation, la capacité, la cartographie des dépendances, les jalons et les release gates. Est resté assez proche de la technique pour résoudre lui-même les escalades liées à la signature des apps, aux SDK natifs, au pont WebView, aux stores et aux incidents.",
        outcome: "Les trois produits ont tenu leurs fenêtres de mise en service réglementaires. YoYo est passé de la première implémentation à la production en cinq mois environ.",
        stack: "Flutter, Dart, Kotlin, Swift, REST/WebSockets, Firebase, GitLab CI/CD, Codemagic, Fastlane, Sentry/Crashlytics",
      },
      {
        label: "02 · Modernisation de plateforme",
        title: "Un cœur Flutter commun et un système de release pour dix applications",
        summary: "A modernisé la plateforme sous un portefeuille multi-marques sans interrompre les livraisons des produits actifs.",
        context: "Dix applications partageaient un cœur Flutter et des configurations propres à chaque marque. La divergence des versions et la reconfiguration de chaque release alourdissaient la maintenance et le risque en production.",
        responsibility: "A piloté la migration du cœur commun de Flutter 3.19 vers 3.38.1 et standardisé des workflows GitLab CI/CD et Codemagic réutilisables pour toutes les équipes produit.",
        approach: "A consolidé la configuration de la plateforme, les checklists de release, les standards de revue, les tests automatisés, l'observabilité et le suivi des incidents, tout en déléguant l'exécution quotidienne aux Team Leads.",
        outcome: "Moins de divergence entre les applications et de configuration répétée, une responsabilité des releases plus claire et un socle de production cohérent pour tout le portefeuille.",
        stack: "Flutter 3.19–3.38.1, GitLab CI/CD, Codemagic, Fastlane, tests automatisés, Sentry, Crashlytics",
      },
      {
        label: "03 · Opérations fintech",
        title: "Une plateforme d'opérations de plus de 100 écrans, construite à partir de zéro",
        summary: "Ingénierie Flutter hands-on pour un produit d'opérations sécurisé par VPN : KYC, AML, cartes, IBAN, transactions, permissions et workflows de support.",
        context: "Les opérations financières internes exigeaient une interface dense et fiable, avec de nombreux états métier, des règles d'accès, des mises à jour en temps réel et des workflows sensibles à la conformité.",
        responsibility: "Seul développeur Flutter de la plateforme, au sein d'une organisation d'ingénierie plus large.",
        approach: "A créé des tableaux, formulaires, permissions, contrôles d'accès et composants temps réel réutilisables, sur une architecture modulaire et une démarche centrée sur les tests.",
        outcome: "Plus de 100 écrans en production en 18 mois, avec un modèle de composants partagé qui a garanti une implémentation homogène dans tous les domaines opérationnels.",
        stack: "Flutter Web/Desktop, Dart, Clean Architecture, BLoC, get_it, REST, WebSockets, TDD, tests unitaires et golden tests",
      },
      {
        label: "04 · Commerce et géodonnées",
        title: "Une livraison au numéro près, sans géocodeur payant",
        summary: "Un pipeline d'adresses maison, fondé sur OpenStreetMap, pour une marketplace de produits fermiers comptant 150 000 clients inscrits.",
        context: "La précision des livraisons dépendait de la normalisation d'adresses hétérogènes et de leur rapprochement au niveau du bâtiment, sans recourir à un service de géocodage externe payant.",
        responsibility: "A conçu et livré personnellement le pipeline de géocodage, de normalisation et de rapprochement des adresses, en parallèle du catalogue, du panier, du checkout, de la livraison et des abonnements côté client.",
        approach: "A combiné les données OpenStreetMap avec des règles de normalisation et des règles géospatiales propres au produit, puis intégré le résultat dans les parcours opérationnels et les parcours de livraison.",
        outcome: "Des adresses de livraison plus précises et une exploitation plus fiable pour un produit comptant 150 000 clients inscrits.",
        stack: "Flutter, Dart, OpenStreetMap, Firebase, REST, Clean Architecture, TDD, intégrations natives Android/iOS",
      },
    ],
  },
  openSource: {
    title: "L'esprit d'un moteur de navigateur, appliqué au SVG dans Flutter.",
    intro: "Denis a créé et maintient full_svg_flutter, un runtime de rendu autonome pour les équipes qui ont besoin que leurs assets SVG existants restent des SVG dans Flutter.",
    versionLabel: "État public · 7 octobre 2026",
    proof: [
      { value: "1.5.2", label: "version actuelle" },
      { value: "140", label: "pub points" },
      { value: "17", label: "versions publiques" },
      { value: "MIT", label: "licence open source" },
    ],
    problemTitle: "L'asset fonctionne dans le navigateur. Dans Flutter, l'animation disparaît.",
    problemBody: "Beaucoup de pipelines comblent cet écart en convertissant l'asset en Lottie, Rive, GIF, WebP ou en code d'animation Flutter écrit à la main. Ce sont parfois de bons outils – mais la conversion est le mauvais prix à payer quand le SVG est déjà la source de vérité.",
    engineTitle: "Un seul moteur, qui préserve le DOM, pour le SVG statique et animé",
    engineBody: "Le package analyse le modèle de document, le CSS, le timing, les filtres, le texte et l'état d'interaction, puis dessine dans Flutter. Les exports SVGator pilotés par JavaScript s'exécutent dans un moteur QuickJS embarqué ; les SVG sans script ne paient aucun coût de démarrage JavaScript.",
    coverageTitle: "Ce que couvre le runtime",
    coverage: [
      "Géométrie statique, dégradés, motifs, clipping et masques",
      "Animations SMIL et CSS @keyframes",
      "Path morphing, motion paths et contrôle de la lecture",
      "Les 17 primitives de filtre SVG",
      "Texte riche, textPath, bidi/RTL et métadonnées d'accessibilité",
      "JavaScript inline et exports SVGator",
      "Migration compatible avec l'API statique de flutter_svg",
      "Android, iOS, macOS, Windows et Linux",
    ],
    migrationTitle: "Un chemin de migration pragmatique",
    migrationBody: "Les usages statiques existants de SvgPicture migrent souvent avec un simple changement d'import. FSvgPicture détecte automatiquement les marqueurs d'animation, et AnimatedSvgController ajoute pause, seek, vitesse, direction et changement de vue SVG quand le produit en a besoin.",
    demoTitle: "Un seul fichier SVG. Ici, l'animation native du navigateur ; dans le package, le rendu natif Flutter.",
    demoBody: "Cette page affiche l'asset SVG animé du projet dans le navigateur. Dans une application Flutter, full_svg_flutter rend exactement le même fichier source dans Flutter, sans WebView ni étape de conversion.",
    relatedTitle: "Package associé : woff2",
    relatedBody: "Construire un runtime SVG sérieux a révélé un autre cas limite : les polices embarquées au format WOFF ou WOFF2. Denis a publié un décodeur pur Dart, encore jeune, avec un wrapper FontLoader, pour que les pipelines Flutter enregistrent ces formats sans plugin natif propre à chaque application.",
    writingTitle: "Articles techniques",
    articleTitle: "Le problème : dans Flutter, la prise en charge du SVG est généralement statique",
    articleDescription: "Une explication concrète de l'écart de rendu, des contournements courants, du contrôle de la lecture, des compromis de performance – et des cas où garder le SVG en SVG est le bon choix.",
  },
  services: {
    title: "Product engineering senior pour le web, le mobile et l'IA.",
    intro: "Faites appel à Denis quand un produit numérique a besoin d'un responsable crédible sur l'interface, l'architecture, la livraison, la production et les workflows IA modernes capables d'accélérer chaque étape.",
    labels: { signal: "Quand c'est utile", action: "Ce que fait Denis", format: "Format habituel" },
    items: [
      { title: "Livraison et sauvetage de produit mobile", signal: "La roadmap dérape, les responsabilités sont éclatées ou une release critique compte trop d'inconnues.", action: "Clarifie les contraintes, cartographie les dépendances, redéfinit les jalons, prend en charge les escalades techniques et met en place un modèle de livraison prêt pour la production.", format: "Diagnostic de la livraison, puis direction technique intérimaire hands-on ou programme de redressement ciblé." },
      { title: "Architecture Flutter et modernisation", signal: "L'application est difficile à faire évoluer, les mises à niveau cassent régulièrement la livraison ou les variantes de marque et de produit divergent.", action: "Passe en revue les frontières, la gestion d'état, les dépendances, l'intégration native, les tests et les risques de migration, puis séquence la modernisation sans arrêter la livraison en cours.", format: "Revue d'architecture, plan priorisé et, si besoin, pilotage de l'implémentation." },
      { title: "Intégration native et release engineering", signal: "Signature, stores, SDK, deep links, notifications, WebView ou platform channels bloquent une release fiable.", action: "Analyse la frontière avec la plateforme, corrige les problèmes d'intégration et de cycle de vie, consolide le chemin de release et documente qui est responsable de quoi en exploitation.", format: "Mission technique ciblée sur un problème d'intégration ou de release bien défini." },
      { title: "CI/CD mobile et préparation à la production", signal: "Les pipelines sont reconstruits pour chaque application, les releases reposent sur un savoir non documenté ou les incidents n'ont pas de responsable clair.", action: "Standardise les pipelines, la signature et les environnements, les release gates, les contrôles, l'observabilité et le suivi des incidents – sans sur-ingénierie de la plateforme.", format: "Audit puis sprint d'implémentation, ou mise en place de la plateforme pour plusieurs équipes." },
      { title: "Direction technique mobile à temps partiel", signal: "Une entreprise a besoin d'une direction mobile senior avant – ou à la place – d'un recrutement à plein temps.", action: "Prend en charge les décisions d'architecture, la planification technique, l'appui au recrutement, le coaching des Team Leads et les risques de livraison, tout en restant disponible pour les escalades hands-on.", format: "Mandat récurrent à temps partiel, avec des résultats attendus et un pouvoir de décision explicites." },
      { title: "Évaluation de la livraison logicielle", signal: "La direction a besoin d'un regard indépendant sur les raisons qui rendent la livraison mobile imprévisible.", action: "Examine la forme de la roadmap, les interfaces entre équipes, les risques techniques, la gouvernance des releases, les signaux de qualité et les responsabilités ; rend un plan d'action priorisé et défendable.", format: "Diagnostic court : entretiens, revue des artefacts et restitution à la direction et aux équipes techniques." },
    ],
    boundaryTitle: "Des recommandations à la mesure du produit.",
    boundaryBody: "Un audit n'est pas un prétexte pour tout réécrire. Les recommandations distinguent le risque de production urgent du travail de maintenabilité, expliquent les arbitrages et précisent ce qui doit rester tel quel.",
  },
  experience: {
    title: "Un périmètre qui grandit, sans quitter l'ingénierie.",
    intro: "Un parcours qui va de la livraison de produits web à l'ingénierie Flutter senior, à la responsabilité d'une plateforme, au rôle de Team Lead, puis au management de plusieurs équipes mobiles.",
    roles: [
      { period: "janv. 2026 – juil. 2026", company: "BrainRocket · Limassol, Chypre", title: "Engineering Manager, Mobile", summary: "A dirigé trois équipes en parallèle et 15 ingénieurs sur des marchés iGaming régulés, avec deux Team Leads en rapport direct.", evidence: "Trois lancements tenus dans les délais ; un produit greenfield en production en cinq mois environ ; un cœur partagé par dix applications ; responsabilité des releases et des incidents à l'échelle du portefeuille." },
      { period: "déc. 2024 – déc. 2025", company: "BrainRocket · Limassol, Chypre", title: "Flutter Team Lead", summary: "A combiné le management d'équipe avec l'architecture modulaire, la revue de code, les escalades natives et la responsabilité des releases régulées.", evidence: "Swiper Ontario et d'autres releases ; Clean Architecture avec BLoC/Riverpod ; platform channels Kotlin/Swift ; redressement après le départ d'une équipe externe." },
      { period: "juil. 2023 – déc. 2024", company: "CFP Technology (CFPS) · Remote", title: "Senior Flutter Developer", summary: "A construit une plateforme d'opérations Flutter en production, sécurisée par VPN, couvrant des workflows fintech et conformité.", evidence: "100+ écrans en 18 mois ; formulaires, tableaux, permissions, contrôles d'accès et composants temps réel réutilisables." },
      { period: "janv. 2022 – juil. 2023", company: "Esh Derevenskoye · Remote", title: "Senior Flutter Developer", summary: "A développé la marketplace et les parcours de commande récurrente d'un service premium de livraison de produits fermiers.", evidence: "A conçu un pipeline maison de géocodage OpenStreetMap et de rapprochement au numéro près pour un produit comptant 150 000 clients inscrits." },
      { period: "janv. 2021 – janv. 2022", company: "Rosselkhozbank · Moscou", title: "Flutter Developer", summary: "A développé des parcours marketplace, B2B, P2P et de services financiers pour des produits agricoles.", evidence: "A introduit la CI/CD, des environnements Docker Compose ainsi que des golden tests, des tests de widgets et des tests d'intégration." },
      { period: "2015 – 2020", company: "Novorossiïsk", title: "Ingénierie web, direction d'un studio et premiers projets Flutter", summary: "A fondé un petit studio, livré plus de 100 projets web, puis dirigé l'implémentation AngularDart/Flutter d'Edakratia.", evidence: "Studio de deux à quatre personnes ; systèmes de paiement et de génération de leads ; produit de livraison de repas avec 10 000+ utilisateurs inscrits dès la première année." },
    ],
    educationTitle: "Formation",
    educationBody: "42 Paris, cursus Software Engineering (depuis 2022, à temps partiel) ; School 21 (2020–2022, transfert vers 42 Paris) ; Institut technique de construction et d'économie de Novorossiïsk, informatique appliquée / technicien en génie logiciel (2015–2019).",
    languagesTitle: "Langues",
    languagesBody: "Russe – langue maternelle. Anglais – B2+, utilisé au quotidien pour la communication avec les parties prenantes, la documentation technique, les entretiens et la coordination entre équipes. Letton – A2.",
  },
  about: {
    title: "Product engineer avant d'être spécialiste d'un framework.",
    intro: "Denis est Engineering Manager et ingénieur hands-on, avec plus de 11 ans d'expérience en produits web, plateformes mobiles, runtimes open source et développement assisté par l'IA.",
    paragraphs: [
      "Le parcours commence dans le web : un petit studio, plus de 100 projets livrés, du e-commerce, des systèmes d'administration, des paiements, des calculateurs et des parcours de génération de leads. Cette étendue a forgé un regard produit bien avant la banque, les marketplaces, la fintech et Flutter.",
      "Le mobile a apporté des contraintes de plateforme plus dures : l'intégration Kotlin et Swift, la signature des apps, les stores, la CI/CD, l'observabilité, les incidents en production et une architecture partagée entre plusieurs applications. Le management a ensuite étendu cette responsabilité aux Team Leads, aux roadmaps, au recrutement et à trois équipes en parallèle.",
      "L'IA fait désormais partie de la méthode de travail. Denis s'en sert pour condenser la recherche, explorer des architectures, prototyper des interfaces, écrire et relire du code, concevoir des tests et produire de la documentation. L'exigence reste la même : des preuves, des arbitrages explicites et un humain responsable de ce qui part en production.",
    ],
    usefulTitle: "Sujets qui méritent une conversation",
    usefulItems: [
      "Un produit mobile a besoin d'un chemin crédible de la roadmap à la production",
      "Une plateforme Flutter a accumulé de la divergence ou des risques de mise à niveau",
      "Des SDK natifs, la signature, des WebView ou l'outillage de release bloquent la livraison",
      "Plusieurs équipes ont besoin d'un modèle opérationnel commun sans perdre leur autonomie",
      "Une entreprise a besoin d'une direction mobile à temps partiel ou d'une évaluation technique indépendante",
      "Un pipeline Flutter riche en SVG a besoin de plus que du rendu statique",
    ],
    nowTitle: "Localisation et disponibilité",
    nowBody: "Basé à Tbilissi, en Géorgie. Ouvert au travail à distance et à une relocalisation en Europe. Rôles et missions pertinents : Engineering Manager, Mobile Engineering Manager, Mobile Tech Lead, Lead Flutter Engineer, conseil en architecture et missions de livraison ciblées.",
  },
  contact: {
    title: "Venez avec le vrai problème.",
    intro: "Un produit web sans chemin vers la production, une release mobile qui ne se stabilise pas, une équipe aux responsabilités floues ou un workflow IA qui doit devenir de l'ingénierie fiable.",
    directTitle: "Contact direct",
    response: "L'e-mail est le canal à privilégier. LinkedIn, GitHub et Telegram fonctionnent aussi.",
    formTitle: "Préparer une demande de projet",
    formIntro: "Le formulaire vérifie l'essentiel, puis ouvre un brouillon structuré dans votre messagerie. Rien n'est envoyé ni suivi par le site.",
    name: "Nom",
    email: "E-mail",
    company: "Entreprise",
    need: "De quelle aide avez-vous besoin ?",
    budget: "Budget",
    timeline: "Délai",
    optional: "facultatif",
    send: "Préparer l'e-mail",
    prepared: "Votre brouillon est prêt. S'il ne s'est pas ouvert, utilisez l'adresse e-mail directe indiquée sur cette page.",
    privacy: "Confidentiel par conception : ce site ne stocke ni ne transmet les données du formulaire. L'envoi ouvre simplement votre propre messagerie.",
    errors: { name: "Indiquez votre nom.", email: "Indiquez une adresse e-mail valide.", need: "Décrivez brièvement le problème." },
    budgetOptions: ["Non précisé", "Moins de 10 000 €", "10 000–25 000 €", "25 000–50 000 €", "Plus de 50 000 €"],
    timelineOptions: ["Non précisé", "Urgent / release en cours", "Sous un mois", "1–3 mois", "Plus de 3 mois"],
  },
};
