import type { CaseStudy, Locale, Service } from "./types";

type PositioningCopy = {
  role: string;
  themeToDark: string;
  themeToLight: string;
  docsCta: string;
  seo: {
    home: { title: string; description: string };
    work: { title: string; description: string };
    services: { title: string; description: string };
    about: { title: string; description: string };
    contact: { title: string; description: string };
  };
  home: {
    titleLead: string;
    titleEmphasis: string;
    intro: string;
    proof: Array<{ value: string; label: string }>;
    mandateLabel: string;
    mandateTitle: string;
    mandateBody: string;
    capabilityLabel: string;
    capabilityTitle: string;
    capabilities: Array<{ code: string; title: string; body: string; evidence: string }>;
    careerTitle: string;
    careerIntro: string;
  };
  work: { title: string; intro: string; webCase: CaseStudy };
  services: { title: string; intro: string; additions: Service[] };
  about: { title: string; intro: string; paragraphs: string[] };
  contact: { title: string; intro: string };
  finalTitle: string;
  finalBody: string;
};

export const positioning: Record<Locale, PositioningCopy> = {
  en: {
    role: "Engineering Manager · Web, Mobile & AI Product Engineer",
    themeToDark: "Switch to dark theme",
    themeToLight: "Switch to light theme",
    docsCta: "Read package documentation",
    seo: {
      home: { title: "Engineering Manager · Web, Mobile & AI", description: "Denis Nadey brings 11+ years across web product engineering, mobile platforms, engineering leadership, open source, and AI-enabled delivery." },
      work: { title: "Web, Mobile & Engineering Leadership Work", description: "Selected web product, mobile platform, delivery, fintech, and open-source engineering work by Denis Nadey." },
      services: { title: "Flutter, Web & AI Engineering Services", description: "Senior product engineering across web, Flutter, delivery systems, architecture, and practical AI-enabled workflows." },
      about: { title: "About Denis Nadey · Web, Mobile & AI", description: "An Engineering Manager and hands-on product engineer with roots in web, deep mobile experience, and an AI-native delivery practice." },
      contact: { title: "Contact Denis Nadey · Web, Mobile & AI", description: "Discuss a web or mobile product, engineering leadership challenge, delivery system, or practical AI workflow with Denis Nadey." },
    },
    home: {
      titleLead: "I build digital products—",
      titleEmphasis: "from web and mobile to AI-enabled delivery.",
      intro: "Eleven-plus years across web, mobile, and engineering leadership: 100+ web projects, production Flutter platforms, multi-team delivery, and AI used as a serious engineering tool—not a badge.",
      proof: [{ value: "11+", label: "years in software engineering" }, { value: "100+", label: "web products delivered" }, { value: "3", label: "concurrent product teams" }, { value: "15", label: "engineers led" }, { value: "3", label: "public runtime packages" }],
      mandateLabel: "Full-spectrum engineering",
      mandateTitle: "Web breadth. Mobile depth. AI-native execution.",
      mandateBody: "Denis started by shipping websites, commerce systems, admin tools, calculators, payments, and lead-generation products. He later moved into mobile platforms and multi-team leadership. Today, AI is part of the engineering loop—from research and prototyping to implementation, tests, and documentation—with human judgment kept accountable for the result.",
      capabilityLabel: "Three connected strengths",
      capabilityTitle: "One engineer across the product boundary.",
      capabilities: [
        { code: "WEB", title: "Web product engineering", body: "Frontend and product architecture, e-commerce, operational interfaces, integrations, performance, accessibility, and the delivery systems around them.", evidence: "100+ web projects · studio founder · AngularDart · current React/Vinext stack" },
        { code: "MOB", title: "Mobile platforms & leadership", body: "Flutter architecture, Kotlin/Swift boundaries, CI/CD, stores, observability, release governance, and leadership across several teams.", evidence: "11+ years total · 6+ Flutter · 3 teams · 80+ releases" },
        { code: "AI", title: "AI-enabled engineering", body: "AI used for structured research, solution exploration, product prototyping, implementation, code review, test design, and technical documentation—not unchecked output.", evidence: "Agentic workflows · rapid product slices · verification-first delivery" },
      ],
      careerTitle: "From web delivery to mobile platforms—and now AI-shaped engineering.",
      careerIntro: "The progression is cumulative: web product breadth, deep mobile systems work, engineering management, and a modern AI-assisted practice that increases speed without handing away responsibility.",
    },
    work: {
      title: "Work across web products, mobile platforms, and delivery systems.",
      intro: "Selected programs where Denis owned delivery, platform quality, or a difficult system boundary. The portfolio begins in web product engineering, then expands into mobile architecture and multi-team responsibility.",
      webCase: { label: "05 · Web product engineering", title: "More than 100 web products before the mobile chapter", summary: "A five-year foundation in websites, e-commerce, operational panels, calculators, payment integrations, and lead-generation systems.", context: "Small and medium businesses needed complete digital products, not isolated UI work: discovery, implementation, hosting, integrations, and a path to measurable use.", responsibility: "Founded and led a two-to-four-person web studio and remained hands-on across frontend, product logic, integrations, delivery, and client communication.", approach: "Built proportional solutions for commerce, administration, payments, calculations, and lead generation, choosing the simplest architecture that could be operated after handoff.", outcome: "Delivered more than 100 small-to-medium web projects between 2015 and 2019—the foundation for later product, platform, and engineering leadership work.", stack: "HTML/CSS, JavaScript, PHP, CMS and commerce platforms, payment integrations, analytics, hosting, AngularDart" },
    },
    services: {
      title: "Senior product engineering across web, mobile, and AI.",
      intro: "Bring Denis in when a digital product needs credible ownership across interface, architecture, delivery, production, and the modern AI workflows that can accelerate each stage.",
      additions: [
        { title: "Web product engineering & modernization", signal: "A web product needs to move from idea to production, or an existing frontend has become slow, fragile, or difficult to extend.", action: "Clarify product flows, reshape the frontend and integration boundaries, improve accessibility and performance, and establish a maintainable delivery path.", format: "Focused product build, modernization sprint, architecture review, or hands-on technical leadership." },
        { title: "Applied AI workflow & product prototyping", signal: "A team wants real leverage from AI but needs more than demos, prompt collections, or unreviewed generated code.", action: "Design a verification-first workflow for research, prototyping, implementation, testing, documentation, and review; build a production-shaped slice to prove it.", format: "Workflow assessment, enablement sprint, rapid product prototype, or integration into an existing engineering system." },
      ],
    },
    about: {
      title: "A product engineer before any single framework.",
      intro: "Denis is an Engineering Manager and hands-on engineer with 11+ years spanning web products, mobile platforms, open-source runtimes, and AI-enabled delivery.",
      paragraphs: [
        "The career started in web: a small studio, more than 100 delivered projects, commerce, admin systems, payments, calculators, and lead-generation flows. That breadth built a product mindset before the move into banking, marketplaces, fintech, and Flutter.",
        "Mobile work added deeper platform constraints—Kotlin and Swift integration, signing, stores, CI/CD, observability, production incidents, and shared architecture across multiple applications. Leadership later expanded that ownership to Team Leads, roadmaps, hiring, and three concurrent teams.",
        "AI is now part of the working method. Denis uses it to compress research, explore architectures, prototype interfaces, implement and review code, design tests, and produce documentation. The standard remains the same: evidence, explicit trade-offs, and a human owner for what reaches production.",
      ],
    },
    contact: { title: "Bring the real product constraint.", intro: "A web product that needs a production path, a mobile release that will not stabilize, a team with unclear ownership, or an AI workflow that must become reliable engineering." },
    finalTitle: "Need to build, modernize, or unblock a digital product?",
    finalBody: "Bring the real constraint—web, mobile, team delivery, or an AI workflow that needs to become production-worthy.",
  },
  ru: {
    role: "Engineering Manager · Web, Mobile & AI Product Engineer",
    themeToDark: "Включить тёмную тему", themeToLight: "Включить светлую тему", docsCta: "Читать документацию пакетов",
    seo: { home: { title: "Engineering Manager · Web, Mobile & AI", description: "Денис Надей: больше 11 лет в веб-продуктах, мобильных платформах, руководстве инженерными командами, open source и разработке с помощью ИИ." }, work: { title: "Веб, мобильные платформы и руководство разработкой", description: "Избранные проекты Дениса Надея: веб-продукты, мобильные платформы, финтех, процессы выпуска и open source." }, services: { title: "Услуги: Flutter, веб и ИИ", description: "Продуктовая инженерия senior-уровня: веб, Flutter, архитектура, процессы выпуска и практичные ИИ-процессы." }, about: { title: "Денис Надей · Web, Mobile & AI", description: "Engineering Manager и практикующий продуктовый инженер: корни в вебе, глубина в мобильной разработке и рабочий процесс, построенный вокруг ИИ." }, contact: { title: "Связаться с Денисом Надеем", description: "Обсудить веб- или мобильный продукт, задачу для инженерного руководителя, процессы выпуска или практичный ИИ-процесс." } },
    home: {
      titleLead: "Я создаю цифровые продукты — ", titleEmphasis: "от веба и мобильных приложений до разработки с помощью ИИ.", intro: "Больше 11 лет в вебе, мобильной разработке и руководстве командами: 100+ веб-проектов, Flutter-платформы в продакшене, несколько команд одновременно и ИИ как полноценный инженерный инструмент, а не модное слово в резюме.",
      proof: [{ value: "11+", label: "лет в разработке" }, { value: "100+", label: "выпущенных веб-продуктов" }, { value: "3", label: "продуктовые команды параллельно" }, { value: "15", label: "инженеров в подчинении" }, { value: "3", label: "публичных runtime-пакета" }],
      mandateLabel: "Полный цикл разработки", mandateTitle: "Широта веба. Глубина мобильной разработки. ИИ в рабочем процессе.", mandateBody: "Денис начинал с сайтов, интернет-магазинов, админок, калькуляторов, платёжных систем и лидогенерации. Потом были мобильные платформы и руководство несколькими командами. Сегодня ИИ встроен в инженерный цикл — от исследования и прототипа до реализации, тестов и документации, — но за результат по-прежнему отвечает человек.",
      capabilityLabel: "Три связанные сильные стороны", capabilityTitle: "Один инженер на всём пути от интерфейса до продакшена.",
      capabilities: [
        { code: "WEB", title: "Веб-продукты", body: "Frontend и продуктовая архитектура, интернет-магазины, операционные интерфейсы, интеграции, производительность, доступность и процессы выпуска вокруг всего этого.", evidence: "100+ веб-проектов · основатель студии · AngularDart · сейчас React/Vinext" },
        { code: "MOB", title: "Мобильные платформы и руководство", body: "Flutter-архитектура, стык с Kotlin/Swift, CI/CD, сторы, наблюдаемость, управление релизами и руководство несколькими командами.", evidence: "11+ лет · 6+ лет Flutter · 3 команды · 80+ релизов" },
        { code: "AI", title: "Разработка с помощью ИИ", body: "ИИ для структурированного исследования, поиска решений, прототипирования, реализации, код-ревью, проектирования тестов и технической документации — без слепого доверия результату.", evidence: "Агентные процессы · быстрые срезы продукта · проверка прежде выпуска" },
      ],
      careerTitle: "От веб-разработки к мобильным платформам — и дальше, к инженерии с ИИ.", careerIntro: "Опыт накапливался слоями: широта веб-продуктов, глубокая работа с мобильными системами, управление командами и современная практика с ИИ, которая ускоряет работу, но не снимает ответственности.",
    },
    work: { title: "Веб-продукты, мобильные платформы и процессы выпуска.", intro: "Проекты, где Денис отвечал за выпуск, качество платформы или сложный стык систем. Портфель начинается с веб-разработки и расширяется до мобильной архитектуры и ответственности за несколько команд.", webCase: { label: "05 · Веб-разработка", title: "Больше 100 веб-продуктов до мобильной главы", summary: "Пять лет фундамента: сайты, интернет-магазины, операционные панели, калькуляторы, платёжные интеграции и системы лидогенерации.", context: "Малому и среднему бизнесу нужны были законченные цифровые продукты, а не отдельный интерфейс: исследование, реализация, хостинг, интеграции и понятный путь к измеримой пользе.", responsibility: "Основал и вёл веб-студию из двух–четырёх человек, оставаясь руками во frontend, продуктовой логике, интеграциях, выпуске и общении с заказчиками.", approach: "Делал соразмерные решения для торговли, администрирования, платежей, расчётов и привлечения клиентов, выбирая самую простую архитектуру, которую заказчик сможет поддерживать после передачи.", outcome: "Больше 100 малых и средних веб-проектов с 2015 по 2019 год — фундамент для последующей продуктовой, платформенной и управленческой работы.", stack: "HTML/CSS, JavaScript, PHP, CMS и e-commerce-платформы, платёжные интеграции, аналитика, хостинг, AngularDart" } },
    services: { title: "Продуктовая инженерия senior-уровня: веб, мобильная разработка и ИИ.", intro: "Подключайте Дениса, когда цифровому продукту нужен один человек, отвечающий за интерфейс, архитектуру, выпуск, продакшен и современные ИИ-процессы, ускоряющие каждый этап.", additions: [
      { title: "Веб-продукты: разработка и модернизация", signal: "Веб-продукт нужно довести от идеи до продакшена, или существующий frontend стал медленным, хрупким и дорогим в развитии.", action: "Уточняет продуктовые сценарии, перестраивает frontend и границы интеграций, улучшает доступность и производительность, выстраивает поддерживаемый процесс выпуска.", format: "Разработка продукта, спринт модернизации, архитектурное ревью или техническое руководство на месте." },
      { title: "Прикладные ИИ-процессы и прототипирование", signal: "Команда хочет реальной пользы от ИИ, а не демо, коллекций промптов и непроверенного сгенерированного кода.", action: "Проектирует процесс с проверкой на каждом шаге — исследование, прототип, реализация, тесты, документация, ревью — и доказывает его на реальном фрагменте продукта, готовом к продакшену.", format: "Оценка процесса, спринт внедрения, быстрый прототип продукта или интеграция в существующую инженерную систему." },
    ] },
    about: { title: "Продуктовый инженер прежде любого фреймворка.", intro: "Денис — Engineering Manager и практикующий инженер с опытом 11+ лет: веб-продукты, мобильные платформы, open-source рантаймы и разработка с помощью ИИ.", paragraphs: ["Карьера началась в вебе: собственная небольшая студия, больше 100 выпущенных проектов, интернет-магазины, админки, платежи, калькуляторы и лидогенерация. Эта широта сформировала продуктовое мышление ещё до банков, маркетплейсов, финтеха и Flutter.", "Мобильная разработка добавила жёсткие платформенные ограничения: интеграции на Kotlin и Swift, подпись приложений, сторы, CI/CD, наблюдаемость, инциденты в продакшене и общая архитектура для нескольких приложений. Потом руководство расширило ответственность до тимлидов, роадмапов, найма и трёх команд одновременно.", "ИИ теперь часть рабочего метода. Денис использует его, чтобы быстрее исследовать, перебирать варианты архитектуры, прототипировать интерфейсы, писать и ревьюить код, проектировать тесты и готовить документацию. Планка не меняется: факты, явные компромиссы и человек, который отвечает за то, что уходит в продакшен."] },
    contact: { title: "Расскажите о реальной задаче.", intro: "Веб-продукт, который никак не доедет до продакшена. Мобильный релиз, который не стабилизируется. Команда с размытой ответственностью. Или ИИ-процесс, которому пора стать надёжной инженерной практикой." },
    finalTitle: "Нужно создать, модернизировать или сдвинуть с места цифровой продукт?", finalBody: "Расскажите о реальной задаче: веб, мобильное приложение, работа команды или ИИ-процесс, который пора довести до продакшена.",
  },
  de: {
    role: "Engineering Manager · Web, Mobile & AI Product Engineer", themeToDark: "Dunkles Design aktivieren", themeToLight: "Helles Design aktivieren", docsCta: "Paketdokumentation lesen",
    seo: { home: { title: "Engineering Manager · Web, Mobile & AI", description: "Denis Nadey: über 11 Jahre Erfahrung in Web-Produkten, Mobile-Plattformen, Engineering-Führung, Open Source und KI-gestützter Entwicklung." }, work: { title: "Web, Mobile & Engineering Leadership", description: "Ausgewählte Arbeiten von Denis Nadey: Web-Produkte, Mobile-Plattformen, Fintech, Auslieferungsprozesse und Open Source." }, services: { title: "Flutter-, Web- & KI-Engineering", description: "Senior Product Engineering für Web, Flutter, Architektur, Auslieferungsprozesse und praxistaugliche KI-Workflows." }, about: { title: "Denis Nadey · Web, Mobile & AI", description: "Engineering Manager und Hands-on-Product-Engineer: Wurzeln im Web, Tiefe im Mobile-Bereich und eine Arbeitsweise, in der KI fest verankert ist." }, contact: { title: "Denis Nadey kontaktieren", description: "Ein Web- oder Mobile-Produkt, eine Führungsaufgabe im Engineering, einen Auslieferungsprozess oder einen konkreten KI-Workflow mit Denis Nadey besprechen." } },
    home: { titleLead: "Ich baue digitale Produkte – ", titleEmphasis: "von Web und Mobile bis zur KI-gestützten Entwicklung.", intro: "Über 11 Jahre in Web, Mobile und Engineering-Führung: 100+ Web-Projekte, Flutter-Plattformen in Produktion, mehrere Teams parallel und KI als ernsthaftes Engineering-Werkzeug – nicht als Schlagwort.", proof: [{ value: "11+", label: "Jahre Software Engineering" }, { value: "100+", label: "ausgelieferte Web-Produkte" }, { value: "3", label: "Produktteams parallel" }, { value: "15", label: "geführte Engineers" }, { value: "3", label: "öffentliche Runtime-Pakete" }], mandateLabel: "Engineering über die gesamte Breite", mandateTitle: "Breite im Web. Tiefe im Mobile-Bereich. KI fest im Arbeitsablauf.", mandateBody: "Denis hat mit Websites, Shops, Admin-Tools, Rechnern, Payment- und Lead-Systemen angefangen. Später kamen Mobile-Plattformen und die Führung mehrerer Teams dazu. Heute ist KI Teil des Engineering-Zyklus – von Recherche und Prototyp bis zu Implementierung, Tests und Dokumentation –, die Verantwortung für das Ergebnis bleibt beim Menschen.", capabilityLabel: "Drei verbundene Stärken", capabilityTitle: "Ein Engineer für die ganze Strecke vom Interface bis zur Produktion.", capabilities: [
      { code: "WEB", title: "Web Product Engineering", body: "Frontend- und Produktarchitektur, E-Commerce, operative Oberflächen, Integrationen, Performance, Barrierefreiheit und die Auslieferungssysteme drumherum.", evidence: "100+ Web-Projekte · Studio-Gründer · AngularDart · aktuell React/Vinext" },
      { code: "MOB", title: "Mobile-Plattformen & Führung", body: "Flutter-Architektur, Kotlin/Swift-Grenzen, CI/CD, App-Stores, Observability, Release-Governance und die Führung mehrerer Teams.", evidence: "11+ Jahre gesamt · 6+ Jahre Flutter · 3 Teams · 80+ Releases" },
      { code: "AI", title: "KI-gestütztes Engineering", body: "KI für strukturierte Recherche, Lösungssuche, Produkt-Prototyping, Implementierung, Code Review, Testdesign und technische Dokumentation – nicht für ungeprüften Output.", evidence: "Agentische Workflows · schnelle Produkt-Slices · Verifikation vor Auslieferung" },
    ], careerTitle: "Vom Web über Mobile-Plattformen zum Engineering mit KI.", careerIntro: "Der Weg ist kumulativ: Breite aus Web-Produkten, Tiefe aus Mobile-Systemen, Engineering-Management und eine moderne, KI-gestützte Arbeitsweise, die schneller macht, ohne Verantwortung abzugeben." },
    work: { title: "Web-Produkte, Mobile-Plattformen und Auslieferungssysteme.", intro: "Ausgewählte Programme, in denen Denis für die Auslieferung, die Plattformqualität oder eine schwierige Systemgrenze verantwortlich war. Das Portfolio beginnt im Web Product Engineering und weitet sich auf Mobile-Architektur und die Verantwortung für mehrere Teams aus.", webCase: { label: "05 · Web Product Engineering", title: "Über 100 Web-Produkte vor dem Mobile-Kapitel", summary: "Fünf Jahre Fundament aus Websites, E-Commerce, operativen Panels, Rechnern, Payment-Integrationen und Lead-Generierungssystemen.", context: "Kleine und mittlere Unternehmen brauchten komplette digitale Produkte statt isolierter UI-Arbeit: Discovery, Umsetzung, Hosting, Integrationen und ein Weg zu messbarer Nutzung.", responsibility: "Gründete und führte ein Web-Studio mit zwei bis vier Personen und blieb hands-on in Frontend, Produktlogik, Integrationen, Auslieferung und Kundenkommunikation.", approach: "Baute verhältnismäßige Lösungen für Handel, Verwaltung, Payments, Berechnungen und Lead-Generierung und wählte jeweils die einfachste Architektur, die sich nach der Übergabe betreiben ließ.", outcome: "Über 100 kleine bis mittlere Web-Projekte zwischen 2015 und 2019 – das Fundament für die spätere Arbeit an Produkten, Plattformen und in der Engineering-Führung.", stack: "HTML/CSS, JavaScript, PHP, CMS- und Commerce-Plattformen, Payment-Integrationen, Analytics, Hosting, AngularDart" } },
    services: { title: "Senior Product Engineering für Web, Mobile und KI.", intro: "Holen Sie Denis dazu, wenn ein digitales Produkt belastbare Verantwortung über Interface, Architektur, Auslieferung, Produktion und die modernen KI-Workflows braucht, die jede dieser Phasen beschleunigen können.", additions: [
      { title: "Web Product Engineering & Modernisierung", signal: "Ein Web-Produkt muss von der Idee in die Produktion, oder ein bestehendes Frontend ist langsam, fragil oder schwer erweiterbar geworden.", action: "Klärt die Produktflüsse, schneidet Frontend- und Integrationsgrenzen neu, verbessert Barrierefreiheit und Performance und etabliert einen wartbaren Auslieferungspfad.", format: "Fokussierter Produktaufbau, Modernisierungssprint, Architektur-Review oder hands-on technische Führung." },
      { title: "Angewandte KI-Workflows & Produkt-Prototyping", signal: "Ein Team will echten Hebel durch KI, braucht aber mehr als Demos, Prompt-Sammlungen oder ungeprüft generierten Code.", action: "Entwirft einen Workflow mit Verifikation an erster Stelle – für Recherche, Prototyping, Implementierung, Tests, Dokumentation und Review – und belegt ihn mit einem produktionsnahen Produktausschnitt.", format: "Workflow-Assessment, Enablement-Sprint, schneller Produktprototyp oder Integration in ein bestehendes Engineering-System." },
    ] },
    about: { title: "Product Engineer, bevor es um ein einzelnes Framework geht.", intro: "Denis ist Engineering Manager und Hands-on-Engineer mit über 11 Jahren Erfahrung in Web-Produkten, Mobile-Plattformen, Open-Source-Runtimes und KI-gestützter Entwicklung.", paragraphs: ["Die Laufbahn begann im Web: ein kleines Studio, über 100 ausgelieferte Projekte, Shops, Admin-Systeme, Payments, Rechner und Lead-Strecken. Diese Breite hat den Blick fürs Produkt geschärft, lange vor Banking, Marktplätzen, Fintech und Flutter.", "Mobile brachte härtere Plattformgrenzen dazu: Kotlin- und Swift-Integration, Signierung, App-Stores, CI/CD, Observability, Incidents in Produktion und eine gemeinsame Architektur über mehrere Apps. Die Führungsrolle weitete diese Verantwortung später auf Team Leads, Roadmaps, Recruiting und drei parallele Teams aus.", "KI gehört heute zur Arbeitsweise. Denis nutzt sie, um Recherche zu verdichten, Architekturvarianten zu erkunden, Interfaces zu prototypen, Code zu schreiben und zu reviewen, Tests zu entwerfen und Dokumentation zu erstellen. Der Maßstab bleibt derselbe: Belege, explizite Trade-offs und ein Mensch, der für das verantwortlich ist, was in Produktion geht."] },
    contact: { title: "Kommen Sie mit dem echten Problem.", intro: "Ein Web-Produkt ohne Weg in die Produktion, ein Mobile-Release, der nicht stabil wird, ein Team mit unklarer Verantwortung oder ein KI-Workflow, der verlässliches Engineering werden muss." },
    finalTitle: "Ein digitales Produkt bauen, modernisieren oder wieder in Bewegung bringen?", finalBody: "Beschreiben Sie das eigentliche Problem – Web, Mobile, die Auslieferung im Team oder ein KI-Workflow, der produktionsreif werden muss.",
  },
  fr: {
    role: "Engineering Manager · Web, Mobile & AI Product Engineer", themeToDark: "Passer au thème sombre", themeToLight: "Passer au thème clair", docsCta: "Lire la documentation des packages",
    seo: { home: { title: "Engineering Manager · Web, Mobile & AI", description: "Denis Nadey : plus de 11 ans en produits web, plateformes mobiles, management d'équipes d'ingénierie, open source et développement assisté par l'IA." }, work: { title: "Web, Mobile & Engineering Leadership", description: "Réalisations de Denis Nadey : produits web, plateformes mobiles, fintech, processus de mise en production et open source." }, services: { title: "Ingénierie Flutter, web & IA", description: "Product engineering senior pour le web, Flutter, l'architecture, les processus de mise en production et des workflows IA concrets." }, about: { title: "Denis Nadey · Web, Mobile & AI", description: "Engineering Manager et product engineer hands-on : racines dans le web, expertise mobile approfondie et une pratique où l'IA fait partie du quotidien." }, contact: { title: "Contacter Denis Nadey", description: "Parlez à Denis Nadey d'un produit web ou mobile, d'un enjeu de management technique, d'un processus de mise en production ou d'un workflow IA concret." } },
    home: { titleLead: "Je construis des produits numériques – ", titleEmphasis: "du web et du mobile au développement assisté par l'IA.", intro: "Plus de 11 ans entre web, mobile et management d'ingénierie : 100+ projets web, des plateformes Flutter en production, plusieurs équipes en parallèle et l'IA utilisée comme un vrai outil d'ingénierie, pas comme un argument marketing.", proof: [{ value: "11+", label: "ans d'ingénierie logicielle" }, { value: "100+", label: "produits web livrés" }, { value: "3", label: "équipes produit en parallèle" }, { value: "15", label: "ingénieurs encadrés" }, { value: "3", label: "packages runtime publics" }], mandateLabel: "Ingénierie de bout en bout", mandateTitle: "L'étendue du web. La profondeur du mobile. L'IA dans la pratique.", mandateBody: "Denis a commencé par livrer des sites, des boutiques en ligne, des outils d'administration, des calculateurs, des paiements et des systèmes de génération de leads. Il est ensuite passé aux plateformes mobiles et au management de plusieurs équipes. Aujourd'hui, l'IA fait partie du cycle d'ingénierie – de la recherche et du prototypage à l'implémentation, aux tests et à la documentation –, mais la responsabilité du résultat reste humaine.", capabilityLabel: "Trois forces qui se complètent", capabilityTitle: "Un seul ingénieur, de l'interface jusqu'à la production.", capabilities: [
      { code: "WEB", title: "Web product engineering", body: "Architecture frontend et produit, e-commerce, interfaces opérationnelles, intégrations, performance, accessibilité et les systèmes de livraison qui les entourent.", evidence: "100+ projets web · fondateur de studio · AngularDart · stack React/Vinext actuelle" },
      { code: "MOB", title: "Plateformes mobiles et management", body: "Architecture Flutter, frontières Kotlin/Swift, CI/CD, stores, observabilité, gouvernance des releases et management de plusieurs équipes.", evidence: "11+ ans au total · 6+ ans de Flutter · 3 équipes · 80+ releases" },
      { code: "AI", title: "Ingénierie assistée par l'IA", body: "L'IA au service de la recherche structurée, de l'exploration de solutions, du prototypage produit, de l'implémentation, de la revue de code, de la conception des tests et de la documentation technique – jamais de la production non vérifiée.", evidence: "Workflows agentiques · tranches de produit rapides · vérification avant livraison" },
    ], careerTitle: "Du web aux plateformes mobiles – et maintenant à l'ingénierie avec l'IA.", careerIntro: "Une progression cumulative : l'étendue des produits web, la profondeur des systèmes mobiles, le management d'ingénierie et une pratique moderne assistée par l'IA, qui accélère sans diluer la responsabilité." },
    work: { title: "Produits web, plateformes mobiles et systèmes de mise en production.", intro: "Une sélection de programmes où Denis portait la responsabilité de la livraison, de la qualité de la plateforme ou d'une frontière technique difficile. Le portfolio commence par le web product engineering, puis s'étend à l'architecture mobile et à la responsabilité de plusieurs équipes.", webCase: { label: "05 · Web product engineering", title: "Plus de 100 produits web avant le chapitre mobile", summary: "Cinq ans de fondations : sites, e-commerce, panneaux d'administration, calculateurs, intégrations de paiement et systèmes de génération de leads.", context: "Les PME avaient besoin de produits numériques complets, pas d'un travail d'interface isolé : cadrage, implémentation, hébergement, intégrations et un chemin vers un usage mesurable.", responsibility: "A fondé et dirigé un studio web de deux à quatre personnes, en restant hands-on sur le frontend, la logique produit, les intégrations, la livraison et la relation client.", approach: "A construit des solutions proportionnées pour le commerce, l'administration, les paiements, les calculs et la génération de leads, en choisissant à chaque fois l'architecture la plus simple qui puisse être exploitée après la livraison.", outcome: "Plus de 100 projets web de petite et moyenne taille livrés entre 2015 et 2019 – le socle du travail produit, plateforme et management qui a suivi.", stack: "HTML/CSS, JavaScript, PHP, CMS et plateformes e-commerce, intégrations de paiement, analytics, hébergement, AngularDart" } },
    services: { title: "Product engineering senior pour le web, le mobile et l'IA.", intro: "Faites appel à Denis quand un produit numérique a besoin d'un responsable crédible sur l'interface, l'architecture, la livraison, la production et les workflows IA modernes capables d'accélérer chaque étape.", additions: [
      { title: "Web product engineering et modernisation", signal: "Un produit web doit passer de l'idée à la production, ou un frontend existant est devenu lent, fragile ou difficile à faire évoluer.", action: "Clarifie les parcours produit, redéfinit les frontières du frontend et des intégrations, améliore l'accessibilité et la performance, et met en place un chemin de livraison maintenable.", format: "Construction produit ciblée, sprint de modernisation, revue d'architecture ou direction technique hands-on." },
      { title: "Workflows IA appliqués et prototypage produit", signal: "Une équipe veut un vrai levier grâce à l'IA, mais a besoin de plus que des démos, des collections de prompts ou du code généré sans relecture.", action: "Conçoit un workflow où la vérification passe en premier – recherche, prototypage, implémentation, tests, documentation et revue – et le prouve sur une tranche de produit proche de la production.", format: "Évaluation du workflow, sprint d'accompagnement, prototype produit rapide ou intégration dans un système d'ingénierie existant." },
    ] },
    about: { title: "Product engineer avant d'être spécialiste d'un framework.", intro: "Denis est Engineering Manager et ingénieur hands-on, avec plus de 11 ans d'expérience en produits web, plateformes mobiles, runtimes open source et développement assisté par l'IA.", paragraphs: ["Le parcours commence dans le web : un petit studio, plus de 100 projets livrés, du e-commerce, des systèmes d'administration, des paiements, des calculateurs et des parcours de génération de leads. Cette étendue a forgé un regard produit bien avant la banque, les marketplaces, la fintech et Flutter.", "Le mobile a apporté des contraintes de plateforme plus dures : l'intégration Kotlin et Swift, la signature des apps, les stores, la CI/CD, l'observabilité, les incidents en production et une architecture partagée entre plusieurs applications. Le management a ensuite étendu cette responsabilité aux Team Leads, aux roadmaps, au recrutement et à trois équipes en parallèle.", "L'IA fait désormais partie de la méthode de travail. Denis s'en sert pour condenser la recherche, explorer des architectures, prototyper des interfaces, écrire et relire du code, concevoir des tests et produire de la documentation. L'exigence reste la même : des preuves, des arbitrages explicites et un humain responsable de ce qui part en production."] },
    contact: { title: "Venez avec le vrai problème.", intro: "Un produit web sans chemin vers la production, une release mobile qui ne se stabilise pas, une équipe aux responsabilités floues ou un workflow IA qui doit devenir de l'ingénierie fiable." },
    finalTitle: "Un produit numérique à construire, moderniser ou débloquer ?", finalBody: "Décrivez le vrai problème – web, mobile, organisation de l'équipe ou workflow IA qui doit devenir fiable en production.",
  },
  es: {
    role: "Engineering Manager · Web, Mobile & AI Product Engineer", themeToDark: "Cambiar a tema oscuro", themeToLight: "Cambiar a tema claro", docsCta: "Leer la documentación de los paquetes",
    seo: { home: { title: "Engineering Manager · Web, Mobile & AI", description: "Denis Nadey suma más de 11 años entre ingeniería de producto web, plataformas móviles, liderazgo de ingeniería, open source y entrega asistida por IA." }, work: { title: "Proyectos web, mobile y liderazgo de ingeniería", description: "Selección de proyectos de Denis Nadey en producto web, plataformas móviles, entrega, fintech e ingeniería open source." }, services: { title: "Servicios de ingeniería Flutter, web e IA", description: "Ingeniería de producto senior en web, Flutter, sistemas de entrega, arquitectura y flujos de trabajo prácticos con IA." }, about: { title: "Sobre Denis Nadey · Web, Mobile & AI", description: "Engineering Manager e ingeniero de producto hands-on: raíces en web, experiencia profunda en mobile y una práctica de entrega con IA nativa." }, contact: { title: "Contactar con Denis Nadey · Web, Mobile & AI", description: "Habla con Denis Nadey sobre un producto web o móvil, un reto de liderazgo de ingeniería, un sistema de entrega o un flujo de trabajo práctico con IA." } },
    home: { titleLead: "Construyo productos digitales – ", titleEmphasis: "de la web y el móvil a la entrega asistida por IA.", intro: "Más de once años entre web, móvil y liderazgo de ingeniería: más de 100 proyectos web, plataformas Flutter en producción, entrega con varios equipos y la IA como herramienta seria de ingeniería, no como adorno.", proof: [{ value: "11+", label: "años en ingeniería de software" }, { value: "100+", label: "productos web entregados" }, { value: "3", label: "equipos de producto en paralelo" }, { value: "15", label: "ingenieros a su cargo" }, { value: "3", label: "paquetes runtime públicos" }], mandateLabel: "Ingeniería de extremo a extremo", mandateTitle: "Amplitud web. Profundidad mobile. Ejecución con IA nativa.", mandateBody: "Denis empezó lanzando sitios web, sistemas de comercio electrónico, herramientas de administración, calculadoras, pagos y productos de captación de leads. Después pasó a las plataformas móviles y al liderazgo de varios equipos. Hoy la IA forma parte del ciclo de ingeniería – de la investigación y el prototipado a la implementación, los tests y la documentación – con el criterio humano como responsable último del resultado.", capabilityLabel: "Tres fortalezas conectadas", capabilityTitle: "Un mismo ingeniero de la interfaz a producción.", capabilities: [
      { code: "WEB", title: "Ingeniería de producto web", body: "Arquitectura de frontend y de producto, e-commerce, interfaces operativas, integraciones, rendimiento, accesibilidad y los sistemas de entrega que los rodean.", evidence: "100+ proyectos web · fundador de estudio · AngularDart · stack actual en React/Vinext" },
      { code: "MOB", title: "Plataformas móviles y liderazgo", body: "Arquitectura Flutter, fronteras con Kotlin/Swift, CI/CD, tiendas de aplicaciones, observabilidad, gobernanza de releases y liderazgo de varios equipos.", evidence: "11+ años en total · 6+ en Flutter · 3 equipos · 80+ releases" },
      { code: "AI", title: "Ingeniería asistida por IA", body: "IA aplicada a la investigación estructurada, la exploración de soluciones, el prototipado de producto, la implementación, la revisión de código, el diseño de tests y la documentación técnica – nunca como salida sin verificar.", evidence: "Flujos de trabajo agénticos · incrementos de producto rápidos · verificar antes de entregar" },
    ], careerTitle: "De la entrega web a las plataformas móviles – y ahora a una ingeniería moldeada por la IA.", careerIntro: "La progresión es acumulativa: amplitud en producto web, trabajo profundo en sistemas móviles, gestión de ingeniería y una práctica moderna asistida por IA que gana velocidad sin ceder la responsabilidad." },
    work: { title: "Proyectos en productos web, plataformas móviles y sistemas de entrega.", intro: "Una selección de programas en los que Denis fue responsable de la entrega, de la calidad de la plataforma o de una frontera difícil del sistema. El portafolio empieza en la ingeniería de producto web y crece hacia la arquitectura móvil y la responsabilidad sobre varios equipos.", webCase: { label: "05 · Ingeniería de producto web", title: "Más de 100 productos web antes del capítulo mobile", summary: "Cinco años de base en sitios web, e-commerce, paneles operativos, calculadoras, integraciones de pago y sistemas de captación de leads.", context: "Las pequeñas y medianas empresas necesitaban productos digitales completos, no piezas de UI aisladas: descubrimiento, implementación, hosting, integraciones y un camino hacia un uso medible.", responsibility: "Fundó y dirigió un estudio web de dos a cuatro personas y siguió hands-on en frontend, lógica de producto, integraciones, entrega y comunicación con clientes.", approach: "Construyó soluciones proporcionadas para comercio, administración, pagos, cálculo y captación de leads, eligiendo siempre la arquitectura más simple que pudiera operarse tras la entrega.", outcome: "Entregó más de 100 proyectos web pequeños y medianos entre 2015 y 2019 – la base del trabajo posterior en producto, plataforma y liderazgo de ingeniería.", stack: "HTML/CSS, JavaScript, PHP, CMS y plataformas de comercio, integraciones de pago, analítica, hosting, AngularDart" } },
    services: { title: "Ingeniería de producto senior en web, mobile e IA.", intro: "Cuenta con Denis cuando un producto digital necesita un responsable creíble de la interfaz, la arquitectura, la entrega, la producción y los flujos de trabajo con IA que pueden acelerar cada etapa.", additions: [
      { title: "Ingeniería y modernización de productos web", signal: "Un producto web tiene que pasar de idea a producción, o un frontend existente se ha vuelto lento, frágil o difícil de ampliar.", action: "Aclara los flujos del producto, redefine las fronteras del frontend y de las integraciones, mejora accesibilidad y rendimiento, y deja un camino de entrega mantenible.", format: "Construcción acotada del producto, sprint de modernización, revisión de arquitectura o liderazgo técnico hands-on." },
      { title: "Flujos de trabajo con IA aplicada y prototipado de producto", signal: "Un equipo quiere sacar partido real a la IA, pero necesita algo más que demos, colecciones de prompts o código generado sin revisar.", action: "Diseña un flujo de trabajo con la verificación por delante para investigación, prototipado, implementación, tests, documentación y revisión, y lo demuestra construyendo un fragmento real del producto con calidad de producción.", format: "Evaluación del flujo de trabajo, sprint de habilitación, prototipo rápido de producto o integración en un sistema de ingeniería existente." },
    ] },
    about: { title: "Ingeniero de producto por encima de cualquier framework.", intro: "Denis es Engineering Manager e ingeniero hands-on con más de 11 años de experiencia en productos web, plataformas móviles, runtimes open source y entrega asistida por IA.", paragraphs: ["La carrera empezó en la web: un estudio pequeño, más de 100 proyectos entregados, comercio electrónico, sistemas de administración, pagos, calculadoras y flujos de captación de leads. Esa amplitud formó una mentalidad de producto antes del salto a banca, marketplaces, fintech y Flutter.", "El trabajo en mobile añadió restricciones de plataforma más profundas – integración con Kotlin y Swift, firma, tiendas de aplicaciones, CI/CD, observabilidad, incidentes en producción y arquitectura compartida entre varias aplicaciones. Más tarde, el liderazgo amplió esa responsabilidad a los Team Leads, los roadmaps, la contratación y tres equipos en paralelo.", "La IA forma ya parte del método de trabajo. Denis la usa para comprimir la investigación, explorar arquitecturas, prototipar interfaces, implementar y revisar código, diseñar tests y producir documentación. El estándar no cambia: evidencias, trade-offs explícitos y una persona responsable de lo que llega a producción."] },
    contact: { title: "Cuéntame la restricción real del producto.", intro: "Un producto web que necesita llegar a producción, una release móvil que no se estabiliza, un equipo sin responsables claros o un flujo de trabajo con IA que tiene que convertirse en ingeniería fiable." },
    finalTitle: "¿Necesitas construir, modernizar o desbloquear un producto digital?", finalBody: "Cuéntame la restricción real: web, móvil, la entrega de tu equipo o un flujo de trabajo con IA que tiene que llegar a calidad de producción.",
  },
  it: {
    role: "Engineering Manager · Web, Mobile & AI Product Engineer", themeToDark: "Passa al tema scuro", themeToLight: "Passa al tema chiaro", docsCta: "Leggi la documentazione dei package",
    seo: { home: { title: "Engineering Manager · Web, Mobile & AI", description: "Denis Nadey porta oltre 11 anni di esperienza tra sviluppo di prodotti web, piattaforme mobile, leadership tecnica, open source e delivery assistita dall'AI." }, work: { title: "Progetti web, mobile e leadership tecnica", description: "Una selezione di progetti di Denis Nadey: prodotti web, piattaforme mobile, sistemi di delivery, fintech e open source." }, services: { title: "Servizi di ingegneria Flutter, web e AI", description: "Product engineering di livello senior su web, Flutter, sistemi di delivery, architettura e workflow AI applicati." }, about: { title: "Chi è Denis Nadey · Web, Mobile & AI", description: "Engineering Manager e product engineer hands-on: radici nel web, esperienza profonda nel mobile e una pratica di delivery AI-native." }, contact: { title: "Contatta Denis Nadey · Web, Mobile & AI", description: "Parla con Denis Nadey di un prodotto web o mobile, di una sfida di leadership tecnica, di un sistema di delivery o di un workflow AI concreto." } },
    home: { titleLead: "Costruisco prodotti digitali – ", titleEmphasis: "dal web e dal mobile alla delivery potenziata dall'AI.", intro: "Oltre undici anni tra web, mobile e leadership tecnica: più di 100 progetti web, piattaforme Flutter in produzione, delivery su più team e l'AI usata come un vero strumento di ingegneria – non come un'etichetta da esibire.", proof: [{ value: "11+", label: "anni di ingegneria del software" }, { value: "100+", label: "prodotti web realizzati" }, { value: "3", label: "team di prodotto in parallelo" }, { value: "15", label: "ingegneri guidati" }, { value: "3", label: "package runtime pubblici" }], mandateLabel: "Ingegneria a tutto campo", mandateTitle: "Ampiezza sul web. Profondità sul mobile. Esecuzione AI-native.", mandateBody: "Denis ha iniziato realizzando siti, sistemi di e-commerce, strumenti di amministrazione, calcolatori, pagamenti e prodotti di lead generation. Poi è passato alle piattaforme mobile e alla guida di più team. Oggi l'AI fa parte del ciclo di sviluppo – dalla ricerca al prototipo, fino a implementazione, test e documentazione – con il giudizio umano che resta responsabile del risultato.", capabilityLabel: "Tre punti di forza collegati", capabilityTitle: "Un solo ingegnere, dall'interfaccia alla produzione.", capabilities: [
      { code: "WEB", title: "Sviluppo di prodotti web", body: "Architettura frontend e di prodotto, e-commerce, interfacce operative, integrazioni, performance, accessibilità e i sistemi di delivery che li circondano.", evidence: "100+ progetti web · fondatore di uno studio · AngularDart · stack attuale React/Vinext" },
      { code: "MOB", title: "Piattaforme mobile e leadership", body: "Architettura Flutter, confini Kotlin/Swift, CI/CD, store, osservabilità, governance delle release e guida di più team.", evidence: "11+ anni in totale · 6+ in Flutter · 3 team · 80+ release" },
      { code: "AI", title: "Ingegneria assistita dall'AI", body: "L'AI usata per ricerca strutturata, esplorazione delle soluzioni, prototipazione di prodotto, implementazione, code review, progettazione dei test e documentazione tecnica – mai come output non verificato.", evidence: "Workflow agentici · slice di prodotto rapide · delivery verification-first" },
    ], careerTitle: "Dallo sviluppo web alle piattaforme mobile – e ora a un'ingegneria che integra l'AI.", careerIntro: "Una progressione cumulativa: l'ampiezza dei prodotti web, il lavoro profondo sui sistemi mobile, l'engineering management e una pratica moderna assistita dall'AI che aumenta la velocità senza cedere la responsabilità." },
    work: { title: "Progetti tra prodotti web, piattaforme mobile e sistemi di delivery.", intro: "Una selezione di programmi in cui Denis ha avuto la responsabilità della delivery, della qualità della piattaforma o di un confine di sistema difficile. Il portfolio parte dal prodotto web, poi si estende all'architettura mobile e alla responsabilità su più team.", webCase: { label: "05 · Sviluppo di prodotti web", title: "Più di 100 prodotti web prima del capitolo mobile", summary: "Cinque anni di fondamenta: siti, e-commerce, pannelli operativi, calcolatori, integrazioni di pagamento e sistemi di lead generation.", context: "Piccole e medie imprese avevano bisogno di prodotti digitali completi, non di interfacce isolate: analisi, implementazione, hosting, integrazioni e una strada verso un uso misurabile.", responsibility: "Ha fondato e guidato uno studio web di due-quattro persone, restando hands-on su frontend, logica di prodotto, integrazioni, delivery e rapporto con i clienti.", approach: "Ha costruito soluzioni proporzionate per commercio, amministrazione, pagamenti, calcoli e lead generation, scegliendo l'architettura più semplice che il cliente potesse gestire da solo dopo la consegna.", outcome: "Ha realizzato più di 100 progetti web di piccole e medie dimensioni tra il 2015 e il 2019 – la base del successivo lavoro su prodotto, piattaforma e leadership tecnica.", stack: "HTML/CSS, JavaScript, PHP, CMS e piattaforme e-commerce, integrazioni di pagamento, analytics, hosting, AngularDart" } },
    services: { title: "Product engineering senior su web, mobile e AI.", intro: "Coinvolgi Denis quando un prodotto digitale ha bisogno di una responsabilità credibile su interfaccia, architettura, delivery, produzione e sui moderni workflow AI che possono accelerare ogni fase.", additions: [
      { title: "Sviluppo e modernizzazione di prodotti web", signal: "Un prodotto web deve passare dall'idea alla produzione, oppure un frontend esistente è diventato lento, fragile o difficile da estendere.", action: "Chiarisce i flussi di prodotto, ridisegna i confini del frontend e delle integrazioni, migliora accessibilità e performance e imposta un percorso di delivery mantenibile.", format: "Build di prodotto mirata, sprint di modernizzazione, review dell'architettura o leadership tecnica hands-on." },
      { title: "Workflow AI applicati e prototipazione di prodotto", signal: "Un team vuole un vantaggio reale dall'AI, ma ha bisogno di più di demo, raccolte di prompt o codice generato senza review.", action: "Progetta un workflow verification-first per ricerca, prototipazione, implementazione, test, documentazione e review; poi lo dimostra costruendo una slice di prodotto con qualità da produzione.", format: "Assessment del workflow, sprint di abilitazione, prototipo rapido o integrazione in un sistema di engineering esistente." },
    ] },
    about: { title: "Un product engineer, prima di qualsiasi framework.", intro: "Denis è un Engineering Manager e un ingegnere hands-on con oltre 11 anni di esperienza tra prodotti web, piattaforme mobile, runtime open source e delivery assistita dall'AI.", paragraphs: ["La carriera è iniziata nel web: un piccolo studio, più di 100 progetti realizzati, e-commerce, sistemi di amministrazione, pagamenti, calcolatori e flussi di lead generation. Quell'ampiezza ha formato una mentalità di prodotto prima del passaggio a banking, marketplace, fintech e Flutter.", "Il mobile ha aggiunto vincoli di piattaforma più profondi – integrazione Kotlin e Swift, signing, store, CI/CD, osservabilità, incidenti in produzione e un'architettura condivisa tra più applicazioni. La leadership ha poi esteso quella responsabilità ai Team Lead, alle roadmap, alle assunzioni e a tre team in parallelo.", "Oggi l'AI fa parte del metodo di lavoro. Denis la usa per comprimere la ricerca, esplorare architetture, prototipare interfacce, implementare e revisionare codice, progettare test e produrre documentazione. Lo standard resta lo stesso: fatti verificabili, trade-off espliciti e un responsabile umano per ciò che arriva in produzione."] },
    contact: { title: "Raccontami il vero vincolo di prodotto.", intro: "Un prodotto web che deve arrivare in produzione, una release mobile che non si stabilizza, un team con responsabilità poco chiare o un workflow AI che deve diventare ingegneria affidabile." },
    finalTitle: "Devi costruire, modernizzare o sbloccare un prodotto digitale?", finalBody: "Raccontami il vincolo reale – web, mobile, delivery del team o un workflow AI che deve diventare pronto per la produzione.",
  },
  pl: {
    role: "Engineering Manager · Web, Mobile & AI Product Engineer", themeToDark: "Przełącz na ciemny motyw", themeToLight: "Przełącz na jasny motyw", docsCta: "Przeczytaj dokumentację pakietów",
    seo: { home: { title: "Engineering Manager · Web, Mobile & AI", description: "Denis Nadey: ponad 11 lat w produktach webowych, platformach mobilnych, kierowaniu zespołami, open source i delivery wspieranym przez AI." }, work: { title: "Projekty · Web, Mobile & Engineering Leadership", description: "Wybrane projekty Denisa Nadeya: produkty webowe, platformy mobilne, delivery, fintech i open source." }, services: { title: "Usługi · Flutter, Web & AI Engineering", description: "Inżynieria produktu na poziomie senior: web, Flutter, systemy delivery, architektura i praktyczne workflow z AI." }, about: { title: "O Denisie Nadeyu · Web, Mobile & AI", description: "Engineering Manager i hands-on inżynier produktu: korzenie w webie, głębokie doświadczenie w mobile i praktyka delivery oparta na AI." }, contact: { title: "Kontakt z Denisem Nadeyem · Web, Mobile & AI", description: "Porozmawiaj z Denisem Nadeyem o produkcie webowym lub mobilnym, wyzwaniu w kierowaniu zespołem, systemie delivery albo praktycznym workflow AI." } },
    home: { titleLead: "Buduję produkty cyfrowe – ", titleEmphasis: "od web i mobile po delivery wspierane przez AI.", intro: "Ponad jedenaście lat w webie, mobile i kierowaniu zespołami: 100+ projektów webowych, produkcyjne platformy Flutter, delivery w kilku zespołach naraz i AI jako poważne narzędzie inżynierskie – a nie ozdobnik.", proof: [{ value: "11+", label: "lat w inżynierii oprogramowania" }, { value: "100+", label: "dostarczonych produktów webowych" }, { value: "3", label: "równoległe zespoły produktowe" }, { value: "15", label: "prowadzonych inżynierów" }, { value: "3", label: "publiczne pakiety runtime" }], mandateLabel: "Pełne spektrum inżynierii", mandateTitle: "Szeroko w web. Głęboko w mobile. AI-native w realizacji.", mandateBody: "Denis zaczynał od stron internetowych, systemów e-commerce, paneli administracyjnych, kalkulatorów, płatności i produktów do generowania leadów. Potem przeszedł do platform mobilnych i kierowania kilkoma zespołami. Dziś AI jest częścią pętli inżynierskiej – od researchu i prototypowania po implementację, testy i dokumentację – a za wynik wciąż odpowiada człowiek.", capabilityLabel: "Trzy powiązane mocne strony", capabilityTitle: "Jeden inżynier na całej drodze od interfejsu do produkcji.", capabilities: [
      { code: "WEB", title: "Inżynieria produktów webowych", body: "Architektura frontendu i produktu, e-commerce, interfejsy operacyjne, integracje, wydajność, dostępność i otaczające je systemy delivery.", evidence: "100+ projektów webowych · założyciel studia · AngularDart · obecny stack React/Vinext" },
      { code: "MOB", title: "Platformy mobilne i kierowanie zespołami", body: "Architektura Flutter, granice Kotlin/Swift, CI/CD, sklepy z aplikacjami, obserwowalność, zarządzanie release'ami i prowadzenie kilku zespołów naraz.", evidence: "11+ lat łącznie · 6+ we Flutterze · 3 zespoły · 80+ release'ów" },
      { code: "AI", title: "Inżynieria wspierana przez AI", body: "AI do ustrukturyzowanego researchu, eksploracji rozwiązań, prototypowania produktu, implementacji, code review, projektowania testów i dokumentacji technicznej – nigdy jako niesprawdzony output.", evidence: "Agentowe workflow · szybkie wycinki produktu · najpierw weryfikacja, potem delivery" },
    ], careerTitle: "Od projektów webowych, przez platformy mobilne – po inżynierię kształtowaną dziś przez AI.", careerIntro: "Każdy etap dokłada się do poprzedniego: szerokość produktów webowych, głęboka praca nad systemami mobilnymi, zarządzanie inżynierią i nowoczesna praktyka z AI, która przyspiesza pracę, nie oddając nikomu odpowiedzialności." },
    work: { title: "Projekty: produkty webowe, platformy mobilne i systemy delivery.", intro: "Wybrane programy, w których Denis odpowiadał za delivery, jakość platformy albo trudną granicę systemu. Portfolio zaczyna się od inżynierii produktów webowych, a potem rozszerza na architekturę mobile i odpowiedzialność za kilka zespołów.", webCase: { label: "05 · Inżynieria produktów webowych", title: "Ponad 100 produktów webowych przed rozdziałem mobile", summary: "Pięcioletni fundament: strony internetowe, e-commerce, panele operacyjne, kalkulatory, integracje płatności i systemy generowania leadów.", context: "Małe i średnie firmy potrzebowały kompletnych produktów cyfrowych, a nie samego UI: discovery, implementacji, hostingu, integracji i drogi do mierzalnego użycia.", responsibility: "Założył i prowadził studio webowe liczące od dwóch do czterech osób, pozostając hands-on we frontendzie, logice produktu, integracjach, delivery i komunikacji z klientem.", approach: "Budował rozwiązania na miarę – dla handlu, administracji, płatności, obliczeń i generowania leadów – wybierając najprostszą architekturę, którą da się utrzymać po przekazaniu.", outcome: "Zrealizował ponad 100 małych i średnich projektów webowych w latach 2015–2019 – fundament późniejszej pracy produktowej, platformowej i kierowania zespołami.", stack: "HTML/CSS, JavaScript, PHP, platformy CMS i e-commerce, integracje płatności, analityka, hosting, AngularDart" } },
    services: { title: "Inżynieria produktu na poziomie senior – web, mobile i AI.", intro: "Zaproś Denisa, gdy produkt cyfrowy potrzebuje kogoś, kto wiarygodnie weźmie odpowiedzialność za interfejs, architekturę, delivery, produkcję i nowoczesne workflow AI, które mogą przyspieszyć każdy z tych etapów.", additions: [
      { title: "Inżynieria i modernizacja produktów webowych", signal: "Produkt webowy ma przejść od pomysłu do produkcji albo istniejący frontend zrobił się wolny, kruchy i trudny do rozbudowy.", action: "Porządkuje przepływy produktowe, przebudowuje granice frontendu i integracji, poprawia dostępność i wydajność oraz ustawia utrzymywalną ścieżkę delivery.", format: "Skupiona budowa produktu, sprint modernizacyjny, przegląd architektury albo hands-on przywództwo techniczne." },
      { title: "Praktyczne workflow AI i prototypowanie produktu", signal: "Zespół chce realnie skorzystać na AI, ale potrzebuje czegoś więcej niż demo, zbiorów promptów i niesprawdzonego wygenerowanego kodu.", action: "Projektuje workflow z weryfikacją na pierwszym miejscu – dla researchu, prototypowania, implementacji, testów, dokumentacji i review – i buduje wycinek produktu o produkcyjnej jakości, który to udowadnia.", format: "Ocena workflow, sprint wdrożeniowy dla zespołu, szybki prototyp produktu albo integracja z istniejącym systemem inżynierskim." },
    ] },
    about: { title: "Najpierw inżynier produktu, dopiero potem framework.", intro: "Denis jest Engineering Managerem i hands-on inżynierem z ponad 11 latami doświadczenia w produktach webowych, platformach mobilnych, runtime'ach open source i delivery wspieranym przez AI.", paragraphs: ["Kariera zaczęła się w webie: małe studio, ponad 100 zrealizowanych projektów, e-commerce, systemy administracyjne, płatności, kalkulatory i procesy generowania leadów. Ta szerokość zbudowała myślenie produktowe, zanim przyszły bankowość, marketplace'y, fintech i Flutter.", "Praca w mobile dołożyła głębsze ograniczenia platformy – integracje w Kotlinie i Swifcie, podpisywanie aplikacji, sklepy, CI/CD, obserwowalność, incydenty produkcyjne i wspólną architekturę dla wielu aplikacji. Rola lidera rozszerzyła później tę odpowiedzialność na Team Leadów, roadmapy, rekrutację i trzy równoległe zespoły.", "AI jest dziś częścią metody pracy. Denis wykorzystuje AI, by skrócić research, przetestować warianty architektury, prototypować interfejsy, pisać i przeglądać kod, projektować testy i tworzyć dokumentację. Standard się nie zmienia: dowody, jawne kompromisy i człowiek odpowiedzialny za to, co trafia na produkcję."] },
    contact: { title: "Przyjdź z prawdziwym problemem produktu.", intro: "Produkt webowy bez drogi na produkcję, release mobilny, który nie chce się ustabilizować, zespół z niejasną odpowiedzialnością albo workflow AI, który musi stać się rzetelną inżynierią." },
    finalTitle: "Chcesz zbudować, zmodernizować albo odblokować produkt cyfrowy?", finalBody: "Przyjdź z prawdziwym problemem – web, mobile, delivery zespołu albo workflow AI, który ma dojrzeć do produkcji.",
  },
  pt: {
    role: "Engineering Manager · Web, Mobile & AI Product Engineer",
    themeToDark: "Mudar para o tema escuro",
    themeToLight: "Mudar para o tema claro",
    docsCta: "Ler a documentação dos pacotes",
    seo: {
      home: { title: "Engineering Manager · Web, Mobile & AI", description: "Denis Nadey reúne 11+ anos em engenharia de produtos web, plataformas mobile, liderança de engenharia, open source e entrega assistida por IA." },
      work: { title: "Projetos em Web, Mobile e Liderança de Engenharia", description: "Projetos selecionados de Denis Nadey em produtos web, plataformas mobile, entrega, fintech e engenharia open source." },
      services: { title: "Serviços de engenharia Flutter, web e IA", description: "Engenharia de produto sênior em web, Flutter, sistemas de entrega, arquitetura e fluxos de trabalho práticos com IA." },
      about: { title: "Sobre Denis Nadey · Web, Mobile & AI", description: "Engineering Manager e engenheiro de produto hands-on, com raízes na web, experiência profunda em mobile e uma prática de entrega nativa em IA." },
      contact: { title: "Fale com Denis Nadey · Web, Mobile & AI", description: "Converse com Denis Nadey sobre um produto web ou mobile, um desafio de liderança de engenharia, um sistema de entrega ou um fluxo de trabalho prático com IA." },
    },
    home: {
      titleLead: "Construo produtos digitais – ",
      titleEmphasis: "da web e do mobile à entrega assistida por IA.",
      intro: "Mais de onze anos entre web, mobile e liderança de engenharia: 100+ projetos web, plataformas Flutter em produção, entrega com vários times e IA usada como ferramenta séria de engenharia – não como enfeite.",
      proof: [{ value: "11+", label: "anos em engenharia de software" }, { value: "100+", label: "produtos web entregues" }, { value: "3", label: "times de produto em paralelo" }, { value: "15", label: "engenheiros liderados" }, { value: "3", label: "pacotes runtime públicos" }],
      mandateLabel: "Engenharia de ponta a ponta",
      mandateTitle: "Amplitude web. Profundidade mobile. Execução nativa em IA.",
      mandateBody: "Denis começou entregando sites, sistemas de e-commerce, ferramentas administrativas, calculadoras, pagamentos e produtos de geração de leads. Depois migrou para plataformas mobile e liderança de vários times. Hoje a IA faz parte do ciclo de engenharia – da pesquisa e prototipagem à implementação, testes e documentação – com o julgamento humano respondendo pelo resultado.",
      capabilityLabel: "Três forças conectadas",
      capabilityTitle: "Um único engenheiro dos dois lados da fronteira do produto.",
      capabilities: [
        { code: "WEB", title: "Engenharia de produtos web", body: "Arquitetura de frontend e de produto, e-commerce, interfaces operacionais, integrações, performance, acessibilidade e os sistemas de entrega ao redor de tudo isso.", evidence: "100+ projetos web · fundador de estúdio · AngularDart · stack atual em React/Vinext" },
        { code: "MOB", title: "Plataformas mobile e liderança", body: "Arquitetura Flutter, fronteiras com Kotlin/Swift, CI/CD, lojas de aplicativos, observabilidade, governança de release e liderança de vários times.", evidence: "11+ anos no total · 6+ em Flutter · 3 times · 80+ releases" },
        { code: "AI", title: "Engenharia assistida por IA", body: "IA usada para pesquisa estruturada, exploração de soluções, prototipagem de produto, implementação, revisão de código, desenho de testes e documentação técnica – nunca como saída sem verificação.", evidence: "Fluxos de trabalho agênticos · fatias rápidas de produto · verificação antes da entrega" },
      ],
      careerTitle: "Da entrega web às plataformas mobile – e agora uma engenharia moldada pela IA.",
      careerIntro: "A progressão é cumulativa: amplitude em produtos web, trabalho profundo em sistemas mobile, gestão de engenharia e uma prática moderna assistida por IA que aumenta a velocidade sem abrir mão da responsabilidade.",
    },
    work: {
      title: "Projetos em produtos web, plataformas mobile e sistemas de entrega.",
      intro: "Programas selecionados em que Denis foi responsável pela entrega, pela qualidade da plataforma ou por uma fronteira difícil do sistema. O portfólio começa na engenharia de produtos web e se expande para arquitetura mobile e responsabilidade por vários times.",
      webCase: { label: "05 · Engenharia de produtos web", title: "Mais de 100 produtos web antes do capítulo mobile", summary: "Cinco anos de base em sites, e-commerce, painéis operacionais, calculadoras, integrações de pagamento e sistemas de geração de leads.", context: "Pequenas e médias empresas precisavam de produtos digitais completos, não de trabalho isolado de UI: descoberta, implementação, hospedagem, integrações e um caminho até o uso mensurável.", responsibility: "Fundou e liderou um estúdio web de duas a quatro pessoas e continuou hands-on em frontend, lógica de produto, integrações, entrega e comunicação com clientes.", approach: "Construiu soluções proporcionais para comércio, administração, pagamentos, cálculos e geração de leads, escolhendo a arquitetura mais simples que pudesse ser operada depois da entrega.", outcome: "Entregou mais de 100 projetos web de pequeno e médio porte entre 2015 e 2019 – a base para o trabalho posterior em produto, plataforma e liderança de engenharia.", stack: "HTML/CSS, JavaScript, PHP, CMS e plataformas de e-commerce, integrações de pagamento, analytics, hospedagem, AngularDart" },
    },
    services: {
      title: "Engenharia de produto sênior em web, mobile e IA.",
      intro: "Chame Denis quando um produto digital precisa de alguém que responda, com credibilidade, por interface, arquitetura, entrega, produção e pelos fluxos de trabalho modernos com IA que podem acelerar cada etapa.",
      additions: [
        { title: "Engenharia e modernização de produtos web", signal: "Um produto web precisa sair da ideia e chegar à produção, ou um frontend existente ficou lento, frágil ou difícil de estender.", action: "Esclarece os fluxos do produto, redesenha as fronteiras de frontend e de integração, melhora acessibilidade e performance e estabelece um caminho de entrega sustentável.", format: "Construção focada de produto, sprint de modernização, revisão de arquitetura ou liderança técnica hands-on." },
        { title: "Fluxos de trabalho com IA aplicada e prototipagem de produto", signal: "O time quer ganho real com IA, mas precisa de mais do que demos, coleções de prompts ou código gerado sem revisão.", action: "Desenha um fluxo de trabalho com verificação em primeiro lugar para pesquisa, prototipagem, implementação, testes, documentação e revisão; constrói uma fatia com cara de produção para provar que funciona.", format: "Avaliação do fluxo de trabalho, sprint de habilitação, protótipo rápido de produto ou integração a um sistema de engenharia existente." },
      ],
    },
    about: {
      title: "Engenheiro de produto antes de qualquer framework.",
      intro: "Denis é Engineering Manager e engenheiro hands-on, com 11+ anos entre produtos web, plataformas mobile, runtimes open source e entrega assistida por IA.",
      paragraphs: [
        "A carreira começou na web: um estúdio pequeno, mais de 100 projetos entregues, e-commerce, sistemas administrativos, pagamentos, calculadoras e fluxos de geração de leads. Essa amplitude formou uma mentalidade de produto antes da passagem por banco, marketplaces, fintech e Flutter.",
        "O mobile trouxe restrições de plataforma mais profundas – integração com Kotlin e Swift, assinatura do app, lojas de aplicativos, CI/CD, observabilidade, incidentes em produção e arquitetura compartilhada entre vários aplicativos. Mais tarde, a liderança estendeu essa responsabilidade a Team Leads, roadmaps, contratação e três times em paralelo.",
        "A IA hoje faz parte do método de trabalho. Denis a usa para comprimir pesquisa, explorar arquiteturas, prototipar interfaces, implementar e revisar código, desenhar testes e produzir documentação. O padrão continua o mesmo: evidência, trade-offs explícitos e uma pessoa responsável pelo que chega à produção.",
      ],
    },
    contact: { title: "Traga a restrição real do produto.", intro: "Um produto web que precisa de um caminho até a produção, uma release mobile que não estabiliza, um time sem responsabilidades claras ou um fluxo de trabalho com IA que precisa virar engenharia confiável." },
    finalTitle: "Precisa construir, modernizar ou destravar um produto digital?",
    finalBody: "Traga a restrição real – web, mobile, entrega do time ou um fluxo de trabalho com IA que precisa ficar pronto para produção.",
  },
  ka: {
    role: "Engineering Manager · Web, Mobile & AI Product Engineer", themeToDark: "მუქ თემაზე გადართვა", themeToLight: "ღია თემაზე გადართვა", docsCta: "პაკეტების დოკუმენტაციის წაკითხვა",
    seo: { home: { title: "Engineering Manager · Web, Mobile და AI", description: "დენის ნადეი: 11+ წელი ვებპროდუქტებში, მობილურ პლატფორმებში, საინჟინრო გუნდების ხელმძღვანელობაში, open source-სა და AI-ით გაძლიერებულ მიწოდებაში." }, work: { title: "პროექტები · Web, Mobile და საინჟინრო ხელმძღვანელობა", description: "დენის ნადეის შერჩეული პროექტები: ვებპროდუქტები, მობილური პლატფორმები, მიწოდების სისტემები, fintech და open source." }, services: { title: "Flutter, Web და AI საინჟინრო სერვისები", description: "სენიორ დონის პროდუქტული ინჟინერია: ვები, Flutter, მიწოდების სისტემები, არქიტექტურა და პრაქტიკული AI სამუშაო პროცესები." }, about: { title: "დენის ნადეის შესახებ · Web, Mobile და AI", description: "Engineering Manager და hands-on პროდუქტული ინჟინერი — ვების საფუძველი, მობილური პლატფორმების ღრმა გამოცდილება და AI-ზე აგებული მიწოდების პრაქტიკა." }, contact: { title: "დაუკავშირდით დენის ნადეის · Web, Mobile და AI", description: "განიხილეთ დენის ნადეისთან ვებ- ან მობილური პროდუქტი, საინჟინრო ხელმძღვანელობის გამოწვევა, მიწოდების სისტემა ან პრაქტიკული AI სამუშაო პროცესი." } },
    home: {
      titleLead: "ვქმნი ციფრულ პროდუქტებს — ", titleEmphasis: "ვებიდან და მობილურიდან AI-ით გაძლიერებულ მიწოდებამდე.", intro: "11+ წელი ვებში, მობილურ მიმართულებასა და საინჟინრო ხელმძღვანელობაში: 100-ზე მეტი ვებპროექტი, პროდაქშენში მომუშავე Flutter-პლატფორმები, რამდენიმე გუნდის პარალელური მიწოდება და ხელოვნური ინტელექტი (AI) როგორც სერიოზული საინჟინრო ინსტრუმენტი და არა მოსაჩვენებელი იარლიყი.",
      proof: [{ value: "11+", label: "წელი პროგრამულ ინჟინერიაში" }, { value: "100+", label: "მიწოდებული ვებპროდუქტი" }, { value: "3", label: "პარალელური პროდუქტული გუნდი" }, { value: "15", label: "ინჟინერი ხელმძღვანელობის ქვეშ" }, { value: "3", label: "საჯარო runtime პაკეტი" }],
      mandateLabel: "სრული სპექტრის ინჟინერია", mandateTitle: "ვებში — სიგანე. მობილურში — სიღრმე. AI — მუშაობის ბუნებრივი ნაწილი.", mandateBody: "დენისმა კარიერა ვებსაიტების, კომერციული სისტემების, ადმინისტრაციული ინსტრუმენტების, კალკულატორების, გადახდებისა და ლიდების გენერაციის პროდუქტების გამოშვებით დაიწყო. მოგვიანებით მობილურ პლატფორმებსა და რამდენიმე გუნდის ხელმძღვანელობაზე გადავიდა. დღეს AI საინჟინრო ციკლის ნაწილია — კვლევიდან და პროტოტიპირებიდან იმპლემენტაციამდე, ტესტებამდე და დოკუმენტაციამდე — შედეგზე პასუხისმგებლობა კი ადამიანის განსჯას რჩება.",
      capabilityLabel: "სამი ურთიერთდაკავშირებული ძლიერი მხარე", capabilityTitle: "ერთი ინჟინერი მთელ გზაზე — ინტერფეისიდან პროდაქშენამდე.", capabilities: [
        { code: "WEB", title: "ვებპროდუქტების ინჟინერია", body: "ფრონტენდისა და პროდუქტის არქიტექტურა, ელექტრონული კომერცია, საოპერაციო ინტერფეისები, ინტეგრაციები, წარმადობა, ხელმისაწვდომობა და მათ გარშემო არსებული მიწოდების სისტემები.", evidence: "100+ ვებპროექტი · სტუდიის დამფუძნებელი · AngularDart · მიმდინარე React/Vinext სტეკი" },
        { code: "MOB", title: "მობილური პლატფორმები და ხელმძღვანელობა", body: "Flutter-არქიტექტურა, Kotlin/Swift საზღვრები, CI/CD, აპლიკაციების მაღაზიები, დაკვირვებადობა, რელიზების მართვა და რამდენიმე გუნდის ხელმძღვანელობა.", evidence: "11+ წელი სულ · 6+ Flutter · 3 გუნდი · 80+ რელიზი" },
        { code: "AI", title: "AI-ით გაძლიერებული ინჟინერია", body: "AI სტრუქტურირებული კვლევისთვის, გადაწყვეტების შესწავლისთვის, პროდუქტის პროტოტიპირებისთვის, იმპლემენტაციისთვის, კოდის რევიუსთვის, ტესტების დაპროექტებისა და ტექნიკური დოკუმენტაციისთვის — და არა შეუმოწმებელი შედეგებისთვის.", evidence: "აგენტური სამუშაო პროცესები · პროდუქტის სწრაფი ფრაგმენტები · ვერიფიკაციაზე აგებული მიწოდება" },
      ], careerTitle: "ვებპროდუქტების მიწოდებიდან მობილურ პლატფორმებამდე — და დღეს უკვე AI-ზე დაფუძნებულ ინჟინერიამდე.", careerIntro: "ეს გზა დაგროვებითია — თითოეული ეტაპი წინას ეყრდნობა: ვებპროდუქტების ფართო გამოცდილება, მობილურ სისტემებზე ღრმა მუშაობა, საინჟინრო მენეჯმენტი და თანამედროვე, AI-ით გაძლიერებული პრაქტიკა, რომელიც სიჩქარეს ზრდის და პასუხისმგებლობას არავის გადააბარებს.",
    },
    work: { title: "ვებპროდუქტები, მობილური პლატფორმები და მიწოდების სისტემები.", intro: "შერჩეული პროგრამები, სადაც დენისი პასუხს აგებდა მიწოდებაზე, პლატფორმის ხარისხზე ან სისტემის რთულ საზღვარზე. პორტფელი ვებპროდუქტების ინჟინერიით იწყება და მობილურ არქიტექტურასა და რამდენიმე გუნდის პასუხისმგებლობამდე ფართოვდება.", webCase: { label: "05 · ვებპროდუქტების ინჟინერია", title: "100-ზე მეტი ვებპროდუქტი მობილურ ეტაპამდე", summary: "ხუთწლიანი საფუძველი: ვებსაიტები, ელექტრონული კომერცია, საოპერაციო პანელები, კალკულატორები, გადახდის ინტეგრაციები და ლიდების გენერაციის სისტემები.", context: "მცირე და საშუალო ბიზნესს სრული ციფრული პროდუქტები სჭირდებოდა და არა იზოლირებული ინტერფეისის სამუშაო: მოთხოვნების კვლევა, იმპლემენტაცია, ჰოსტინგი, ინტეგრაციები და გზა გაზომვად გამოყენებამდე.", responsibility: "დააფუძნა და ხელმძღვანელობდა 2–4-კაციან ვებსტუდიას; პირადად აგრძელებდა მუშაობას ფრონტენდზე, პროდუქტის ლოგიკაზე, ინტეგრაციებზე, მიწოდებასა და დამკვეთებთან კომუნიკაციაზე.", approach: "ქმნიდა ამოცანის მასშტაბის შესაბამის გადაწყვეტებს კომერციისთვის, ადმინისტრირებისთვის, გადახდებისთვის, გამოთვლებისა და ლიდების გენერაციისთვის და ირჩევდა უმარტივეს არქიტექტურას, რომლის მართვაც გადაცემის შემდეგაც შესაძლებელი იქნებოდა.", outcome: "2015–2019 წლებში დამკვეთებს 100-ზე მეტი მცირე და საშუალო ვებპროექტი მიაწოდა — საფუძველი შემდგომი პროდუქტული, პლატფორმული და საინჟინრო ხელმძღვანელობის სამუშაოსთვის.", stack: "HTML/CSS, JavaScript, PHP, CMS და კომერციული პლატფორმები, გადახდის ინტეგრაციები, ანალიტიკა, ჰოსტინგი, AngularDart" } },
    services: { title: "სენიორ დონის პროდუქტული ინჟინერია — ვები, მობილური და AI.", intro: "ჩართეთ დენისი, როცა ციფრულ პროდუქტს ერთი სანდო პასუხისმგებელი სჭირდება ინტერფეისისთვის, არქიტექტურისთვის, მიწოდებისთვის, პროდაქშენისა და თანამედროვე AI სამუშაო პროცესებისთვის, რომლებსაც თითოეული ეტაპის დაჩქარება შეუძლია.", additions: [
      { title: "ვებპროდუქტების ინჟინერია და მოდერნიზაცია", signal: "ვებპროდუქტი იდეიდან პროდაქშენამდე უნდა მივიდეს, ან არსებული ფრონტენდი ნელი, მყიფე და რთულად გასაფართოებელი გახდა.", action: "აზუსტებს პროდუქტის პროცესებს, თავიდან აყალიბებს ფრონტენდისა და ინტეგრაციების საზღვრებს, აუმჯობესებს ხელმისაწვდომობასა და წარმადობას და ქმნის მიწოდების მართვად გზას.", format: "ფოკუსირებული პროდუქტის აშენება, მოდერნიზაციის სპრინტი, არქიტექტურის განხილვა ან hands-on ტექნიკური ხელმძღვანელობა." },
      { title: "გამოყენებითი AI სამუშაო პროცესები და პროდუქტის პროტოტიპირება", signal: "გუნდს AI-სგან რეალური სარგებელი სურს და არა დემოები, პრომპტების კოლექციები ან გადაუხედავი გენერირებული კოდი.", action: "აპროექტებს ვერიფიკაციაზე აგებულ სამუშაო პროცესს კვლევის, პროტოტიპირების, იმპლემენტაციის, ტესტირების, დოკუმენტაციისა და რევიუსთვის; შემდეგ პროდაქშენთან მიახლოებული ფრაგმენტით ამტკიცებს, რომ ის მუშაობს.", format: "სამუშაო პროცესის შეფასება, დანერგვის სპრინტი, პროდუქტის სწრაფი პროტოტიპი ან ინტეგრაცია არსებულ საინჟინრო სისტემაში." },
    ] },
    about: { title: "უპირველესად პროდუქტული ინჟინერი და არა ერთი ფრეიმვორკის მიმდევარი.", intro: "დენისი Engineering Manager-ი და hands-on ინჟინერია 11+ წლიანი გამოცდილებით, რომელიც ვებპროდუქტებს, მობილურ პლატფორმებს, open-source runtime-ებსა და AI-ით გაძლიერებულ მიწოდებას მოიცავს.", paragraphs: ["კარიერა ვებში დაიწყო: პატარა სტუდია, 100-ზე მეტი მიწოდებული პროექტი, ელექტრონული კომერცია, ადმინისტრაციული სისტემები, გადახდები, კალკულატორები და ლიდების გენერაციის პროცესები. ამ სიგანემ პროდუქტული აზროვნება ჩამოაყალიბა მანამ, სანამ საბანკო სფეროში, marketplace-ებში, fintech-სა და Flutter-ში გადავიდოდა.", "მობილურმა მიმართულებამ პლატფორმის უფრო ღრმა შეზღუდვები დაამატა — Kotlin-ისა და Swift-ის ინტეგრაცია, ხელმოწერა, აპლიკაციების მაღაზიები, CI/CD, დაკვირვებადობა, პროდაქშენის ინციდენტები და რამდენიმე აპლიკაციის საერთო არქიტექტურა. მოგვიანებით ხელმძღვანელობამ ეს პასუხისმგებლობა Team Lead-ებზე, საგზაო რუკებზე, დაქირავებასა და სამ პარალელურ გუნდზე გააფართოვა.", "ხელოვნური ინტელექტი (AI) ახლა სამუშაო მეთოდის ნაწილია. დენისი მას იყენებს კვლევის შესამოკლებლად, არქიტექტურების შესასწავლად, ინტერფეისების პროტოტიპირებისთვის, კოდის დასაწერად და გადასახედად, ტესტების დასაპროექტებლად და დოკუმენტაციის შესაქმნელად. სტანდარტი იგივე რჩება: მტკიცებულებები, მკაფიო კომპრომისები და ადამიანი, რომელიც პასუხს აგებს ყველაფერზე, რაც პროდაქშენში გადის."] },
    contact: { title: "მოგვიყევით პროდუქტის რეალურ პრობლემაზე.", intro: "ვებპროდუქტი, რომელსაც პროდაქშენამდე გზა სჭირდება; მობილური რელიზი, რომელიც ვერ სტაბილურდება; გუნდი ბუნდოვანი პასუხისმგებლობით; ან AI სამუშაო პროცესი, რომელიც საიმედო ინჟინერიად უნდა იქცეს." },
    finalTitle: "გჭირდებათ ციფრული პროდუქტის შექმნა, მოდერნიზაცია ან ჩიხიდან გამოყვანა?", finalBody: "მოგვიყევით რეალურ პრობლემაზე — ვები, მობილური, გუნდის მიწოდება თუ AI სამუშაო პროცესი, რომელიც პროდაქშენისთვის ვარგისი უნდა გახდეს.",
  },
  ar: {
    role: "مدير هندسة · مهندس منتجات Web و Mobile و AI", themeToDark: "بدّل إلى الوضع الداكن", themeToLight: "بدّل إلى الوضع الفاتح", docsCta: "اقرأ وثائق الحزم",
    seo: { home: { title: "مدير هندسة · Web و Mobile و AI", description: "يجمع دينيس نادي خبرة تزيد على 11 عاماً في هندسة منتجات الويب ومنصات Mobile والقيادة الهندسية والمصادر المفتوحة والتسليم المدعوم بالذكاء الاصطناعي." }, work: { title: "أعمال في Web و Mobile والقيادة الهندسية", description: "أعمال مختارة لدينيس نادي في منتجات الويب ومنصات Mobile والتسليم والتقنية المالية والمصادر المفتوحة." }, services: { title: "خدمات هندسة Flutter و Web و AI", description: "هندسة منتجات على مستوى senior عبر الويب و Flutter وأنظمة التسليم والبنية المعمارية ومسارات عمل تطبيقية بالذكاء الاصطناعي." }, about: { title: "عن دينيس نادي · Web و Mobile و AI", description: "مدير هندسة ومهندس منتجات عملي، بجذور في الويب وخبرة عميقة في Mobile وممارسة تسليم مبنية على الذكاء الاصطناعي." }, contact: { title: "تواصل مع دينيس نادي · Web و Mobile و AI", description: "ناقش مع دينيس نادي منتج ويب أو Mobile، أو تحدياً في القيادة الهندسية، أو نظام تسليم، أو مسار عمل تطبيقياً بالذكاء الاصطناعي." } },
    home: {
      titleLead: "أبني منتجات رقمية — ", titleEmphasis: "من Web و Mobile إلى تسليم مدعوم بالذكاء الاصطناعي.", intro: "أكثر من 11 عاماً بين Web و Mobile والقيادة الهندسية: أكثر من 100 مشروع ويب، ومنصات Flutter في الإنتاج، وتسليم عبر عدة فرق، والذكاء الاصطناعي أداةً هندسية جادّة لا للتباهي.",
      proof: [{ value: "+11", label: "عاماً في هندسة البرمجيات" }, { value: "+100", label: "منتج ويب مُسلَّم" }, { value: "3", label: "فرق منتجات متزامنة" }, { value: "15", label: "مهندساً تحت قيادته" }, { value: "3", label: "حزم runtime عامة" }],
      mandateLabel: "هندسة كاملة الطيف", mandateTitle: "اتساع Web. عمق Mobile. تنفيذ AI-native.", mandateBody: "بدأ دينيس بإطلاق مواقع وأنظمة تجارة وأدوات إدارة وحاسبات ومدفوعات ومنتجات لتوليد العملاء المحتملين، ثم انتقل إلى منصات Mobile وقيادة عدة فرق. واليوم صار الذكاء الاصطناعي جزءاً من حلقة العمل الهندسية، من البحث والنماذج الأولية إلى التنفيذ والاختبارات والتوثيق، مع بقاء الحكم البشري مسؤولاً عن النتيجة.",
      capabilityLabel: "ثلاث نقاط قوة مترابطة", capabilityTitle: "مهندس واحد من الواجهة إلى الإنتاج.", capabilities: [
        { code: "WEB", title: "هندسة منتجات الويب", body: "بنية الواجهة الأمامية والمنتج، والتجارة الإلكترونية، والواجهات التشغيلية، والتكاملات، والأداء، وإمكانية الوصول، وأنظمة التسليم المحيطة بها.", evidence: "+100 مشروع ويب · مؤسس استوديو · AngularDart · React/Vinext حالياً" },
        { code: "MOB", title: "منصات Mobile والقيادة", body: "بنية Flutter، وحدود Kotlin/Swift، و CI/CD، والمتاجر، والمراقبة، وحوكمة الإصدارات، وقيادة عدة فرق.", evidence: "+11 عاماً إجمالاً · +6 في Flutter · 3 فرق · +80 إصداراً" },
        { code: "AI", title: "هندسة مدعومة بالذكاء الاصطناعي", body: "يُستخدم الذكاء الاصطناعي للبحث المنظم، واستكشاف الحلول، وبناء نماذج أولية للمنتج، والتنفيذ، ومراجعة الكود، وتصميم الاختبارات، والتوثيق التقني، لا لإنتاج مخرجات بلا مراجعة.", evidence: "مسارات عمل agentic · شرائح منتج سريعة · تسليم يبدأ بالتحقق" },
      ], careerTitle: "من تسليم الويب إلى منصات Mobile، والآن هندسة يشكّلها الذكاء الاصطناعي.", careerIntro: "المسار تراكمي: اتساع في منتجات الويب، وعمل عميق في أنظمة Mobile، وإدارة هندسية، وممارسة حديثة بمساعدة الذكاء الاصطناعي تزيد السرعة من دون التنازل عن المسؤولية.",
    },
    work: { title: "أعمال عبر منتجات الويب ومنصات Mobile وأنظمة التسليم.", intro: "برامج مختارة تولّى فيها دينيس مسؤولية التسليم أو جودة المنصة أو حدّاً صعباً في النظام. تبدأ المحفظة بهندسة منتجات الويب، ثم تتسع إلى بنية Mobile ومسؤولية عدة فرق.", webCase: { label: "05 · هندسة منتجات الويب", title: "أكثر من 100 منتج ويب قبل مرحلة Mobile", summary: "أساس من خمس سنوات في المواقع والتجارة الإلكترونية ولوحات التشغيل والحاسبات وتكاملات الدفع وأنظمة توليد العملاء المحتملين.", context: "احتاجت الشركات الصغيرة والمتوسطة إلى منتجات رقمية كاملة لا إلى واجهات معزولة: استكشاف المتطلبات، والتنفيذ، والاستضافة، والتكاملات، ومسار نحو استخدام قابل للقياس.", responsibility: "أسس استوديو ويب من شخصين إلى أربعة وقاده، وبقي منخرطاً بنفسه في الواجهة الأمامية ومنطق المنتج والتكاملات والتسليم والتواصل مع العملاء.", approach: "بنى حلولاً متناسبة للتجارة والإدارة والمدفوعات والحسابات وتوليد العملاء المحتملين، مختاراً أبسط بنية يمكن تشغيلها بعد التسليم.", outcome: "سلّم أكثر من 100 مشروع ويب صغير ومتوسط بين 2015 و2019، وكان ذلك الأساس لعمله اللاحق في المنتجات والمنصات والقيادة الهندسية.", stack: "HTML/CSS, JavaScript, PHP, منصات CMS وتجارة إلكترونية, تكاملات دفع, تحليلات, استضافة, AngularDart" } },
    services: { title: "هندسة منتجات على مستوى senior عبر Web و Mobile و AI.", intro: "استعن بدينيس عندما يحتاج منتج رقمي إلى مسؤولية موثوقة تمتد عبر الواجهة والبنية المعمارية والتسليم والإنتاج، ومسارات عمل الذكاء الاصطناعي الحديثة القادرة على تسريع كل مرحلة.", additions: [
      { title: "هندسة منتجات الويب وتحديثها", signal: "يحتاج منتج ويب إلى الانتقال من الفكرة إلى الإنتاج، أو أصبحت الواجهة الأمامية الحالية بطيئة أو هشة أو صعبة التوسيع.", action: "يوضّح تدفقات المنتج، ويعيد تشكيل حدود الواجهة الأمامية والتكامل، ويحسّن إمكانية الوصول والأداء، ويرسي مسار تسليم قابلاً للصيانة.", format: "بناء منتج مركّز، أو sprint تحديث، أو مراجعة معمارية، أو قيادة تقنية عملية." },
      { title: "مسارات عمل تطبيقية بالذكاء الاصطناعي ونماذج أولية للمنتجات", signal: "يريد الفريق استفادة حقيقية من الذكاء الاصطناعي، لكنه يحتاج إلى أكثر من عروض توضيحية أو مجموعات prompts أو كود مولَّد بلا مراجعة.", action: "يصمّم مسار عمل يبدأ بالتحقق للبحث والنماذج الأولية والتنفيذ والاختبار والتوثيق والمراجعة، ويبني شريحة بمواصفات الإنتاج لإثباته.", format: "تقييم لمسار العمل، أو sprint تمكين، أو نموذج أولي سريع للمنتج، أو دمج في نظام هندسي قائم." },
    ] },
    about: { title: "مهندس منتجات أولاً، قبل أي إطار عمل بعينه.", intro: "دينيس مدير هندسة ومهندس عملي بخبرة تزيد على 11 عاماً تمتد عبر منتجات الويب ومنصات Mobile وحزم runtime مفتوحة المصدر والتسليم المدعوم بالذكاء الاصطناعي.", paragraphs: ["بدأت المسيرة في الويب: استوديو صغير، وأكثر من 100 مشروع مُسلَّم، وتجارة إلكترونية، وأنظمة إدارة، ومدفوعات، وحاسبات، ومسارات توليد العملاء المحتملين. هذا الاتساع بنى عقلية منتج قبل الانتقال إلى الخدمات المصرفية والأسواق الإلكترونية والتقنية المالية و Flutter.", "أضاف العمل في Mobile قيوداً أعمق على مستوى المنصة: تكامل Kotlin و Swift، وتوقيع التطبيقات، والمتاجر، و CI/CD، والمراقبة، وحوادث الإنتاج، وبنية مشتركة عبر عدة تطبيقات. ثم وسّعت القيادة تلك المسؤولية لتشمل الـ Team Leads وخرائط الطريق والتوظيف وثلاثة فرق متزامنة.", "أصبح الذكاء الاصطناعي اليوم جزءاً من طريقة العمل. يستخدمه دينيس لاختصار البحث، واستكشاف البنى المعمارية، وبناء نماذج أولية للواجهات، وتنفيذ الكود ومراجعته، وتصميم الاختبارات، وإنتاج التوثيق. ويبقى المعيار كما هو: أدلة، ومفاضلات صريحة، وإنسان مسؤول عمّا يصل إلى الإنتاج."] },
    contact: { title: "حدّثنا عن القيد الحقيقي في منتجك.", intro: "منتج ويب يحتاج إلى مسار نحو الإنتاج، أو إصدار Mobile لا يستقر، أو فريق بمسؤولية غير واضحة، أو مسار عمل بالذكاء الاصطناعي يجب أن يتحول إلى هندسة موثوقة." },
    finalTitle: "هل تحتاج إلى بناء منتج رقمي أو تحديثه أو إزالة ما يعطّله؟", finalBody: "حدّثنا عن القيد الحقيقي: منتج ويب، أو Mobile، أو تسليم الفريق، أو مسار عمل بالذكاء الاصطناعي يجب أن يصبح جاهزاً للإنتاج.",
  },
};

export function getPositioning(locale: Locale): PositioningCopy {
  return positioning[locale];
}
