import type { CaseStudy, Locale, Service } from "./types";

type PositioningCopy = {
  role: string;
  themeToDark: string;
  themeToLight: string;
  docsCta: string;
  seo: {
    home: { title: string; description: string };
    work: { title: string; description: string };
    services: { title: string; description: string };
    about: { title: string; description: string };
    contact: { title: string; description: string };
  };
  home: {
    titleLead: string;
    titleEmphasis: string;
    intro: string;
    proof: Array<{ value: string; label: string }>;
    mandateLabel: string;
    mandateTitle: string;
    mandateBody: string;
    capabilityLabel: string;
    capabilityTitle: string;
    capabilities: Array<{ code: string; title: string; body: string; evidence: string }>;
    careerTitle: string;
    careerIntro: string;
  };
  work: { title: string; intro: string; webCase: CaseStudy };
  services: { title: string; intro: string; additions: Service[] };
  about: { title: string; intro: string; paragraphs: string[] };
  contact: { title: string; intro: string };
  finalTitle: string;
  finalBody: string;
};

export const positioning: Record<Locale, PositioningCopy> = {
  en: {
    role: "Engineering Manager · Web, Mobile & AI Product Engineer",
    themeToDark: "Switch to dark theme",
    themeToLight: "Switch to light theme",
    docsCta: "Read package documentation",
    seo: {
      home: { title: "Engineering Manager · Web, Mobile & AI", description: "Denis Nadey brings 11+ years across web product engineering, mobile platforms, engineering leadership, open source, and AI-enabled delivery." },
      work: { title: "Web, Mobile & Engineering Leadership Work", description: "Selected web product, mobile platform, delivery, fintech, and open-source engineering work by Denis Nadey." },
      services: { title: "Web, Mobile & AI Engineering Services", description: "Senior product engineering across web, Flutter, delivery systems, architecture, and practical AI-enabled workflows." },
      about: { title: "About Denis Nadey · Web, Mobile & AI", description: "An Engineering Manager and hands-on product engineer with roots in web, deep mobile experience, and an AI-native delivery practice." },
      contact: { title: "Contact Denis Nadey · Web, Mobile & AI", description: "Discuss a web or mobile product, engineering leadership challenge, delivery system, or practical AI workflow with Denis Nadey." },
    },
    home: {
      titleLead: "I build digital products—",
      titleEmphasis: "from web and mobile to AI-enabled delivery.",
      intro: "Eleven-plus years across web, mobile, and engineering leadership: 100+ web projects, production Flutter platforms, multi-team delivery, and AI used as a serious engineering tool—not a badge.",
      proof: [{ value: "11+", label: "years in software engineering" }, { value: "100+", label: "web products delivered" }, { value: "3", label: "concurrent product teams" }, { value: "15", label: "engineers led" }, { value: "3", label: "public runtime packages" }],
      mandateLabel: "Full-spectrum engineering",
      mandateTitle: "Web breadth. Mobile depth. AI-native execution.",
      mandateBody: "Denis started by shipping websites, commerce systems, admin tools, calculators, payments, and lead-generation products. He later moved into mobile platforms and multi-team leadership. Today, AI is part of the engineering loop—from research and prototyping to implementation, tests, and documentation—with human judgment kept accountable for the result.",
      capabilityLabel: "Three connected strengths",
      capabilityTitle: "One engineer across the product boundary.",
      capabilities: [
        { code: "WEB", title: "Web product engineering", body: "Frontend and product architecture, e-commerce, operational interfaces, integrations, performance, accessibility, and the delivery systems around them.", evidence: "100+ web projects · studio founder · AngularDart · current React/Vinext stack" },
        { code: "MOB", title: "Mobile platforms & leadership", body: "Flutter architecture, Kotlin/Swift boundaries, CI/CD, stores, observability, release governance, and leadership across several teams.", evidence: "11+ years total · 6+ Flutter · 3 teams · 80+ releases" },
        { code: "AI", title: "AI-enabled engineering", body: "AI used for structured research, solution exploration, product prototyping, implementation, code review, test design, and technical documentation—not unchecked output.", evidence: "Agentic workflows · rapid product slices · verification-first delivery" },
      ],
      careerTitle: "From web delivery to mobile platforms—and now AI-shaped engineering.",
      careerIntro: "The progression is cumulative: web product breadth, deep mobile systems work, engineering management, and a modern AI-assisted practice that increases speed without handing away responsibility.",
    },
    work: {
      title: "Work across web products, mobile platforms, and delivery systems.",
      intro: "Selected programs where Denis owned delivery, platform quality, or a difficult system boundary. The portfolio begins in web product engineering, then expands into mobile architecture and multi-team responsibility.",
      webCase: { label: "05 · Web product engineering", title: "More than 100 web products before the mobile chapter", summary: "A five-year foundation in websites, e-commerce, operational panels, calculators, payment integrations, and lead-generation systems.", context: "Small and medium businesses needed complete digital products, not isolated UI work: discovery, implementation, hosting, integrations, and a path to measurable use.", responsibility: "Founded and led a two-to-four-person web studio and remained hands-on across frontend, product logic, integrations, delivery, and client communication.", approach: "Built proportional solutions for commerce, administration, payments, calculations, and lead generation, choosing the simplest architecture that could be operated after handoff.", outcome: "Delivered more than 100 small-to-medium web projects between 2015 and 2019—the foundation for later product, platform, and engineering leadership work.", stack: "HTML/CSS, JavaScript, PHP, CMS and commerce platforms, payment integrations, analytics, hosting, AngularDart" },
    },
    services: {
      title: "Senior product engineering across web, mobile, and AI.",
      intro: "Bring Denis in when a digital product needs credible ownership across interface, architecture, delivery, production, and the modern AI workflows that can accelerate each stage.",
      additions: [
        { title: "Web product engineering & modernization", signal: "A web product needs to move from idea to production, or an existing frontend has become slow, fragile, or difficult to extend.", action: "Clarify product flows, reshape the frontend and integration boundaries, improve accessibility and performance, and establish a maintainable delivery path.", format: "Focused product build, modernization sprint, architecture review, or hands-on technical leadership." },
        { title: "Applied AI workflow & product prototyping", signal: "A team wants real leverage from AI but needs more than demos, prompt collections, or unreviewed generated code.", action: "Design a verification-first workflow for research, prototyping, implementation, testing, documentation, and review; build a production-shaped slice to prove it.", format: "Workflow assessment, enablement sprint, rapid product prototype, or integration into an existing engineering system." },
      ],
    },
    about: {
      title: "A product engineer before any single framework.",
      intro: "Denis is an Engineering Manager and hands-on engineer with 11+ years spanning web products, mobile platforms, open-source runtimes, and AI-enabled delivery.",
      paragraphs: [
        "The career started in web: a small studio, more than 100 delivered projects, commerce, admin systems, payments, calculators, and lead-generation flows. That breadth built a product mindset before the move into banking, marketplaces, fintech, and Flutter.",
        "Mobile work added deeper platform constraints—Kotlin and Swift integration, signing, stores, CI/CD, observability, production incidents, and shared architecture across multiple applications. Leadership later expanded that ownership to Team Leads, roadmaps, hiring, and three concurrent teams.",
        "AI is now part of the working method. Denis uses it to compress research, explore architectures, prototype interfaces, implement and review code, design tests, and produce documentation. The standard remains the same: evidence, explicit trade-offs, and a human owner for what reaches production.",
      ],
    },
    contact: { title: "Bring the real product constraint.", intro: "A web product that needs a production path, a mobile release that will not stabilize, a team with unclear ownership, or an AI workflow that must become reliable engineering." },
    finalTitle: "Need to build, modernize, or unblock a digital product?",
    finalBody: "Bring the real constraint—web, mobile, team delivery, or an AI workflow that needs to become production-worthy.",
  },
  ru: {
    role: "Engineering Manager · Web, Mobile и AI Product Engineer",
    themeToDark: "Включить тёмную тему", themeToLight: "Включить светлую тему", docsCta: "Читать документацию пакетов",
    seo: { home: { title: "Engineering Manager · Web, Mobile и AI", description: "11+ лет Дениса Надея в веб-продуктах, мобильных платформах, инженерном лидерстве, open source и AI-усиленной разработке." }, work: { title: "Web, Mobile и инженерное лидерство", description: "Веб-продукты, мобильные платформы, финтех, delivery и open-source инженерия Дениса Надея." }, services: { title: "Web, Mobile и AI-инженерия", description: "Разработка цифровых продуктов, Flutter, архитектура, delivery-системы и практические AI-workflows." }, about: { title: "Денис Надей · Web, Mobile и AI", description: "Engineering Manager и практикующий product engineer с фундаментом в вебе, глубиной в mobile и AI-native подходом." }, contact: { title: "Связаться с Денисом Надеем · Web, Mobile и AI", description: "Обсудить веб- или мобильный продукт, инженерное лидерство, delivery-систему или практический AI-workflow с Денисом Надеем." } },
    home: {
      titleLead: "Я создаю цифровые продукты —", titleEmphasis: "от web и mobile до AI-усиленной разработки.", intro: "11+ лет в web, mobile и инженерном лидерстве: 100+ веб-проектов, продакшен Flutter-платформы, несколько команд и AI как серьёзный инженерный инструмент, а не ярлык.",
      proof: [{ value: "11+", label: "лет в разработке" }, { value: "100+", label: "веб-продуктов выпущено" }, { value: "3", label: "параллельные продуктовые команды" }, { value: "15", label: "инженеров под руководством" }, { value: "3", label: "публичных runtime-пакета" }],
      mandateLabel: "Инженерия полного цикла", mandateTitle: "Широта в web. Глубина в mobile. AI-native исполнение.", mandateBody: "Денис начинал с сайтов, e-commerce, админок, калькуляторов, платежей и lead-generation систем. Затем перешёл к мобильным платформам и руководству несколькими командами. Сегодня AI встроен в инженерный цикл — от исследования и прототипа до реализации, тестов и документации — при сохранении человеческой ответственности за результат.",
      capabilityLabel: "Три связанные компетенции", capabilityTitle: "Один инженер по обе стороны продуктовой границы.",
      capabilities: [
        { code: "WEB", title: "Разработка веб-продуктов", body: "Frontend и продуктовая архитектура, e-commerce, операционные интерфейсы, интеграции, performance, accessibility и delivery вокруг продукта.", evidence: "100+ веб-проектов · основатель студии · AngularDart · React/Vinext сегодня" },
        { code: "MOB", title: "Мобильные платформы и лидерство", body: "Flutter, границы Kotlin/Swift, CI/CD, stores, observability, release governance и руководство несколькими командами.", evidence: "11+ лет · 6+ Flutter · 3 команды · 80+ релизов" },
        { code: "AI", title: "AI-усиленная инженерия", body: "AI для системного исследования, поиска решений, прототипирования, реализации, code review, проектирования тестов и документации — без слепого доверия к результату.", evidence: "Agentic workflows · быстрые product slices · verification-first delivery" },
      ],
      careerTitle: "От веб-разработки к mobile-платформам и AI-shaped engineering.", careerIntro: "Этот путь складывается слоями: продуктовая широта web, глубокие мобильные системы, engineering management и современный AI-assisted подход, который ускоряет работу, но не размывает ответственность.",
    },
    work: { title: "Web-продукты, мобильные платформы и delivery-системы.", intro: "Проекты, где Денис отвечал за поставку, качество платформы или сложную системную границу. Портфель начинается с web product engineering и расширяется до мобильной архитектуры и нескольких команд.", webCase: { label: "05 · Web product engineering", title: "Более 100 веб-продуктов до мобильной главы", summary: "Пять лет сайтов, e-commerce, операционных панелей, калькуляторов, платёжных интеграций и lead-generation систем.", context: "Малому и среднему бизнесу требовались полноценные цифровые продукты: исследование, интерфейс, бизнес-логика, интеграции, hosting и понятная эксплуатация.", responsibility: "Основал студию из двух-четырёх человек и оставался hands-on во frontend, продуктовой логике, интеграциях, delivery и работе с заказчиком.", approach: "Создавал соразмерные решения для commerce, администрирования, платежей, расчётов и привлечения клиентов, выбирая минимальную архитектуру, которую можно поддерживать после передачи.", outcome: "С 2015 по 2019 год выпустил более 100 веб-проектов — фундамент последующей продуктовой, платформенной и управленческой работы.", stack: "HTML/CSS, JavaScript, PHP, CMS и commerce-платформы, платежи, аналитика, hosting, AngularDart" } },
    services: { title: "Senior product engineering для web, mobile и AI.", intro: "Подключайте Дениса, когда продукту нужен один ответственный контур между интерфейсом, архитектурой, поставкой, продакшеном и AI-workflows, ускоряющими работу.", additions: [
      { title: "Web product engineering и модернизация", signal: "Нужно вывести веб-продукт из идеи в продакшен или существующий frontend стал медленным, хрупким и дорогим в изменениях.", action: "Уточняет продуктовые сценарии, перестраивает frontend и интеграционные границы, улучшает доступность и скорость, создаёт поддерживаемый delivery path.", format: "Разработка продукта, modernization sprint, architecture review или hands-on техническое лидерство." },
      { title: "Прикладные AI-workflows и прототипирование", signal: "Команда хочет реальную пользу от AI, а не набор демо, промптов и непроверенного сгенерированного кода.", action: "Строит verification-first процесс исследования, прототипирования, реализации, тестов, документации и review; доказывает его production-shaped срезом.", format: "Оценка workflow, enablement sprint, быстрый продуктовый прототип или интеграция в существующую инженерную систему." },
    ] },
    about: { title: "Product engineer до любого конкретного фреймворка.", intro: "Денис — Engineering Manager и hands-on инженер с 11+ годами в веб-продуктах, мобильных платформах, open-source runtime и AI-усиленной разработке.", paragraphs: ["Карьера началась в вебе: собственная небольшая студия, более 100 выпущенных проектов, commerce, admin systems, платежи, калькуляторы и lead-generation. Эта широта сформировала продуктовый взгляд до перехода в banking, marketplaces, fintech и Flutter.", "Mobile добавил глубокие платформенные ограничения: Kotlin/Swift, signing, stores, CI/CD, observability, продакшен-инциденты и общую архитектуру нескольких приложений. Затем leadership расширил ответственность до Team Lead, roadmap, найма и трёх параллельных команд.", "AI теперь встроен в способ работы: ускоряет исследование, варианты архитектуры, прототипирование интерфейсов, реализацию и review кода, тесты и документацию. Стандарт остаётся прежним: факты, явные компромиссы и человек, отвечающий за продакшен."] },
    contact: { title: "Приносите реальное ограничение продукта.", intro: "Веб-продукт без понятного пути в продакшен, нестабильный mobile-релиз, размытая ответственность в команде или AI-workflow, который пора превратить в надёжную инженерную систему." },
    finalTitle: "Нужно создать, модернизировать или разблокировать цифровой продукт?", finalBody: "Приносите реальное ограничение — web, mobile, delivery команды или AI-workflow, который пора довести до production уровня.",
  },
  de: {
    role: "Engineering Manager · Web, Mobile & AI Product Engineer", themeToDark: "Dunkles Design aktivieren", themeToLight: "Helles Design aktivieren", docsCta: "Paketdokumentation lesen",
    seo: { home: { title: "Engineering Manager · Web, Mobile & AI", description: "11+ Jahre Web-Produkte, Mobile-Plattformen, Engineering Leadership, Open Source und AI-gestützte Delivery." }, work: { title: "Web, Mobile & Engineering Leadership", description: "Ausgewählte Web-Produkte, Mobile-Plattformen, Delivery-, Fintech- und Open-Source-Arbeit von Denis Nadey." }, services: { title: "Web-, Mobile- & AI-Engineering", description: "Senior Product Engineering für Web, Flutter, Architektur, Delivery-Systeme und praktische AI-Workflows." }, about: { title: "Denis Nadey · Web, Mobile & AI", description: "Engineering Manager und hands-on Product Engineer mit Web-Wurzeln, Mobile-Tiefe und AI-nativer Delivery." }, contact: { title: "Denis Nadey kontaktieren · Web, Mobile & AI", description: "Web- oder Mobile-Produkte, Engineering Leadership, Delivery-Systeme oder praktische AI-Workflows mit Denis Nadey besprechen." } },
    home: { titleLead: "Ich baue digitale Produkte—", titleEmphasis: "von Web und Mobile bis AI-gestützter Delivery.", intro: "11+ Jahre in Web, Mobile und Engineering Leadership: 100+ Web-Projekte, produktive Flutter-Plattformen, mehrere Teams und AI als ernsthaftes Engineering-Werkzeug.", proof: [{ value: "11+", label: "Jahre Software Engineering" }, { value: "100+", label: "gelieferte Web-Produkte" }, { value: "3", label: "parallele Produktteams" }, { value: "15", label: "geführte Engineers" }, { value: "3", label: "öffentliche Runtime-Pakete" }], mandateLabel: "Engineering über den gesamten Stack", mandateTitle: "Web-Breite. Mobile-Tiefe. AI-native Umsetzung.", mandateBody: "Denis begann mit Websites, Commerce, Admin-Tools, Rechnern, Payment- und Lead-Systemen. Später kamen Mobile-Plattformen und Multi-Team-Führung hinzu. Heute gehört AI zum Engineering-Zyklus—von Research und Prototyping bis Code, Tests und Dokumentation, mit klarer menschlicher Verantwortung.", capabilityLabel: "Drei verbundene Stärken", capabilityTitle: "Ein Engineer über die Produktgrenzen hinweg.", capabilities: [
      { code: "WEB", title: "Web Product Engineering", body: "Frontend- und Produktarchitektur, E-Commerce, operative Interfaces, Integrationen, Performance, Accessibility und Delivery.", evidence: "100+ Web-Projekte · Studio-Gründer · AngularDart · heutiger React/Vinext-Stack" },
      { code: "MOB", title: "Mobile-Plattformen & Leadership", body: "Flutter, Kotlin/Swift-Grenzen, CI/CD, Stores, Observability, Release Governance und Führung mehrerer Teams.", evidence: "11+ Jahre · 6+ Flutter · 3 Teams · 80+ Releases" },
      { code: "AI", title: "AI-gestütztes Engineering", body: "AI für Research, Lösungsräume, Prototyping, Implementierung, Review, Testdesign und Dokumentation—mit konsequenter Verifikation.", evidence: "Agentic Workflows · schnelle Product Slices · verification-first Delivery" },
    ], careerTitle: "Vom Web-Delivery zu Mobile-Plattformen und AI-geprägtem Engineering.", careerIntro: "Der Weg ist kumulativ: Web-Produktbreite, tiefe Mobile-Systemarbeit, Engineering Management und AI-unterstützte Umsetzung ohne Verantwortungsverlust." },
    work: { title: "Web-Produkte, Mobile-Plattformen und Delivery-Systeme.", intro: "Ausgewählte Programme mit Verantwortung für Delivery, Plattformqualität oder schwierige Systemgrenzen—vom Web Product Engineering bis zur Multi-Team-Verantwortung.", webCase: { label: "05 · Web Product Engineering", title: "Mehr als 100 Web-Produkte vor dem Mobile-Kapitel", summary: "Fünf Jahre Websites, E-Commerce, Admin-Panels, Rechner, Payment-Integrationen und Lead-Systeme.", context: "Kleine und mittlere Unternehmen brauchten komplette digitale Produkte statt isolierter UI-Arbeit.", responsibility: "Gründete und führte ein Studio mit zwei bis vier Personen und blieb hands-on in Frontend, Produktlogik, Integrationen und Kundendialog.", approach: "Baute angemessene Lösungen für Commerce, Administration, Payments, Berechnungen und Lead-Generierung mit wartbarer Übergabe.", outcome: "Mehr als 100 kleine bis mittlere Web-Projekte von 2015 bis 2019—die Basis für spätere Plattform- und Führungsarbeit.", stack: "HTML/CSS, JavaScript, PHP, CMS, Commerce, Payments, Analytics, Hosting, AngularDart" } },
    services: { title: "Senior Product Engineering für Web, Mobile und AI.", intro: "Für digitale Produkte, die glaubwürdige Verantwortung zwischen Interface, Architektur, Delivery, Produktion und modernen AI-Workflows brauchen.", additions: [
      { title: "Web Product Engineering & Modernisierung", signal: "Ein Web-Produkt soll in Produktion oder ein Frontend ist langsam, fragil und schwer erweiterbar.", action: "Produktflows, Frontend- und Integrationsgrenzen, Accessibility, Performance und einen wartbaren Delivery-Pfad verbessern.", format: "Produktaufbau, Modernisierungssprint, Architekturreview oder hands-on technische Führung." },
      { title: "Angewandte AI-Workflows & Prototyping", signal: "Ein Team will echte AI-Hebel statt Demos, Prompt-Sammlungen oder ungeprüftem generierten Code.", action: "Verification-first Workflow für Research, Prototyping, Implementierung, Tests, Dokumentation und Review entwerfen und praktisch beweisen.", format: "Workflow-Assessment, Enablement-Sprint, schneller Produktprototyp oder Integration." },
    ] },
    about: { title: "Product Engineer vor jedem einzelnen Framework.", intro: "Engineering Manager und hands-on Engineer mit 11+ Jahren über Web-Produkte, Mobile-Plattformen, Open-Source-Runtimes und AI-gestützte Delivery.", paragraphs: ["Die Laufbahn begann im Web: eigenes kleines Studio, mehr als 100 Projekte, Commerce, Admin-Systeme, Payments, Rechner und Lead-Flows. Diese Breite prägte den Produktblick vor Banking, Marketplaces, Fintech und Flutter.", "Mobile ergänzte Kotlin/Swift, Signing, Stores, CI/CD, Observability, Incidents und gemeinsame Architektur über mehrere Apps. Leadership erweiterte die Verantwortung auf Team Leads, Roadmaps, Hiring und drei parallele Teams.", "AI ist heute Teil der Arbeitsweise: Research, Architekturvarianten, Interface-Prototypen, Implementierung, Review, Tests und Dokumentation. Der Maßstab bleibt: Evidenz, klare Trade-offs und ein Mensch mit Produktionsverantwortung."] },
    contact: { title: "Bringen Sie die echte Produktgrenze mit.", intro: "Ein Web-Produkt ohne Produktionspfad, ein instabiler Mobile-Release, unklare Teamverantwortung oder ein AI-Workflow, der zuverlässiges Engineering werden muss." },
    finalTitle: "Ein digitales Produkt bauen, modernisieren oder entblocken?", finalBody: "Bringen Sie die echte Einschränkung mit—Web, Mobile, Team-Delivery oder einen AI-Workflow auf dem Weg zur Produktion.",
  },
  fr: {
    role: "Engineering Manager · Web, Mobile & AI Product Engineer", themeToDark: "Passer au thème sombre", themeToLight: "Passer au thème clair", docsCta: "Lire la documentation des packages",
    seo: { home: { title: "Engineering Manager · Web, Mobile & AI", description: "11+ ans entre produits web, plateformes mobiles, leadership, open source et delivery assisté par l'AI." }, work: { title: "Web, Mobile & Engineering Leadership", description: "Produits web, plateformes mobiles, fintech, delivery et open source par Denis Nadey." }, services: { title: "Ingénierie Web, Mobile & AI", description: "Product engineering senior pour le web, Flutter, l'architecture, le delivery et les workflows AI." }, about: { title: "Denis Nadey · Web, Mobile & AI", description: "Engineering Manager et product engineer hands-on, du web aux plateformes mobiles et au delivery AI-native." }, contact: { title: "Contacter Denis Nadey · Web, Mobile & AI", description: "Échangeons sur un produit web ou mobile, le leadership engineering, un système de delivery ou un workflow AI concret." } },
    home: { titleLead: "Je construis des produits numériques—", titleEmphasis: "du web et mobile au delivery amplifié par l'AI.", intro: "11+ ans entre web, mobile et leadership : 100+ projets web, plateformes Flutter en production, plusieurs équipes et l'AI comme véritable outil d'ingénierie.", proof: [{ value: "11+", label: "ans d'ingénierie logicielle" }, { value: "100+", label: "produits web livrés" }, { value: "3", label: "équipes produit en parallèle" }, { value: "15", label: "ingénieurs encadrés" }, { value: "3", label: "packages runtime publics" }], mandateLabel: "Ingénierie de bout en bout", mandateTitle: "Largeur web. Profondeur mobile. Exécution AI-native.", mandateBody: "Denis a commencé par des sites, du commerce, des outils admin, des calculateurs, des paiements et de la génération de leads. Puis sont venus les plateformes mobiles et le leadership multi-équipes. Aujourd'hui, l'AI s'intègre au cycle—recherche, prototype, code, tests et documentation—avec une responsabilité humaine explicite.", capabilityLabel: "Trois forces reliées", capabilityTitle: "Un ingénieur à travers les frontières du produit.", capabilities: [
      { code: "WEB", title: "Web product engineering", body: "Architecture frontend et produit, e-commerce, interfaces opérationnelles, intégrations, performance, accessibilité et delivery.", evidence: "100+ projets web · fondateur de studio · AngularDart · stack React/Vinext actuelle" },
      { code: "MOB", title: "Plateformes mobiles & leadership", body: "Flutter, frontières Kotlin/Swift, CI/CD, stores, observabilité, gouvernance des releases et plusieurs équipes.", evidence: "11+ ans · 6+ Flutter · 3 équipes · 80+ releases" },
      { code: "AI", title: "Ingénierie amplifiée par l'AI", body: "AI pour recherche structurée, exploration, prototype, implémentation, review, conception des tests et documentation—avec vérification.", evidence: "Workflows agentiques · product slices rapides · delivery verification-first" },
    ], careerTitle: "Du delivery web aux plateformes mobiles et à l'ingénierie façonnée par l'AI.", careerIntro: "Une progression cumulative : largeur produit web, profondeur mobile, management et pratique AI-assisted qui accélère sans diluer la responsabilité." },
    work: { title: "Produits web, plateformes mobiles et systèmes de delivery.", intro: "Des programmes avec une responsabilité nette sur le delivery, la plateforme ou une frontière technique—du web product engineering au leadership multi-équipes.", webCase: { label: "05 · Web product engineering", title: "Plus de 100 produits web avant le chapitre mobile", summary: "Cinq ans de sites, e-commerce, outils admin, calculateurs, paiements et systèmes de leads.", context: "Les PME avaient besoin de produits numériques complets, pas d'une interface isolée.", responsibility: "Création et direction d'un studio de deux à quatre personnes, avec un rôle hands-on sur le frontend, la logique, les intégrations et les clients.", approach: "Solutions proportionnées pour commerce, administration, paiements, calcul et acquisition, avec une exploitation simple après livraison.", outcome: "Plus de 100 projets web livrés entre 2015 et 2019—le socle des responsabilités produit et plateforme suivantes.", stack: "HTML/CSS, JavaScript, PHP, CMS, commerce, paiements, analytics, hosting, AngularDart" } },
    services: { title: "Product engineering senior pour le web, le mobile et l'AI.", intro: "Pour un produit qui exige un ownership crédible entre interface, architecture, delivery, production et workflows AI modernes.", additions: [
      { title: "Web product engineering & modernisation", signal: "Un produit web doit atteindre la production ou un frontend est devenu lent, fragile ou coûteux à étendre.", action: "Clarifier les parcours, remodeler frontend et intégrations, améliorer accessibilité et performance, établir un delivery maintenable.", format: "Build produit, sprint de modernisation, revue d'architecture ou leadership hands-on." },
      { title: "Workflows AI appliqués & prototypage", signal: "Une équipe cherche un vrai levier AI au-delà des démos, prompts et code généré non vérifié.", action: "Concevoir un workflow verification-first pour recherche, prototype, code, tests, documentation et review, puis le prouver par un slice réaliste.", format: "Évaluation, sprint d'enablement, prototype rapide ou intégration." },
    ] },
    about: { title: "Product engineer avant tout framework.", intro: "Engineering Manager et ingénieur hands-on avec 11+ ans entre produits web, plateformes mobiles, runtimes open source et delivery AI-assisted.", paragraphs: ["Le parcours commence dans le web : petit studio, plus de 100 projets, commerce, systèmes admin, paiements, calculateurs et acquisition. Cette largeur a construit le regard produit avant la banque, les marketplaces, la fintech et Flutter.", "Le mobile a ajouté Kotlin/Swift, signing, stores, CI/CD, observabilité, incidents et architecture partagée. Le leadership a étendu l'ownership aux Team Leads, roadmaps, recrutement et trois équipes.", "L'AI fait maintenant partie de la méthode : recherche, options d'architecture, prototypes, implémentation, review, tests et documentation. Le standard reste l'évidence, les arbitrages explicites et un responsable humain en production."] },
    contact: { title: "Apportez la vraie contrainte produit.", intro: "Un produit web sans chemin de production, une release mobile instable, un ownership flou ou un workflow AI à transformer en ingénierie fiable." },
    finalTitle: "Construire, moderniser ou débloquer un produit numérique ?", finalBody: "Apportez la vraie contrainte—web, mobile, delivery d'équipe ou workflow AI à rendre crédible en production.",
  },
  es: {
    role: "Engineering Manager · Web, Mobile & AI Product Engineer", themeToDark: "Cambiar al tema oscuro", themeToLight: "Cambiar al tema claro", docsCta: "Leer documentación de paquetes",
    seo: { home: { title: "Engineering Manager · Web, Mobile & AI", description: "11+ años en productos web, plataformas móviles, liderazgo, open source y desarrollo asistido por AI." }, work: { title: "Web, Mobile y liderazgo de ingeniería", description: "Productos web, plataformas móviles, fintech, delivery y open source de Denis Nadey." }, services: { title: "Ingeniería Web, Mobile & AI", description: "Product engineering senior para web, Flutter, arquitectura, delivery y workflows de AI." }, about: { title: "Denis Nadey · Web, Mobile & AI", description: "Engineering Manager y product engineer hands-on, con raíces web, profundidad mobile y práctica AI-native." }, contact: { title: "Contactar con Denis Nadey · Web, Mobile & AI", description: "Hablemos de un producto web o mobile, liderazgo de ingeniería, sistemas de delivery o un workflow práctico de AI." } },
    home: { titleLead: "Construyo productos digitales—", titleEmphasis: "desde web y mobile hasta delivery potenciado por AI.", intro: "11+ años entre web, mobile y liderazgo: 100+ proyectos web, plataformas Flutter en producción, varios equipos y AI como herramienta seria de ingeniería.", proof: [{ value: "11+", label: "años de ingeniería" }, { value: "100+", label: "productos web entregados" }, { value: "3", label: "equipos en paralelo" }, { value: "15", label: "ingenieros liderados" }, { value: "3", label: "paquetes runtime públicos" }], mandateLabel: "Ingeniería de extremo a extremo", mandateTitle: "Amplitud web. Profundidad mobile. Ejecución AI-native.", mandateBody: "Denis empezó con sitios, comercio, herramientas admin, calculadoras, pagos y generación de leads. Después llegaron las plataformas móviles y el liderazgo multi-equipo. Hoy AI forma parte del ciclo—investigación, prototipo, código, pruebas y documentación—con responsabilidad humana clara.", capabilityLabel: "Tres fortalezas conectadas", capabilityTitle: "Un ingeniero a través de la frontera del producto.", capabilities: [
      { code: "WEB", title: "Web product engineering", body: "Arquitectura frontend y de producto, e-commerce, interfaces operativas, integraciones, rendimiento, accesibilidad y delivery.", evidence: "100+ proyectos web · fundador de estudio · AngularDart · stack React/Vinext actual" },
      { code: "MOB", title: "Plataformas móviles y liderazgo", body: "Flutter, límites Kotlin/Swift, CI/CD, stores, observabilidad, releases y liderazgo de varios equipos.", evidence: "11+ años · 6+ Flutter · 3 equipos · 80+ releases" },
      { code: "AI", title: "Ingeniería potenciada por AI", body: "AI para investigación, exploración, prototipos, implementación, review, diseño de pruebas y documentación, siempre verificada.", evidence: "Workflows agénticos · product slices rápidos · delivery verification-first" },
    ], careerTitle: "Del delivery web a plataformas móviles e ingeniería moldeada por AI.", careerIntro: "Una progresión acumulativa: amplitud web, profundidad mobile, management y una práctica AI-assisted que acelera sin ceder responsabilidad." },
    work: { title: "Productos web, plataformas móviles y sistemas de delivery.", intro: "Programas con responsabilidad clara sobre delivery, plataforma o una frontera difícil—del web product engineering al liderazgo multi-equipo.", webCase: { label: "05 · Web product engineering", title: "Más de 100 productos web antes del capítulo mobile", summary: "Cinco años de sitios, e-commerce, paneles, calculadoras, pagos y sistemas de generación de leads.", context: "Las pymes necesitaban productos digitales completos, no trabajo de UI aislado.", responsibility: "Fundó y lideró un estudio de dos a cuatro personas y siguió hands-on en frontend, lógica, integraciones y clientes.", approach: "Soluciones proporcionales para comercio, administración, pagos, cálculos y captación, operables tras la entrega.", outcome: "Más de 100 proyectos web entre 2015 y 2019—la base del trabajo posterior en producto, plataforma y liderazgo.", stack: "HTML/CSS, JavaScript, PHP, CMS, comercio, pagos, analytics, hosting, AngularDart" } },
    services: { title: "Product engineering senior para web, mobile y AI.", intro: "Para productos que necesitan ownership entre interfaz, arquitectura, delivery, producción y workflows AI modernos.", additions: [
      { title: "Web product engineering y modernización", signal: "Un producto web debe llegar a producción o el frontend es lento, frágil o difícil de ampliar.", action: "Aclarar flujos, rediseñar límites frontend e integración, mejorar accesibilidad y rendimiento, y crear un delivery mantenible.", format: "Build de producto, sprint de modernización, revisión o liderazgo hands-on." },
      { title: "Workflows AI aplicados y prototipado", signal: "El equipo busca valor real de AI más allá de demos, prompts y código sin revisar.", action: "Diseñar un workflow verification-first para investigar, prototipar, implementar, probar, documentar y revisar; demostrarlo con un slice realista.", format: "Assessment, sprint de enablement, prototipo rápido o integración." },
    ] },
    about: { title: "Product engineer antes que cualquier framework.", intro: "Engineering Manager e ingeniero hands-on con 11+ años en productos web, plataformas móviles, runtimes open source y delivery asistido por AI.", paragraphs: ["La carrera empezó en web: un pequeño estudio, más de 100 proyectos, comercio, sistemas admin, pagos, calculadoras y captación. Esa amplitud creó una mirada de producto antes de banking, marketplaces, fintech y Flutter.", "Mobile añadió Kotlin/Swift, signing, stores, CI/CD, observabilidad, incidentes y arquitectura compartida. El liderazgo amplió el alcance a Team Leads, roadmaps, contratación y tres equipos.", "AI es parte del método actual: investigación, opciones de arquitectura, prototipos, implementación, review, pruebas y documentación. El estándar sigue siendo evidencia, trade-offs explícitos y una persona responsable de producción."] },
    contact: { title: "Trae la restricción real del producto.", intro: "Un producto web sin camino a producción, una release mobile inestable, ownership poco claro o un workflow AI que debe convertirse en ingeniería fiable." },
    finalTitle: "¿Construir, modernizar o desbloquear un producto digital?", finalBody: "Trae la restricción real: web, mobile, delivery de equipo o un workflow AI que debe llegar a nivel de producción.",
  },
  it: {
    role: "Engineering Manager · Web, Mobile & AI Product Engineer", themeToDark: "Passa al tema scuro", themeToLight: "Passa al tema chiaro", docsCta: "Leggi la documentazione dei package",
    seo: { home: { title: "Engineering Manager · Web, Mobile & AI", description: "11+ anni tra prodotti web, piattaforme mobile, leadership, open source e delivery assistita dall'AI." }, work: { title: "Web, Mobile & Engineering Leadership", description: "Prodotti web, piattaforme mobile, fintech, delivery e open source di Denis Nadey." }, services: { title: "Ingegneria Web, Mobile & AI", description: "Product engineering senior per web, Flutter, architettura, delivery e workflow AI." }, about: { title: "Denis Nadey · Web, Mobile & AI", description: "Engineering Manager e product engineer hands-on con radici web, profondità mobile e pratica AI-native." }, contact: { title: "Contatta Denis Nadey · Web, Mobile & AI", description: "Parliamo di un prodotto web o mobile, engineering leadership, sistemi di delivery o workflow AI concreti." } },
    home: { titleLead: "Costruisco prodotti digitali—", titleEmphasis: "dal web e mobile alla delivery potenziata dall'AI.", intro: "11+ anni tra web, mobile e leadership: 100+ progetti web, piattaforme Flutter in produzione, più team e AI come vero strumento d'ingegneria.", proof: [{ value: "11+", label: "anni di engineering" }, { value: "100+", label: "prodotti web consegnati" }, { value: "3", label: "team prodotto paralleli" }, { value: "15", label: "engineer guidati" }, { value: "3", label: "package runtime pubblici" }], mandateLabel: "Engineering end-to-end", mandateTitle: "Ampiezza web. Profondità mobile. Esecuzione AI-native.", mandateBody: "Denis ha iniziato con siti, commerce, strumenti admin, calcolatori, pagamenti e lead generation. Poi sono arrivate piattaforme mobile e leadership multi-team. Oggi l'AI è nel ciclo—ricerca, prototipo, codice, test e documentazione—con responsabilità umana esplicita.", capabilityLabel: "Tre punti di forza connessi", capabilityTitle: "Un engineer attraverso i confini del prodotto.", capabilities: [
      { code: "WEB", title: "Web product engineering", body: "Architettura frontend e prodotto, e-commerce, interfacce operative, integrazioni, performance, accessibilità e delivery.", evidence: "100+ progetti web · fondatore di studio · AngularDart · stack React/Vinext attuale" },
      { code: "MOB", title: "Piattaforme mobile & leadership", body: "Flutter, confini Kotlin/Swift, CI/CD, store, osservabilità, release governance e più team.", evidence: "11+ anni · 6+ Flutter · 3 team · 80+ release" },
      { code: "AI", title: "Engineering potenziato dall'AI", body: "AI per ricerca, esplorazione, prototipi, implementazione, review, test design e documentazione—sempre verificata.", evidence: "Workflow agentici · product slice rapide · delivery verification-first" },
    ], careerTitle: "Dalla delivery web alle piattaforme mobile e all'engineering plasmato dall'AI.", careerIntro: "Una progressione cumulativa: ampiezza web, profondità mobile, management e pratica AI-assisted che accelera senza cedere responsabilità." },
    work: { title: "Prodotti web, piattaforme mobile e sistemi di delivery.", intro: "Programmi con responsabilità chiara su delivery, piattaforma o confini difficili—dal web product engineering alla leadership multi-team.", webCase: { label: "05 · Web product engineering", title: "Oltre 100 prodotti web prima del capitolo mobile", summary: "Cinque anni di siti, e-commerce, pannelli, calcolatori, pagamenti e lead-generation.", context: "Le PMI richiedevano prodotti digitali completi, non UI isolate.", responsibility: "Ha fondato e guidato uno studio di due-quattro persone, restando hands-on su frontend, logica, integrazioni e clienti.", approach: "Soluzioni proporzionate per commerce, amministrazione, pagamenti, calcoli e acquisizione, gestibili dopo il passaggio.", outcome: "Oltre 100 progetti web tra 2015 e 2019—la base del successivo lavoro di prodotto, piattaforma e leadership.", stack: "HTML/CSS, JavaScript, PHP, CMS, commerce, pagamenti, analytics, hosting, AngularDart" } },
    services: { title: "Product engineering senior per web, mobile e AI.", intro: "Per prodotti che richiedono ownership tra interfaccia, architettura, delivery, produzione e moderni workflow AI.", additions: [
      { title: "Web product engineering e modernizzazione", signal: "Un prodotto web deve arrivare in produzione o il frontend è lento, fragile e difficile da estendere.", action: "Chiarire i flussi, ridisegnare frontend e integrazioni, migliorare accessibilità e performance, creare una delivery mantenibile.", format: "Product build, sprint di modernizzazione, review o leadership hands-on." },
      { title: "Workflow AI applicati e prototipazione", signal: "Il team vuole valore reale dall'AI oltre demo, prompt e codice generato non verificato.", action: "Progettare un workflow verification-first per ricerca, prototipo, codice, test, documentazione e review; provarlo con una slice realistica.", format: "Assessment, enablement sprint, prototipo rapido o integrazione." },
    ] },
    about: { title: "Product engineer prima di ogni framework.", intro: "Engineering Manager e engineer hands-on con 11+ anni tra prodotti web, piattaforme mobile, runtime open source e delivery AI-assisted.", paragraphs: ["Il percorso parte dal web: piccolo studio, oltre 100 progetti, commerce, sistemi admin, pagamenti, calcolatori e acquisizione. Questa ampiezza ha costruito lo sguardo di prodotto prima di banking, marketplace, fintech e Flutter.", "Mobile ha aggiunto Kotlin/Swift, signing, store, CI/CD, osservabilità, incidenti e architettura condivisa. La leadership ha esteso l'ownership a Team Lead, roadmap, hiring e tre team.", "L'AI è ora parte del metodo: ricerca, opzioni architetturali, prototipi, implementazione, review, test e documentazione. Lo standard resta evidenza, trade-off espliciti e un responsabile umano per la produzione."] },
    contact: { title: "Porta il vero vincolo di prodotto.", intro: "Un prodotto web senza percorso di produzione, una release mobile instabile, ownership poco chiaro o un workflow AI da trasformare in engineering affidabile." },
    finalTitle: "Costruire, modernizzare o sbloccare un prodotto digitale?", finalBody: "Porta il vero vincolo—web, mobile, delivery del team o un workflow AI da rendere pronto per la produzione.",
  },
  pl: {
    role: "Engineering Manager · Web, Mobile & AI Product Engineer", themeToDark: "Włącz ciemny motyw", themeToLight: "Włącz jasny motyw", docsCta: "Czytaj dokumentację pakietów",
    seo: { home: { title: "Engineering Manager · Web, Mobile & AI", description: "11+ lat w produktach web, platformach mobilnych, leadershipie, open source i delivery wspieranym przez AI." }, work: { title: "Web, Mobile i Engineering Leadership", description: "Produkty web, platformy mobilne, fintech, delivery i open source Denisa Nadeya." }, services: { title: "Web, Mobile & AI Engineering", description: "Senior product engineering dla web, Flutter, architektury, delivery i workflow AI." }, about: { title: "Denis Nadey · Web, Mobile & AI", description: "Engineering Manager i hands-on product engineer z fundamentem web, głębią mobile i praktyką AI-native." }, contact: { title: "Kontakt z Denisem Nadeyem · Web, Mobile & AI", description: "Porozmawiajmy o produkcie web lub mobile, engineering leadership, systemie delivery albo praktycznym workflow AI." } },
    home: { titleLead: "Buduję produkty cyfrowe—", titleEmphasis: "od web i mobile po delivery wzmocnione przez AI.", intro: "11+ lat w web, mobile i leadershipie: 100+ projektów web, produkcyjne platformy Flutter, wiele zespołów i AI jako realne narzędzie inżynierskie.", proof: [{ value: "11+", label: "lat software engineering" }, { value: "100+", label: "dostarczonych produktów web" }, { value: "3", label: "równoległe zespoły" }, { value: "15", label: "prowadzonych inżynierów" }, { value: "3", label: "publiczne pakiety runtime" }], mandateLabel: "Engineering end-to-end", mandateTitle: "Szerokość web. Głębia mobile. AI-native execution.", mandateBody: "Denis zaczynał od stron, commerce, narzędzi admin, kalkulatorów, płatności i lead generation. Później doszły platformy mobilne i leadership wielu zespołów. Dziś AI jest częścią cyklu—research, prototyp, kod, testy i dokumentacja—z jasną odpowiedzialnością człowieka.", capabilityLabel: "Trzy połączone mocne strony", capabilityTitle: "Jeden inżynier ponad granicami produktu.", capabilities: [
      { code: "WEB", title: "Web product engineering", body: "Architektura frontend i produktu, e-commerce, interfejsy operacyjne, integracje, performance, accessibility i delivery.", evidence: "100+ projektów web · założyciel studia · AngularDart · obecny stack React/Vinext" },
      { code: "MOB", title: "Platformy mobile i leadership", body: "Flutter, granice Kotlin/Swift, CI/CD, store, observability, release governance i wiele zespołów.", evidence: "11+ lat · 6+ Flutter · 3 zespoły · 80+ releasów" },
      { code: "AI", title: "Engineering wzmocniony przez AI", body: "AI do researchu, eksploracji, prototypów, implementacji, review, projektowania testów i dokumentacji—z weryfikacją.", evidence: "Agentic workflows · szybkie product slices · verification-first delivery" },
    ], careerTitle: "Od web delivery do platform mobile i engineeringu kształtowanego przez AI.", careerIntro: "Kumulatywna ścieżka: szerokość web, głębia mobile, management i praktyka AI-assisted przy zachowaniu odpowiedzialności." },
    work: { title: "Produkty web, platformy mobile i systemy delivery.", intro: "Programy z odpowiedzialnością za delivery, platformę lub trudną granicę systemu—od web product engineering po multi-team leadership.", webCase: { label: "05 · Web product engineering", title: "Ponad 100 produktów web przed rozdziałem mobile", summary: "Pięć lat stron, e-commerce, paneli, kalkulatorów, płatności i lead-generation.", context: "Małe i średnie firmy potrzebowały pełnych produktów cyfrowych, nie izolowanego UI.", responsibility: "Założył i prowadził studio 2–4 osób, pozostając hands-on w frontendzie, logice, integracjach i pracy z klientem.", approach: "Proporcjonalne rozwiązania dla commerce, administracji, płatności, obliczeń i pozyskania klientów, możliwe do utrzymania po przekazaniu.", outcome: "Ponad 100 projektów web w latach 2015–2019—fundament późniejszej pracy produktowej, platformowej i leadershipu.", stack: "HTML/CSS, JavaScript, PHP, CMS, commerce, płatności, analytics, hosting, AngularDart" } },
    services: { title: "Senior product engineering dla web, mobile i AI.", intro: "Dla produktów wymagających ownershipu między interfejsem, architekturą, delivery, produkcją i nowoczesnymi workflow AI.", additions: [
      { title: "Web product engineering i modernizacja", signal: "Produkt web ma wejść na produkcję albo frontend jest wolny, kruchy i trudny do rozwijania.", action: "Uporządkować flow, granice frontendu i integracji, accessibility, performance oraz utrzymywalną ścieżkę delivery.", format: "Budowa produktu, sprint modernizacyjny, review lub hands-on leadership." },
      { title: "Praktyczne workflow AI i prototypowanie", signal: "Zespół chce realnej wartości z AI, nie tylko demo, promptów i niezweryfikowanego kodu.", action: "Zaprojektować verification-first workflow dla researchu, prototypu, kodu, testów, dokumentacji i review, a potem udowodnić je realistycznym slice'em.", format: "Assessment, enablement sprint, szybki prototyp lub integracja." },
    ] },
    about: { title: "Product engineer przed każdym frameworkiem.", intro: "Engineering Manager i hands-on engineer z 11+ latami w produktach web, platformach mobile, runtime open source i delivery wspieranym AI.", paragraphs: ["Kariera zaczęła się w web: małe studio, ponad 100 projektów, commerce, systemy admin, płatności, kalkulatory i lead generation. Ta szerokość zbudowała myślenie produktowe przed bankingiem, marketplace, fintechem i Flutterem.", "Mobile dodał Kotlin/Swift, signing, store, CI/CD, observability, incydenty i wspólną architekturę. Leadership rozszerzył odpowiedzialność na Team Leadów, roadmapy, hiring i trzy zespoły.", "AI jest dziś częścią metody: research, opcje architektury, prototypy, implementacja, review, testy i dokumentacja. Standard to nadal dowody, jawne trade-offy i człowiek odpowiedzialny za produkcję."] },
    contact: { title: "Przynieś prawdziwe ograniczenie produktu.", intro: "Produkt web bez drogi do produkcji, niestabilny release mobile, niejasny ownership albo workflow AI, który ma stać się niezawodnym engineeringiem." },
    finalTitle: "Zbudować, zmodernizować lub odblokować produkt cyfrowy?", finalBody: "Przynieś realne ograniczenie—web, mobile, delivery zespołu albo workflow AI, które ma wejść na poziom produkcyjny.",
  },
  pt: {
    role: "Engineering Manager · Web, Mobile & AI Product Engineer", themeToDark: "Mudar para tema escuro", themeToLight: "Mudar para tema claro", docsCta: "Ler documentação dos pacotes",
    seo: { home: { title: "Engineering Manager · Web, Mobile & AI", description: "11+ anos em produtos web, plataformas mobile, liderança, open source e delivery assistido por AI." }, work: { title: "Web, Mobile e Engineering Leadership", description: "Produtos web, plataformas mobile, fintech, delivery e open source de Denis Nadey." }, services: { title: "Engenharia Web, Mobile & AI", description: "Product engineering sênior para web, Flutter, arquitetura, delivery e workflows de AI." }, about: { title: "Denis Nadey · Web, Mobile & AI", description: "Engineering Manager e product engineer hands-on com base em web, profundidade mobile e prática AI-native." }, contact: { title: "Fale com Denis Nadey · Web, Mobile & AI", description: "Converse sobre um produto web ou mobile, liderança de engenharia, sistemas de delivery ou workflows práticos de AI." } },
    home: { titleLead: "Construo produtos digitais—", titleEmphasis: "de web e mobile a delivery potencializado por AI.", intro: "11+ anos entre web, mobile e liderança: 100+ projetos web, plataformas Flutter em produção, vários times e AI como ferramenta séria de engenharia.", proof: [{ value: "11+", label: "anos de software engineering" }, { value: "100+", label: "produtos web entregues" }, { value: "3", label: "times em paralelo" }, { value: "15", label: "engenheiros liderados" }, { value: "3", label: "pacotes runtime públicos" }], mandateLabel: "Engenharia ponta a ponta", mandateTitle: "Amplitude web. Profundidade mobile. Execução AI-native.", mandateBody: "Denis começou com sites, commerce, ferramentas admin, calculadoras, pagamentos e geração de leads. Depois vieram plataformas mobile e liderança de vários times. Hoje AI faz parte do ciclo—pesquisa, protótipo, código, testes e documentação—com responsabilidade humana explícita.", capabilityLabel: "Três forças conectadas", capabilityTitle: "Um engenheiro através da fronteira do produto.", capabilities: [
      { code: "WEB", title: "Web product engineering", body: "Arquitetura frontend e de produto, e-commerce, interfaces operacionais, integrações, performance, acessibilidade e delivery.", evidence: "100+ projetos web · fundador de estúdio · AngularDart · stack React/Vinext atual" },
      { code: "MOB", title: "Plataformas mobile e liderança", body: "Flutter, limites Kotlin/Swift, CI/CD, stores, observabilidade, releases e liderança de vários times.", evidence: "11+ anos · 6+ Flutter · 3 times · 80+ releases" },
      { code: "AI", title: "Engenharia potencializada por AI", body: "AI para pesquisa, exploração, protótipos, implementação, review, design de testes e documentação—com verificação.", evidence: "Workflows agênticos · product slices rápidos · delivery verification-first" },
    ], careerTitle: "Do delivery web a plataformas mobile e engenharia moldada por AI.", careerIntro: "Uma progressão cumulativa: amplitude web, profundidade mobile, management e prática AI-assisted que acelera sem abrir mão da responsabilidade." },
    work: { title: "Produtos web, plataformas mobile e sistemas de delivery.", intro: "Programas com responsabilidade clara sobre delivery, plataforma ou uma fronteira difícil—do web product engineering à liderança multi-time.", webCase: { label: "05 · Web product engineering", title: "Mais de 100 produtos web antes do capítulo mobile", summary: "Cinco anos de sites, e-commerce, painéis, calculadoras, pagamentos e lead-generation.", context: "Pequenas e médias empresas precisavam de produtos digitais completos, não apenas UI isolada.", responsibility: "Fundou e liderou um estúdio de duas a quatro pessoas, mantendo atuação hands-on em frontend, lógica, integrações e clientes.", approach: "Soluções proporcionais para commerce, administração, pagamentos, cálculos e aquisição, operáveis após a entrega.", outcome: "Mais de 100 projetos web entre 2015 e 2019—base para o trabalho posterior em produto, plataforma e liderança.", stack: "HTML/CSS, JavaScript, PHP, CMS, commerce, pagamentos, analytics, hosting, AngularDart" } },
    services: { title: "Product engineering sênior para web, mobile e AI.", intro: "Para produtos que exigem ownership entre interface, arquitetura, delivery, produção e workflows modernos de AI.", additions: [
      { title: "Web product engineering e modernização", signal: "Um produto web precisa chegar à produção ou o frontend ficou lento, frágil e difícil de evoluir.", action: "Clarificar fluxos, redesenhar limites de frontend e integração, melhorar acessibilidade e performance e criar delivery sustentável.", format: "Build de produto, sprint de modernização, review ou liderança hands-on." },
      { title: "Workflows aplicados de AI e prototipagem", signal: "O time busca valor real de AI além de demos, prompts e código gerado sem revisão.", action: "Desenhar um workflow verification-first para pesquisa, protótipo, implementação, testes, documentação e review; prová-lo com uma slice realista.", format: "Assessment, enablement sprint, protótipo rápido ou integração." },
    ] },
    about: { title: "Product engineer antes de qualquer framework.", intro: "Engineering Manager e engineer hands-on com 11+ anos em produtos web, plataformas mobile, runtimes open source e delivery assistido por AI.", paragraphs: ["A carreira começou no web: pequeno estúdio, mais de 100 projetos, commerce, sistemas admin, pagamentos, calculadoras e geração de leads. Essa amplitude criou visão de produto antes de banking, marketplaces, fintech e Flutter.", "Mobile adicionou Kotlin/Swift, signing, stores, CI/CD, observabilidade, incidentes e arquitetura compartilhada. A liderança ampliou o ownership para Team Leads, roadmaps, contratação e três times.", "AI hoje faz parte do método: pesquisa, opções de arquitetura, protótipos, implementação, review, testes e documentação. O padrão continua sendo evidência, trade-offs explícitos e uma pessoa responsável pela produção."] },
    contact: { title: "Traga a restrição real do produto.", intro: "Um produto web sem caminho para produção, uma release mobile instável, ownership pouco claro ou um workflow AI que precisa virar engenharia confiável." },
    finalTitle: "Construir, modernizar ou desbloquear um produto digital?", finalBody: "Traga a restrição real—web, mobile, delivery do time ou um workflow AI que precisa chegar ao nível de produção.",
  },
};

export function getPositioning(locale: Locale): PositioningCopy {
  return positioning[locale];
}
