// Writes content/build-info.ts with the date of the last commit so the sitemap
// reports a real lastmod. Runs automatically before `npm run build` (prebuild).
import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";

let date = "";
try {
  date = execSync("git log -1 --format=%cI", { stdio: ["ignore", "pipe", "ignore"] }).toString().trim();
} catch {
  date = "";
}
if (!/^\d{4}-\d{2}-\d{2}T/.test(date)) date = new Date().toISOString();

const target = new URL("../content/build-info.ts", import.meta.url);
writeFileSync(target, `// Generated by scripts/build-info.mjs before each build. Do not edit by hand.\nexport const contentUpdatedAt = "${date}";\n`);
console.log(`content/build-info.ts → ${date}`);
